platformplatform/PlatformPlatform

.github/PULL_REQUEST_TEMPLATE.md
Add a pull request template to ensure that all pull requests have high quality. Include a checklist to ensure that all pull requests have a label and remind the contributor to update documentation.
=> Create a pull request template to ensure consistent high quality pull requests

.github/workflows/account-management-tests.yml, .github/workflows/account-management.yml
Ensure that CI builds run JetBrains code inspections during the CI build process. Add any findings as comments on the pull request for easy resolution.
=> Run JetBrains code inspections during CI builds

account-management/src/Domain/Shared/Entity.cs, account-management/src/Domain/Shared/EntityEqualityComparer.cs, account-management/src/Domain/Shared/IdGenerator.cs, account-management/src/Domain/Shared/StronglyTypedId.cs, account-management/src/Infrastructure/Shared/UnitOfWork.cs, account-management/src/WebApi/Program.cs, account-management/tests/Tests/Domain/Shared/EntityEqualityComparerTests.cs, account-management/tests/Tests/Domain/Shared/EntityTests.cs, account-management/tests/Tests/Domain/Shared/IdGeneratorTests.cs
Fix code smells found by SonarCloud
=> Fix code smells

.github/workflows/account-management.yml
Add caching of SonarCloud packages used in GitHub actions.
=> Add caching of SonarCloud packages

.github/workflows/account-management.yml, account-management/src/WebApi/Endpoints/TestEndpoints.cs, account-management/src/WebApi/Program.cs, account-management/src/WebApi/Shared/GlobalExceptionHandlerMiddleware.cs, account-management/src/WebApi/WebApi.csproj, account-management/src/WebApi/WebApiConfiguration.cs, account-management/tests/Tests/WebApi/Shared/CustomExceptionHandlingTests.cs
Implement a global exception handler to efficiently manage and process unhandled exceptions throughout the application. Add test endpoints that simulate throwing exceptions. Utilize an environment variable to set up this endpoint only when running tests, ensuring it is not enabled in production or developer environments.
=> Add global exception handler

account-management/src/Application/Application.csproj, account-management/src/Application/ApplicationConfiguration.cs, account-management/src/Domain/DomainConfiguration.cs, account-management/src/Domain/Shared/Entity.cs, account-management/src/Domain/Shared/ValidationUtils.cs, account-management/src/Infrastructure/InfrastructureConfiguration.cs, account-management/src/Infrastructure/Shared/SaveChangesInterceptor.cs, account-management/src/WebApi/Shared/GlobalExceptionHandlerMiddleware.cs, account-management/src/WebApi/WebApiConfiguration.cs, account-management/tests/Tests/ArchitectureTests/PublicClassesTests.cs
Perform minor refactoring, code cleanup, documentation updates, and other incremental improvements for enhanced code readability and maintainability.
=> Incremental improvements for enhanced code readability and maintainability

account-management/src/Foundation/Application/CommandResult.cs, account-management/src/Foundation/Application/QueryResult.cs, account-management/src/Foundation/Domain/AggregateRoot.cs, account-management/src/Foundation/Infrastructure/UnitOfWork.cs, account-management/src/Foundation/WebApi/GlobalExceptionHandlerMiddleware.cs, account-management/src/Infrastructure/ApplicationDbContext.cs, account-management/src/Infrastructure/Migrations/20230429131456_Initial.cs, account-management/src/Infrastructure/Tenants/TenantRepository.cs, account-management/src/WebApi/Program.cs, account-management/tests/Foundation.Tests/Infrastructure/RepositoryTests.cs, account-management/tests/Foundation.Tests/Infrastructure/SqliteInMemoryDbContextFactory.cs, account-management/tests/Foundation.Tests/TestEntities/TestAggregateRepository.cs, account-management/tests/Foundation.Tests/TestEntities/TestDbContext.cs, account-management/tests/Tests/ArchitectureTests/PublicClassesTests.cs, account-management/tests/Tests/Domain/TenantTests.cs, account-management/tests/Tests/Infrastructure/SqliteInMemoryDbContextFactory.cs
Make TestDbContext inherit from FoundationDbContext to enhance test accuracy, and modify TestAggregateRepository to utilize TestDbContext.TestAggregates instead of testDbContext.Set<TestAggregate>. Add a new test to ensure entity changes require an explicit Repository.Update call due to disabled EF tracking. Introduce architectural tests to verify that public classes in Infrastructure are sealed. Also, seal CommandResult, QueryResult, UnitOfWork, and GlobalExceptionHandlerMiddleware.Add a test for Tenant aggregate validation.
Change DomainEvents in AggregateRoot from IReadOnlyList to IReadOnlyCollection. Correct FindAsync in TenantRepository by adding cancellationToken as a potential key. Remove unused "Hello World!" endpoint from WebApi.
=> Improve tests and other small improvements

account-management/Application/Tenants/CreateTenant.cs, account-management/Application/Users/CreateUser.cs, account-management/Tests/Api/Tenants/TenantEndpointsTests.cs, account-management/Tests/Api/Users/UserEndpointsTests.cs
Refactor the Tenant and UserEndpointsTest to further enhance their consistency and improve their structure and readability.
Additionally, remove the unused UserRepository in the TenantValidation component as it is no longer needed.
=> Clean up and improve the consistency of the API endpoint tests

account-management/Api/Api.csproj, account-management/Api/Tenants/TenantEndpoints.cs, account-management/Api/Users/UserEndpoints.cs, account-management/Application/Application.csproj, account-management/Application/Tenants/CreateTenant.cs, account-management/Application/Users/CreateUser.cs, account-management/Infrastructure/Infrastructure.csproj, account-management/Tests/Api/ApiCore/CustomExceptionHandlingTests.cs, account-management/Tests/Api/BaseApiTest.cs, account-management/Tests/Api/Tenants/TenantEndpointsTests.cs, account-management/Tests/Api/Users/UserEndpointsTests.cs, account-management/Tests/Application/Tenants/CreateTenantValidationTests.cs, account-management/Tests/Application/Tenants/TenantCreatedEventHandlerTests.cs, account-management/Tests/BaseTest.cs, account-management/Tests/SqliteConnectionExtensions.cs, account-management/Tests/Tests.csproj, shared-kernel/ApiCore/ApiCore.csproj, shared-kernel/ApiCore/ApiResults/ApiResult.cs, shared-kernel/ApiCore/AspNetCoreUtilsConfiguration.cs, shared-kernel/ApiCore/Middleware/GlobalExceptionHandlerMiddleware.cs, shared-kernel/ApiCore/Middleware/ModelBindingExceptionHandlerMiddleware.cs, shared-kernel/ApplicationCore/ApplicationCore.csproj, shared-kernel/ApplicationCore/Behaviors/PublishDomainEventsPipelineBehavior.cs, shared-kernel/DomainCore/DomainCore.csproj, shared-kernel/InfrastructureCore/InfrastructureCore.csproj, shared-kernel/InfrastructureCore/InfrastructureCoreConfiguration.cs, shared-kernel/Tests/Tests.csproj
Update Tests and Validation for Improved Consistency, JSON Schema Validation, and Error Handling
Simplify TenantValidation to return the same validation error when subdomain length and alphanumeric characters are invalid. Ensure consistency in error messaging.
Add tests to validate proper error responses when creating users in scenarios where the Tenant does not exist or when an existing user already has the same email.
Implement JSON Schema validation using NJsonSchema to validate the structure of JSON responses in the Tenant and User tests.
Introduce a new RowExists extension method to SqliteConnection, simplifying the process of checking if a database row exists.
Refactor CustomExceptionHandlingTests to utilize the BaseApiTests.EnsureErrorStatusCode method, ensuring consistent and …
=> Enhance tests, validation, and error handling for improved consistency and functionality

account-management/Application/Tenants/TenantValidator.cs, account-management/Application/Users/UserValidator.cs, account-management/Tests/Api/Tenants/TenantEndpointsTests.cs, account-management/Tests/Api/Users/UserEndpointsTests.cs, account-management/Tests/Application/Tenants/CreateTenantValidationTests.cs, account-management/Tests/BaseTest.cs, account-management/Tests/FakerExtensions.cs, account-management/Tests/SqliteConnectionExtensions.cs, account-management/Tests/Tests.csproj, shared-kernel/ApplicationCore/Behaviors/ValidationPipelineBehavior.cs, shared-kernel/ApplicationCore/Validation/SharedValidations.cs
Integrate the Bogus .NET library to facilitate the generation of fake test data, clearly indicating when data is synthetic or carries a specific meaning. Implement extension methods to generate domain-specific data such as subdomains/TenantIds, TenantNames, PhoneNumbers, Snowflake IDs, and more.
Fix minor validation issues in the User commands by ensuring it utilizes the same Email validation logic as when creating a tenant.
Update the ValidationPipelineBehavior to handle duplicated validation errors appropriately. Specifically, ignore duplicate errors related to the same property, preventing redundant error messages.
Enhance the SqliteConnectionExtensions.ExecuteScalar extension method to support multiple parameters when executing SQL queries. This improvement allows for more flexible …
=> Improve test data generation with Bogus library and add domain-specific extensions

.github/workflows/platformplatform-build-and-test.yml, cloud-infrastructure/README.md, cloud-infrastructure/modules/container-app.bicep, cloud-infrastructure/modules/container-registry-permission.bicep, cloud-infrastructure/shared/deploy-shared.sh
Ensure consistent role assignment naming while maintaining required uniqueness in Azure AD.
Enhance the clarity of the user-assigned identity name to reflect permissions granted in the Azure Container Registry.
Configure the hello-world container image to use the amd64 architecture, even when running on an Apple Silicon MacBook.
Revise instructions for setting the CLUSTER_UNIQUE_NAME environment variable when running on localhost.
=> Enhancements for role assignment and identity naming

.github/workflows/azure-infrastructure-change-preview.yml, .github/workflows/azure-infrastructure-deployment.yml, cloud-infrastructure/README.md, cloud-infrastructure/bicepconfig.json, cloud-infrastructure/cluster/config/development-west-europe.sh, cloud-infrastructure/cluster/main-cluster.bicep, cloud-infrastructure/environment/config/development.sh, cloud-infrastructure/environment/main-environment.bicep, cloud-infrastructure/modules/application-insights.bicep, cloud-infrastructure/modules/container-app.bicep, cloud-infrastructure/modules/container-apps-environment.bicep, cloud-infrastructure/modules/container-registry-permission.bicep, cloud-infrastructure/modules/container-registry.bicep, cloud-infrastructure/modules/key-vault.bicep, cloud-infrastructure/modules/microsoft-sql-server-diagnostic.bicep, cloud-infrastructure/modules/microsoft-sql-server.bicep, cloud-infrastructure/modules/service-bus.bicep, cloud-infrastructure/modules/virtual-network.bicep, cloud-infrastructure/shared/config/shared-development.sh, cloud-infrastructure/shared/deploy-shared.sh, cloud-infrastructure/shared/main-shared.bicep
Enable inbound traffic on ports 80 and 443 and disable sticky sessions in the Container App.
Optimize and fix the Bicep files. Upgrade all Bicep resources to the latest (preview) version. Introduce a Bicep configuration file with pretty printing rules and perform a cleanup of all Bicep files. Resolve the Bicep warning when CPU is entered as decimal by using  "json decimal", and also set the scale for replicas to 0. Add Bicep configuration to Container Apps Environment and Service Bus to prevent change detection. Also, ensure GitHub Actions uses the latest Bicep CLI version. Ensure GitHub Actions uses the latest Bicep CLI version.
Replace the dummy image in the `account-management-api` with `mcr.microsoft.com/k8se/quickstart`. This image does not generate any security warnings and it …
=> Add inbound traffic support, optimize Bicep code, and establish dev environment for simplified experiments

shared-kernel/ApiCore/Endpoints/TestEndpoints.cs, shared-kernel/InfrastructureCore/EntityFramework/UpdateAuditableEntitiesInterceptor.cs, shared-kernel/InfrastructureCore/InfrastructureCoreConfiguration.cs
Refine the codebase by addressing SonarCloud warnings, specifically by substituting generic exceptions such as Exception and NullReferenceException with more descriptive, specific exceptions to enhance clarity and error handling.
=> Replace general exceptions like Exception, NullReferenceException with specific exceptions

README.md, application/README.md
Minor update of the README files with a description of how .NET Aspire is utilized in the project. Additionally, it includes a small GIF demonstrating the F5 experience. This visual aid provides a clear and engaging way for users and contributors to understand the ease and functionality of the F5 setup, thanks to .NET Aspire integration.
=> Update README files to showcase the use of .NET Aspire

application/shared-kernel/ApiCore/Endpoints/TrackEndpoints.cs
Location is missing from Application Insights. We need to pass on the client ip for location to be resolved.
The ip address is then replaced with "0.0.0.0" in Application Insights.
=> Set location ip in track endpoint for client ip

developer-cli/Commands/Translate.cs, developer-cli/Installation/PrerequisitesChecker.cs, developer-cli/Program.cs
This pull requests includes the following:
- Method renaming.
- Change how we display messages for missing command line tools and workload tools.
- Automatically run `pp configure-developer-environment` if we the developer environment is not configured yet. 
- The translate command is configured so that it requires docker to be installed.
=> Improve first time CLI installation

application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
We need to clear network and proxy lists for extracting the client ip correctly
=> Fix proxy support setting correct client IP Address

application/shared-kernel/ApiCore/Aspire/ServiceDefaultsExtensions.cs
Filter out health, tracking endpoints from OpenTelemetry to filter out unnecessary tracking
=> Filter health endpoints from OpenTelemetry

.github/CODEOWNERS, .github/CONTRIBUTING.md, .github/SECURITY.md, README.md
Update the README for PlatformPlatform to include a new, visually engaging banner. Additionally, the introduction is revised to accurately reflect the project's current state and progress. A detailed explanation of the monorepo structure is added, providing clarity on the organization and management of the project's various components.
In the Contributing Guidelines, clarification has been added to encourage the initiation of discussions rather than the creation of issues for new contributions. The guidelines are also fine-tuned to underscore the project's commitment to high standards, its opinionated approach, and the intention to merge pull requests swiftly.
The Security Policy has been updated to instruct the use of GitHub's security advisory form, instead of reporting using emails. …
=> Enhance README and project documentation for PlatformPlatform

README.md
Update the readme to reflect the current state of the project. The intro describes what PlatformPlatform is and the getting started has been updated to include 5 clear steps.
=> Update README with new intro and clear steps for getting started

README.md
Update the intro in the readme with bullets outlining the building blocks.
Remove the sections about GitHub services used.
=> Minor update to README intro to make it more readable

README.md
Fix the broken in the README to the mono repository section.
=> Fix broken link for the mono repository section

application/account-management/WebApp/rspack.config.ts
Added loader support for using images in the WebApp. Also added support for
=> WebApp image support

application/shared-kernel/ApiCore/Middleware/WebAppMiddleware.cs
Add more Content Security Policies and security headers to improve security and lighthouse scores
=> WebApp add more CSP and security headers

application/shared-kernel/ApiCore/ApiCoreConfiguration.cs, application/shared-kernel/ApiCore/Middleware/SecurityHeaderMiddleware.cs
Add initial security headers and remove the server header for improved security score.
- [*] I have added a Label to the pull-request
- [*] I have added tests, and done manual regression tests
- [*] I have updated the documentation, if necessary
=> Add middleware security headers 

application/account-management/Api/Program.cs, application/shared-kernel/ApiCore/Middleware/WebAppMiddleware.cs
We want all middlewares to implement IMiddleware / moving towards factory based middleware
=> Refactor WebAppMiddleware into IMiddleware

README.md, cloud-infrastructure/cluster/main-cluster.bicep, cloud-infrastructure/modules/communication-services.bicep, cloud-infrastructure/modules/container-app.bicep, cloud-infrastructure/modules/key-vault.bicep
Create new Azure Communication Service Resource. Create an Azure Email Configuration Service and add it to the Communication Service. Configured a no-reply@xxxx-xxxx-xx.azurecomm.net email named PlatformPlatform to allow sending up to 30 emails per minute and max 100 mails per hour (configuring a valid email domain will allow for unlimited mails).
Add Communication Service connection string to Azure Key Vault (as it does not support managed identities) and configure Key Vault to allow Azure Container Apps to read secrets.
Configure KEYVAULT_URL and SENDER_EMAIL_ADDRESS environment variables on Azure Container Apps, allowing .NET to read the Communication Service connection string and mails.
=> Create Azure Communication and Email Communication Service resources

developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
This pull request changes the way we execute Azure CLI commands for Windows. When in Windows environment, we will need to use Window's command prompt (cmd.exe) to run az commands.
=> Fix the execution of azure cli commands for windows

application/account-management/WebApp/global.d.ts, application/account-management/WebApp/rspack.config.ts, application/account-management/WebApp/shared/rspack/runtime.ts, application/shared-kernel/ApiCore/Middleware/WebAppMiddleware.cs
As part of authentication we want to provide the client with a minimum set of user claims from the claims principal. This pull-request adds the user info as part of the meta data sent to the client on initial load.
=> WebApp Add initial UserInfo

application/account-management/WebApp/lib/auth/AccessDenied.tsx, application/account-management/WebApp/lib/auth/AuthenticationProvider.tsx, application/account-management/WebApp/lib/auth/SignedIn.tsx, application/account-management/WebApp/lib/auth/SignedOut.tsx, application/account-management/WebApp/lib/auth/actions.ts, application/account-management/WebApp/lib/auth/hooks.ts, application/account-management/WebApp/lib/auth/mock.api.ts, application/account-management/WebApp/translations/locale/da-DK.po, application/account-management/WebApp/translations/locale/en-US.po, application/account-management/WebApp/translations/locale/pseudo.po
Add basic actions, hooks and helper components for managing authentication and user info
Helper components
* `SignedIn` - Render contents if user is logged in, and have the right roles (if required)
* `SignedOut` - Render contents if the user is logged out
* `AccessDenied` - Render contets if the user is logged in but is missing role requirements
Form action helpers
* `authenticate` - Will validate input and call endpoints to login user
* `logout`
* `getUserInfo` - Will read the UserInfo for the current user
React hooks:
* `useAuthentication` - Return the full authentication context object
* `useUserInfo` - Will Return the current user info in client context
* `useIsAuthenticated` - Boolean, true if logged in
* `useUserRole` - Return the role of the current user on the tenant
* …
=> Set up basic react auth infrastructure

application/account-management/WebApp/app/register/[registrationId]/error.tsx, application/account-management/WebApp/app/register/[registrationId]/page.tsx, application/account-management/WebApp/app/register/layout.tsx, application/account-management/WebApp/app/register/page.tsx, application/account-management/WebApp/lib/router/router.ts, application/account-management/WebApp/translations/locale/da-DK.po, application/account-management/WebApp/translations/locale/en-US.po, application/account-management/WebApp/translations/locale/pseudo.po, application/account-management/WebApp/ui/Auth/SignUpForm.tsx, application/account-management/WebApp/ui/Auth/SignUpVerifyForm.tsx, application/account-management/WebApp/ui/Auth/actions.ts, application/account-management/WebApp/ui/Auth/otp/Digit.tsx, application/account-management/WebApp/ui/Auth/otp/DigitPattern.tsx, application/account-management/WebApp/ui/Auth/otp/OneTimeCodeInput.tsx, application/account-management/WebApp/ui/Auth/otp/VerificationExpirationError.ts, application/account-management/WebApp/ui/Auth/otp/useExpiration.ts, application/client-foundation/clientFilesystemRouter/lib/pageReactRoutesCode.ts
Add next parts of the authentication flow for registering a user and verifying email.
This pull-request also adds a new One Time Code Input field
=> WebApp add initial sign up and verification flow

application/account-management/WebApp/app/layout.tsx, application/account-management/WebApp/app/not-found.tsx, application/account-management/WebApp/app/page.tsx, application/account-management/WebApp/lib/router/router.ts, application/account-management/WebApp/package.json, application/account-management/WebApp/rspack.config.ts, application/account-management/WebApp/ui/Auth/LoginForm.tsx, application/account-management/WebApp/ui/Auth/SignUpForm.tsx, application/account-management/WebApp/ui/Auth/SignUpVerifyForm.tsx, application/account-management/WebApp/ui/components/Button.tsx, application/account-management/WebApp/ui/components/Link.tsx
Configure React Aria Component "Link" for using the router. Did minor updates to Button and Link component usage. Configured "browserslist" and added as build target.
=> Add link component for routing

application/AppHost/Program.cs, application/Directory.Packages.props, application/account-management/Infrastructure/InfrastructureConfiguration.cs, application/shared-kernel/InfrastructureCore/InfrastructureCoreConfiguration.cs, developer-cli/Commands/BuildCommand.cs, developer-cli/Commands/CodeCleanupCommand.cs, developer-cli/Commands/CodeCoverageCommand.cs, developer-cli/Commands/CodeInspectionsCommand.cs, developer-cli/Commands/ConfigureDeveloperEnvironmentCommand.cs, developer-cli/Commands/RunCommand.cs, developer-cli/Installation/PrerequisitesChecker.cs
Update Aspire to use Preview 4. This required updating DB Context configuration to use the new `EnrichSqlServerDbContext` which separates setting up SQL Server and DB Context (we use the default `.UseSqlServer()`, which does not have DB Context pooling).
The DB Context is now configured with an Execution Strategy optimized for Azure, including retries.
The Developer CLI has been updated to require Aspire Preview 4 and has been updated to ensure all commands check for developer prerequisites.
=> Update to Aspire preview 4 and optimize EF Execution Strategy optimized for Azure SQL

.github/workflows/_deploy-container.yml, .github/workflows/_publish-container.yml, .github/workflows/cloud-infrastructure.yml
This pull request will upgrade all workflows to use azure/login@v2 since it uses an updated version of Node
=> Update all workflows to use azure/login@v2 so that they use Node.js 20

application/account-management/Api/AccountRegistrations/AccountRegistrationsEndpoints.cs, application/account-management/Api/Program.cs, application/account-management/Api/Tenants/TenantEndpoints.cs, application/account-management/Api/Users/UserEndpoints.cs, application/shared-kernel/ApiCore/ApiCoreConfiguration.cs, application/shared-kernel/ApiCore/Aspire/ServiceDefaultsExtensions.cs, application/shared-kernel/ApiCore/Endpoints/HealthEndpoints.cs, application/shared-kernel/ApiCore/Endpoints/IEndpoints.cs, application/shared-kernel/ApiCore/Endpoints/TestEndpoints.cs, application/shared-kernel/ApiCore/Endpoints/TrackEndpoints.cs
This pull request will Map all of the application's endpoints by scanning all of the classes that implement the `IEndpoints` interface.
=> Create a generic method for mapping API endpoints

cloud-infrastructure/cluster/deploy-cluster.sh, cloud-infrastructure/modules/container-app.bicep
Ensure setting up a custom domain functions correctly both on initial deployment, whether the resource group exists, and if a TXT challenge is already created.
=> Fix different errors when setting up custom domain

.gitignore, README.md, developer-cli/Commands/ConfigureDeveloperEnvironmentCommand.cs, developer-cli/Commands/InstallCommand.cs, developer-cli/Commands/UninstallCommand.cs, developer-cli/Installation/Configuration.cs, developer-cli/Installation/PrerequisitesChecker.cs, developer-cli/Program.cs
Update developer CLI to support using Linux and WSL on Windows (Ubuntu). Update README with instructions on how to install prerequisites for Linux and WSL.
=> Add support for development on Linux and Windows WSL

.vscode/settings.json, application/account-management/WebApp/app/_landing/sections/CommunitySection.tsx, application/account-management/WebApp/app/_landing/sections/CtaSection.tsx, application/account-management/WebApp/app/_landing/sections/CtaSection2.tsx, application/account-management/WebApp/app/_landing/sections/CtaSection3.tsx, application/account-management/WebApp/app/_landing/sections/FeatureSection.tsx, application/account-management/WebApp/app/_landing/sections/FeatureSection2.tsx, application/account-management/WebApp/app/_landing/sections/FeatureSection3.tsx, application/account-management/WebApp/app/_landing/sections/FeatureSection4.tsx, application/account-management/WebApp/app/_landing/sections/FooterSection.tsx, application/account-management/WebApp/app/_landing/sections/HeroSection.tsx, application/account-management/WebApp/app/_landing/sections/TechnologySection.tsx, application/account-management/WebApp/app/_landing/sections/TechnologySection2.tsx, application/account-management/WebApp/app/page.tsx, application/account-management/WebApp/main.css, application/account-management/WebApp/rspack.config.ts, application/account-management/WebApp/translations/locale/da-DK.po, application/account-management/WebApp/translations/locale/en-US.po, application/account-management/WebApp/translations/locale/pseudo.po, application/account-management/WebApp/ui/components/Button.tsx, application/account-management/WebApp/ui/components/Link.tsx, application/shared-kernel/ApiCore/Middleware/WebAppMiddlewareConfiguration.cs, application/yarn.lock
Create an initial landing page showcasing the benefits of using PlatformPlatform. This page highlights key advantages such as the all-in-one package, enterprise-grade security, scalability, and the key technologies used, designed to attract potential consumers by demonstrating how PlatformPlatform can enhance their operational efficiency and technology management.
=> Landing page initial version

cloud-infrastructure/cluster/deploy-cluster.sh, cloud-infrastructure/cluster/main-cluster.bicep
Create Azure infrastructure for the new Back Office self-contained system. This includes setting up an Azure Container App for the API and Worker, a Database, Blob Storage, and a Managed Identity. Update the deploy-cluster script to send the current version of the self-contained system.
=> Create Azure infrastructure for Back Office self-contained system

.github/workflows/account-management.yml, .github/workflows/app-gateway.yml
Install all node modules required by the self-contained systems to prepare for multiple self-contained systems. This is necessary when building .NET solutions to ensure all dependencies are available for each system. Also, ensure that NodeJS is always installed.
=> Install NodeJS and node modules for multiple self-contained systems

application/account-management/WebApp/dist/index.html, application/account-management/WebApp/public/index.html
We hardcode the theme mode to light mode until we implement the theme mode switcher.
=> Hardcode theme mode to light mode

.github/workflows/account-management.yml, .github/workflows/app-gateway.yml, .github/workflows/back-office.yml, application/account-management/WebApp/pages/-landing/sections/TechnologySection2.tsx, application/account-management/WebApp/pages/__root.tsx, application/account-management/WebApp/pages/login/_layout.tsx, application/account-management/WebApp/public/index.html, application/account-management/WebApp/shared/lib/applicationInsights/ApplicationInsightsProvider.tsx, application/account-management/WebApp/shared/lib/auth/AuthenticationProvider.tsx, application/account-management/WebApp/shared/lib/router/ReactAriaRouterProvider.tsx, application/account-management/WebApp/shared/ui/DomainInput.tsx, application/account-management/WebApp/shared/ui/LocaleSwitcher.tsx, application/back-office/WebApp/pages/__root.tsx, application/back-office/WebApp/public/index.html, application/back-office/WebApp/shared/lib/applicationInsights/ApplicationInsightsProvider.tsx, application/back-office/WebApp/shared/lib/auth/AuthenticationProvider.tsx, application/back-office/WebApp/shared/lib/router/ReactAriaRouterProvider.tsx
Fix failed publishing of frontend artifacts on the main branch. In the previous implementation, the publishing of frontend artifacts failed when running on the main branch.
Additionally, JetBrains formatting has been applied to all frontend files, ensuring compatibility by retaining only changes that do not conflict with Biome.
=> Fix failed publishing of frontend artifacts

.github/workflows/cloud-infrastructure.yml, cloud-infrastructure/modules/container-app.bicep, cloud-infrastructure/modules/key-vault.bicep
Enhance Bicep modules and GitHub workflows to improve resource creation and ensure proper deployment triggers.
- Update Bicep modules for Azure Container App and KeyVault to return `ContainerAppUrl` and `KeyVaultId` respectively, allowing these values to be used when creating other dependent resources
- Ensure changes to the reusable GitHub workflow `_deploy-infrastructure.yml` trigger the deployment of infrastructure. This ensures that any modifications to this workflow trigger a build
=> Update Bicep modules and ensure infrastructure deployment triggers

.github/workflows/account-management.yml, .github/workflows/back-office.yml
Ensure that changes to `shared-webapp` trigger the GitHub workflows for Account Management and BackO ffice. Previously, these workflows were not triggered when modifications were made to `shared-webapp`.
=> Ensure GitHub workflows trigger on changes to shared-webapp

application/account-management/Application/Users/UserResponseDto.cs, application/account-management/Directory.Build.props, application/account-management/Domain/AccountRegistrations/AccountRegistration.cs, application/account-management/Domain/Users/User.cs, application/account-management/Infrastructure/Migrations/DatabaseMigrations.cs, application/account-management/Infrastructure/Users/UserRepository.cs, application/account-management/Tests/Api/Users/UserEndpointsTests.cs, application/account-management/Tests/DatabaseSeeder.cs, application/back-office/Directory.Build.props, developer-cli/Commands/BuildCommand.cs, developer-cli/Commands/CodeCleanupCommand.cs, developer-cli/Commands/CodeCoverageCommand.cs, developer-cli/Commands/CodeInspectionsCommand.cs, developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs, developer-cli/Commands/DevCommand.cs, developer-cli/Commands/InstallCommand.cs, developer-cli/Commands/TestCommand.cs, developer-cli/Commands/TranslateCommand.cs, developer-cli/Commands/UninstallCommand.cs
Add `User.Title` to the database, including updates to database migrations, DTO, `UserRepository.Search`, and database seeding.
Remove all usages of `[UsedImplicitly]` attributes, which were previously used to avoid warnings in JetBrains. These leftover attributes have been removed from Domain Entities and Developer CLI commands.
IMPORTANT: This change requires the existing database to be updated manually.
=> Add title property to user

application/account-management/WebApp/pages/admin/users/-components/UserHeader.tsx, application/account-management/WebApp/pages/admin/users/-components/UserTable.tsx, application/account-management/WebApp/pages/admin/users/-components/data.tsx, application/shared-webapp/ui/components/ListBox.tsx, application/shared-webapp/ui/components/Menu.tsx, application/shared-webapp/ui/components/SideMenu.tsx
In this pull-request we added more interactives to buttons and menus and changed styling.
=> Added interactives on user-management

application/account-management/WebApp/pages/admin/users/-components/UserHeader.tsx, application/account-management/WebApp/pages/admin/users/-components/UserInvite.tsx, application/account-management/WebApp/pages/admin/users/-components/UserQuerying.tsx, application/account-management/WebApp/pages/admin/users/-components/UserTable.tsx, application/account-management/WebApp/pages/admin/users/-components/UserTabs.tsx, application/account-management/WebApp/pages/admin/users/-components/data.tsx, application/account-management/WebApp/pages/admin/users/-components/profileMenuItem.tsx, application/account-management/WebApp/pages/admin/users/index.tsx
Update User Management page to align with the design specifications.
- Move profile menu item to a new separate `profileMenuItem` component
- Set height on menu items to match design, and set width for smooth open menu animation
- Switch Profile menu from icon to Avatar image to match design
- Format user action menu with consistent height and red text for delete item to match design
- Only show delete icon when hovering over user row
- Ensure rounded corners of search textbox align with other elements and match design
- Add minimal padding between main content and side menu to prevent selected borders from being cropped
- Disable sorting on Date, Last seen, and Role
- Ensure the background on the user management page covers the full height of the screen
- Ensure the header and pagination …
=> Update User Management styling to align with design

application/Directory.Packages.props, application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json, application/back-office/WebApp/shared/lib/api/BackOffice.Api.json, developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs, developer-cli/Commands/TranslateCommand.cs, developer-cli/DeveloperCli.csproj, developer-cli/Installation/PrerequisitesChecker.cs
Upgrade all NuGet packages in PlatformPlatform to the latest version. 
Bump Developer CLI prerequisite checks for .NET, Aspire, Azure CLI, GitHub CLI, Node, and Docker to the latest versions.
=> Upgrade dependencies and bump CLI prerequisite checks

application/account-management/Api/AccountManagement.Api.csproj, application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json, application/back-office/Api/BackOffice.Api.csproj, application/shared-kernel/SharedKernel/ApiDependencyConfiguration.cs, application/shared-kernel/SharedKernel/SchemaProcessor/StronglyTypedDocumentProcessor.cs, application/shared-kernel/SharedKernel/SharedKernel.csproj, application/shared-webapp/ui/components/Accordion.tsx, application/shared-webapp/ui/components/Button.tsx, application/shared-webapp/ui/components/InlineAlert.tsx, application/shared-webapp/ui/components/Input.tsx, application/shared-webapp/ui/components/Menu.tsx, application/shared-webapp/ui/components/SideMenu.tsx, application/shared-webapp/ui/components/Toast.tsx, application/shared-webapp/ui/theme/mode/ThemeMode.tsx
Move Microsoft.Extensions.ApiDescription.Server back to API.csproj files to trigger OpenAPI.json generation.
=> Fix disabled API.json generation

developer-cli/Commands/DevCommand.cs
Dev command does not start Docker on Windows platform. This Pull Request addresses the issue.
Starting Docker takes a few second before it can accept commands. A check is added that ensures Docker is responsive to commands before proceeding to the next steps.
=> Fix starting Docker on Windows when not running

developer-cli/Commands/CodeCoverageCommand.cs, developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs, developer-cli/Commands/TranslateCommand.cs, developer-cli/DeveloperCli.csproj, developer-cli/Installation/ChangeDetection.cs, developer-cli/Installation/Prerequisite.cs, developer-cli/Utilities/GithubHelper.cs, developer-cli/Utilities/SolutionHelper.cs, developer-cli/dotnet-tools.json
Upgrade the Developer CLI to target .NET 9, aligning with the broader project update.
The Docker prerequisite has been removed from the `translate` CLI command, simplifying its usage.
Additionally, spelling errors and SonarLint warnings in the Developer CLI have been fixed, and a code cleanup has been performed to improve maintainability.
=> Upgrade Developer CLI to .NET 9

.cursorrules, .github/copilot-instructions.md, .gitignore, application/.cursorrules
Add rules files to guide AI editors in maintaining consistency with PlatformPlatform’s coding conventions. Custom instructions for GitHub Copilot have been added, and a `.cursorrules` file for the Cursor AI Editor has been created, linking explicitly to `.github/copilot-instructions.md` for shared rules.
Additionally, the `.gitignore` file has been updated to exclude Windsurf rules files, allowing local use without committing them to the repository.
=> Add rules for AI editors to ensure consistency with project guidelines

.github/workflows/check-git-history.yml, .github/workflows/validate-pull-request-conventions.yml
Introduce a GitHub Action to validate Git history and enforce branch naming, commit message formatting, and rebase requirements. This ensures that all contributions adhere to the established conventions for clean and consistent Git history.
The action performs the following checks:
- **Branch naming convention**: Verifies that branch names follow the format `this-is-my-branch-name`, containing only lowercase letters, numbers, and hyphens.
- **No merge commits**: Ensures no merge commits exist in the branch by requiring a rebase onto `main`.
- **Branch is up-to-date**: Confirms the branch is rebased to the latest `main`.
- **Commit message format**:
- Messages must be single-line.
- The first character of the commit message must be uppercase.
- Commit messages cannot end with a period …
=> Add GitHub Action to enforce Git conventions

.github/copilot-instructions.md
Enhance the GitHub and Cursor rules files to make them more specific to PlatformPlatform's conventions. This update includes detailed examples and explanations of key concepts such as the usage of CQRS, Strongly Typed IDs, and other important architectural patterns. The added specificity ensures better adherence to PlatformPlatform's development standards and provides clearer guidance for contributors.
The file is now just above 6 KB, which is the maximum for the Windsurf AI editor, while Cursor AI seems to allow for larger rule files.
=> Update AI Editor rules files with detailed PlatformPlatform conventions 

developer-cli/Commands/TranslateCommand.cs
Add cost visibility for large translation jobs to help track usage and expenses. The system now calculates and reports translation cost using:
- Reported input token count
- Cached input and output token usage
- Price estimates based on values published by OpenAI
This provides transparency for cases where many translation keys are processed, which may incur significant cost.
=> Show token usage and translation cost of translate CLI command

.ai-rules/README.md, .ai-rules/backend/README.md, .ai-rules/backend/api-endpoints.md, .ai-rules/frontend/README.md, .ai-rules/other/pull-request.md, README.md, application/AppGateway/Filters/ClusterDestinationConfigFilter.cs, application/AppGateway/Middleware/AuthenticationCookieMiddleware.cs, application/account-management/Core/Features/Authentication/Commands/CompleteLogin.cs, application/account-management/Core/Features/Authentication/Commands/RefreshAuthenticationTokens.cs, application/account-management/Core/Features/EmailConfirmations/Commands/CompleteEmailConfirmation.cs, application/account-management/Core/Features/EmailConfirmations/Commands/ResendEmailConfirmationCode.cs, application/account-management/Core/Features/EmailConfirmations/Domain/EmailConfirmation.cs, application/account-management/Core/Features/Tenants/EventHandlers/TenantCreatedEventHandler.cs, application/account-management/Tests/Signups/CompleteSignupTests.cs, application/account-management/WebApp/bootstrap.tsx, application/account-management/WebApp/routes/login/-shared/loginState.ts, application/account-management/WebApp/routes/signup/-shared/signupState.ts, application/account-management/WebApp/shared/translations/locale/da-DK.po, application/account-management/WebApp/shared/translations/locale/en-US.po, application/account-management/WebApp/shared/translations/locale/nl-NL.po, application/back-office/WebApp/bootstrap.tsx, application/shared-webapp/infrastructure/auth/hooks.ts, application/shared-webapp/infrastructure/translations/TranslationContext.tsx, application/shared-webapp/ui/components/DndGridList.tsx, application/shared-webapp/ui/components/Pagination.tsx
New AI rules
- Add new AI rules for writing pull request titles and descriptions  
AI assistants like Cursor and Windsurf automatically inspect all git commits and perform a git diff against main to understand the changes introduced. If needed, the AI assistants will look at additional files to gather context.
- Update backend and frontend rules with clear conventions for adding punctuation to exceptions, errors, and log messages
- Update the "Inside our mono repository" section in both the global README.md and the main README.md for AI assistants
Finally update badges in the main README.md to include Cloud Infrastructure and Back Office, and remove a few Sonar Cloud badges.
Maintainers of downstream projects should update their code to follow the new message punctuation guidelines:
1. …
=> Add AI rules for pull requests and update message punctuation guidelines

developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
Fix issues with the `configure-continuous-deployments` CLI command:
- Fix bug with Azure CLI commands on Windows by properly handling command execution through `cmd.exe`
- Add error handling for GitHub environment creation when repository lacks environment feature due to subscription type
- Fix Azure query filtering when AppRegistration ID is empty
- Add proper error handling when user is not logged in to GitHub CLI
=> Fix configure-continuous-deployments CLI command issues

.github/workflows/account-management.yml, .github/workflows/app-gateway.yml, .github/workflows/back-office.yml
Update GitHub Actions workflows to use the new developer CLI command names:
- Replace `code-inspections` with `inspect --backend` command and replace the `-s` with `--solution-name`
- Replace `code-cleanup` with `format --backend` command and replace the `-s` with `--solution-name`
These changes align the workflow files with the recent developer CLI command renaming, ensuring CI/CD pipelines continue to function correctly.
Please update the GitHub Actions for your self-contained system to use the new CLI commands:
1. Update the GitHub actions workflow for your self-contained system
In your workflow files under `.github/workflows/your-self-contained-system.yml`, replace:
```diff
- dotnet run code-inspections -s YourSolutionFile.slnf
+ dotnet run inspect --backend --solution-name …
```
=> Update GitHub Actions workflows to use the new developer CLI command names

application/account-management/WebApp/routes/admin/index.tsx, application/account-management/WebApp/routes/admin/users/-components/UserTable.tsx, application/account-management/WebApp/shared/components/AvatarButton.tsx, application/account-management/WebApp/shared/components/SharedSideMenu.tsx, application/account-management/WebApp/shared/lib/api/client.ts, application/shared-webapp/utils/date/formatDate.ts, application/shared-webapp/utils/string/getInitials.ts
Add common React hooks for frontend applications and optimize mutation behavior:
- Add meta option to skip query invalidation during mutations, preventing unnecessary API calls e.g. during logout
- Extract formatting utility functions from UserTable to SharedWebApp
- Remove forced page reload on Account menu option to improve navigation experience
=> Add frontend optimizations including  query invalidation control and new React hooks

application/shared-webapp/ui/components/Avatar.tsx, application/shared-webapp/ui/components/Checkbox.tsx, application/shared-webapp/ui/components/ComboBox.tsx, application/shared-webapp/ui/components/DatePicker.tsx, application/shared-webapp/ui/components/DateRangePicker.tsx, application/shared-webapp/ui/components/Digit.tsx, application/shared-webapp/ui/components/Input.tsx, application/shared-webapp/ui/components/Link.tsx, application/shared-webapp/ui/components/NumberField.tsx, application/shared-webapp/ui/components/RadioGroup.tsx
Fix various UI component alignment and visual issues to improve user experience and ensure proper display across different scenarios.
- Fix alignment of controls inside ComboBox and NumberField to ensure consistent spacing.
- Fix avatar image sizing to prevent large display and blinking on slow connections by showing initials placeholder until image loads.
- Use Canadian locale for date pickers to display ISO 8601 format (YYYY-MM-DD), avoiding ambiguity between US (MM/DD/YYYY) and EU (DD/MM/YYYY) formats.
- Fix OneTimeCodeInput focus indicator visibility on mouse click.
- Fix color in NumberField when maximum or minimum is reached to ensure visibility.
- Ensure links display cursor pointer on hover.
- Remove bold font weight from DateRangePicker placeholder text.
- Ensure all components …
=> Fix UI component alignment and visual issues
