platformplatform/PlatformPlatform

- .github/workflows/account-management.yml
- .gitignore
Generate unique version numbers in the format YYYY.M.D.REV, where REV represents the count of GitHub Action runs. Apply this version number to both the .NET AssemblyVersion and AssemblyFileVersion.
> Create unique .NET build version number as YYYY.M.D.REV

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Add badges to the README file, incorporating GitHub Action build status, GitHub issue counts for bugs, enhancements, and roadmap items. Additionally, include code quality badges from SonarCloud, such as Code Coverage, Quality Gate, Security, Reliability, and Maintainability status, etc., with deep links to their respective pages.
> Add status badges to readme

- .github/CODEOWNERS
Create a new GitHub CODEOWNERS file to enforce appropriate team approvals before merging. This pull request assumes the existence of a "Site Reliability Team" and an "Account Team" within the GitHub organization. By default, the Site Reliability Team owns all new folders, with explicit ownership of the .github and cloud-infrastructure folders. The Account Team owns the /account-management/ folder.
> Add GitHub CODEOWNERS file to mandate appropriate team approval

- account-management/src/Application/Application.csproj
- account-management/src/Application/ApplicationConfiguration.cs
- account-management/src/Application/Tenants/Commands/CreateTenant/CreateTenantCommand.cs
- account-management/src/Application/Tenants/Queries/GetTenantByIdQuery.cs
- account-management/tests/Tests/Application/Tenants/Commands/CreateTenant/CreateTenantCommandHandlerTests.cs
- account-management/tests/Tests/Application/Tenants/Queries/GetTenantByIdQueryTests.cs
Introduce [Mapster](https://www.nuget.org/packages/Mapster/) as a mapping framework. Mapster offers automatic mapping between entities and DTOs with minimal configuration for basic mapping, while still allowing customized mapping when necessary. This eliminates the need for manual mapping, so the TenantDto.CreateFrom(tenant) method and its calls are removed.
> Add mapster for mapping dto objects

- account-management/src/Application/Tenants/Dtos/TenantDto.cs
Remove the unused TenantDto.CreateFrom(tenant) method after introducing Mapster as the mapping framework.
> Delete TenantDto.CreateFrom(tenant) method

- .github/workflows/account-management.yml
- account-management/src/Application/Application.csproj
- account-management/src/Application/ApplicationConfiguration.cs
- account-management/src/Application/Shared/DomainEvents/PublishDomainEventsPipelineBehavior.cs
- account-management/src/Application/Shared/Persistence/UnitOfWorkPipelineBehavior.cs
- account-management/src/Application/Tenants/Commands/CreateTenant/TenantCreatedEventHandler.cs
- account-management/src/Domain/Domain.csproj
- account-management/src/Domain/Shared/AggregateRoot.cs
- account-management/src/Domain/Shared/IDomainEvent.cs
- account-management/src/Domain/Shared/IUnitOfWork.cs
- account-management/src/Domain/Tenants/Tenant.cs
- account-management/src/Domain/Tenants/TenantCreatedEvent.cs
- account-management/src/Infrastructure/Shared/UnitOfWork.cs
- account-management/tests/Tests/Application/Shared/DomainEvents/PublishDomainEventsPipelineBehaviorTests.cs
- account-management/tests/Tests/Application/Shared/Persistence/UnitOfWorkPipelineBehaviorTests.cs
- account-management/tests/Tests/Application/Tenants/Commands/CreateTenant/CreateTenantCommandHandlerTests.cs
- account-management/tests/Tests/Domain/Shared/DomainEventTests.cs
Implement DomainEvents on Aggregate Roots. Ensure these events are dispatched (by the PublishDomainEventsPipelineBehavior) and handled before the UnitOfWork is committed (within the UnitOfWorkPipelineBehavior).
Introduce a new AggregateRoot class, in addition to the existing IAggregateRoot, that holds domain events.
Implement a new TenantCreateEvent, leveraging the new DomainEvent foundation.
> Set up Domain events using MediatR

- account-management/src/Application/Tenants/Commands/CreateTenant/CreateTenantCommand.cs
- account-management/src/Application/Tenants/Commands/DeleteTenant/DeleteTenantCommand.cs
- account-management/src/Application/Tenants/Commands/UpdateTenant/UpdateTenantCommand.cs
- account-management/src/Domain/Tenants/Tenant.cs
- account-management/src/Foundation/Application/CommandResult.cs
- account-management/src/Foundation/Foundation.csproj
- account-management/src/Foundation/WebApi/CommandResultExtensions.cs
- account-management/src/WebApi/Endpoints/TenantEndpoints.cs
- account-management/tests/Tests/Application/Tenants/Commands/CreateTenant/CreateTenantCommandHandlerTests.cs
- account-management/tests/Tests/Application/Tenants/Commands/DeleteTenant/DeleteTenantCommandHandlerTests.cs
- account-management/tests/Tests/Application/Tenants/Commands/UpdateTenant/UpdateTenantCommandHandlerTests.cs
- account-management/tests/Tests/Application/Tenants/Queries/GetTenantByIdQueryTests.cs
- account-management/tests/Tests/DatabaseSeeder.cs
- account-management/tests/Tests/Infrastructure/Tenants/TenantRepositoryTests.cs
- account-management/tests/Tests/WebApi/Endpoints/TenantEndpointsTests.cs
This pull request implements Update and Delete tenant endpoints to the WebAPI. These endpoints come with new commands, namely UpdateTenantCommand and DeleteTenantCommand, along with relevant tests.
The CommandResult has been extended to allow for a null value upon success (for the Delete scenario). Additionally, HttpStatusCode has been added to the CommandResult to allow for different HttpResults (NotFound, BadRequest, etc). An extension method has been implemented within the Foundation, which can convert a CommandResult<T> to an HttpResponseMessage. This reduces boilerplate code in the endpoints which now often can be one or two lines.
> Add update and delete tenant endpoints

- account-management/Application/ApplicationConfiguration.cs
- account-management/Infrastructure/InfrastructureConfiguration.cs
- account-management/WebApi/Endpoints/TenantEndpoints.cs
- account-management/WebApi/Program.cs
- account-management/WebApi/WebApi.csproj
- account-management/WebApi/WebApiConfiguration.cs
- backend-foundation/AspNetCoreUtils/AspNetCoreUtils.csproj
- backend-foundation/AspNetCoreUtils/AspNetCoreUtilsConfiguration.cs
- backend-foundation/AspNetCoreUtils/Endpoints/TestEndpoints.cs
- backend-foundation/AspNetCoreUtils/Extensions/CommandResultExtensions.cs
- backend-foundation/AspNetCoreUtils/Middleware/GlobalExceptionHandlerMiddleware.cs
- backend-foundation/DomainModeling/DomainModelingConfiguration.cs
- backend-foundation/InfrastructureCore/InfrastructureCoreConfiguration.cs
Move common service registration, app configuration, and test endpoints from the Account Management to the Backend Foundation. This promotes operational consistency across different self-contained systems.
Create a new Middleware and Extensions namespace in AspNetCoreUtils for better organization and separation of concerns.
> Extract reusable backend foundation

- account-management/Application/ApplicationConfiguration.cs
- account-management/Application/Tenants/Commands/CreateTenantCommand.cs
- account-management/Application/Tenants/Commands/DeleteTenantCommand.cs
- account-management/Application/Tenants/Commands/UpdateTenantCommand.cs
- account-management/Application/Tenants/Dtos/TenantDto.cs
- account-management/Application/Tenants/EventHandlers/TenantCreatedEventHandler.cs
- account-management/Application/Tenants/Queries/GetTenantQuery.cs
- account-management/Infrastructure/ApplicationDbContext.cs
- account-management/Tests/Application/Tenants/Commands/CreateTenantCommandTests.cs
- account-management/Tests/Application/Tenants/Commands/DeleteTenantCommandTests.cs
- account-management/Tests/Application/Tenants/Commands/UpdateTenantCommandTests.cs
- account-management/Tests/Application/Tenants/Queries/GetTenantQueryTests.cs
- account-management/Tests/DatabaseSeeder.cs
- account-management/Tests/WebApi/Endpoints/TenantEndpointsTests.cs
- account-management/WebApi/Endpoints/TenantEndpoints.cs
- account-management/WebApi/Program.cs
- account-management/WebApi/Tenants/CreateTenantRequest.cs
- account-management/WebApi/Tenants/TenantEndpoints.cs
- account-management/WebApi/Tenants/TenantResponseDto.cs
- account-management/WebApi/Tenants/UpdateTenantRequest.cs
- account-management/WebApi/WebApiConfiguration.cs
- backend-foundation/AspNetCoreUtils/AspNetCoreUtils.csproj
- backend-foundation/AspNetCoreUtils/Extensions/CommandResultExtensions.cs
- backend-foundation/DomainModeling/DomainModelingConfiguration.cs
Relocate TenantDTO to WebApi and modify commands and queries to return domain entities. Enhance CommandResultExtensions to accept domain entity and DTO as generic parameters, streamlining and standardizing the minimal API endpoints.
Flatten the commands and queries namespace in the Application Layer for better organization. Update tests accordingly.
> Move TenantDTO and flattern command and queries namespace

- account-management/Application/Tenants/Commands/DeleteTenantCommand.cs
- account-management/Application/Tenants/Commands/UpdateTenantCommand.cs
- account-management/Tests/WebApi/Endpoints/TenantEndpointsTests.cs
- backend-foundation/AspNetCoreUtils/Extensions/CommandResultExtensions.cs
- backend-foundation/DomainModeling/Cqrs/CommandResult.cs
- backend-foundation/DomainModeling/Cqrs/QueryResult.cs
- backend-foundation/DomainModeling/Validation/AttributeError.cs
- backend-foundation/DomainModeling/Validation/ErrorMessage.cs
- backend-foundation/DomainModeling/Validation/ValidationResult.cs
Modify 'NotFound' command endpoints to return an error message, similar to Query endpoints for consistent error handling.
Rename PropertyError to AttributeError and QueryError to ErrorMessage for clearer identification and understanding of the error types.
> Optimize http response error messages

- account-management/Api/Api.csproj
- account-management/Api/ApiConfiguration.cs
- account-management/Api/Program.cs
- account-management/Api/Tenants/TenantContractsV1.cs
- account-management/Api/Users/UserContractsV1.cs
- account-management/Application/Tenants/CreateTenant.cs
- account-management/Application/Tenants/DeleteTenant.cs
- account-management/Application/Users/CreateUser.cs
- account-management/Domain/Users/IUserRepository.cs
- account-management/Domain/Users/User.cs
- account-management/Infrastructure/AccountManagementDbContext.cs
- account-management/Infrastructure/Migrations/20230529195123_Add_Users.Designer.cs
- account-management/Infrastructure/Migrations/20230529195123_Add_Users.cs
- account-management/Infrastructure/Migrations/AccountManagementDbContextModelSnapshot.cs
- account-management/Infrastructure/Users/UserRepository.cs
- account-management/Tests/Api/Tenants/TenantEndpointsTests.cs
- account-management/Tests/Api/Users/UserEndpointsTests.cs
- account-management/Tests/DatabaseSeeder.cs
- account-management/Tests/Tests.csproj
- shared-kernel/ApplicationCore/Behaviors/UnitOfWorkPipelineBehaviorConcurrentCounter.cs
- shared-kernel/ApplicationCore/Behaviors/ValidationPipelineBehavior.cs
- shared-kernel/ApplicationCore/Cqrs/Result.cs
- shared-kernel/DomainCore/Persistence/IRepository.cs
- shared-kernel/InfrastructureCore/EntityFramework/ModelBuilderExtensions.cs
- shared-kernel/InfrastructureCore/InfrastructureCore.csproj
- shared-kernel/InfrastructureCore/Persistence/RepositoryBase.cs
- shared-kernel/Tests/Tests.csproj
Add a new property called TenantId to the User entity to ensure that each user is associated with a specific Tenant. Create a database migration that establishes a foreign key relationship between Users.TenantId and Tenants.Id. Update the CreateUser command to require the existence of the specified Tenant. To support this functionality, implement a new generic ExistsAsync method in the RepositoryBase class, which includes entities added to the DbContext but not yet committed to the Database (like when Creating a Tenant and TenantOwner user in the same transaction). Furthermore, implement logic to provide meaningful error messages when attempting to delete a Tenant that has associated users. To enable this, add a new method called CountTenantUsersAsync in the UserRepository class, and …
> Change User to be associated with a Tenant and block deletion of tenants with users

- account-management/Api/Tenants/TenantEndpoints.cs
- account-management/Api/Users/UserEndpoints.cs
- shared-kernel/ApiCore/ApiResults/ApiResult.cs
- shared-kernel/ApiCore/ApiResults/ApiResultExtensions.cs
- shared-kernel/ApiCore/HttpResults/ApiResultExtensions.cs
Update the create endpoints to return ApiResult instead of ApiResult<TenantId> since the Id is already returned as part of the location header and not in the response body.
Refactor the Tenant and UserEndpointsTest to further enhance their consistency.
> Update create endpoints to return ApiResult instead of ApiResult<TenantId>

- account-management/Api/Api.csproj
- account-management/Domain/Domain.csproj
- account-management/Domain/Users/UserTypes.cs
- account-management/Infrastructure/AccountManagementDbContext.cs
- account-management/Infrastructure/Migrations/20230618152042_Initial.Designer.cs
- account-management/Infrastructure/Migrations/20230618152042_Initial.cs
- account-management/Infrastructure/Migrations/AccountManagementDbContextModelSnapshot.cs
- account-management/Tests/Api/Users/UserEndpointsTests.cs
- account-management/Tests/DatabaseSeeder.cs
- account-management/Tests/FakerExtensions.cs
- shared-kernel/ApiCore/ApiCore.csproj
- shared-kernel/DomainCore/DomainCore.csproj
- shared-kernel/DomainCore/Identity/StronglyTypedLongId.cs
- shared-kernel/DomainCore/Identity/StronglyTypedUlid.cs
- shared-kernel/InfrastructureCore/EntityFramework/ModelBuilderExtensions.cs
Add the NUlid NuGet package to the shared kernel to enable the use of [Ulid-based IDs](https://github.com/ulid/spec/). This allows for globally unique IDs that are roughly sorted, eliminating the need for sorting when querying and enabling better page splitting in SQL Server.
Create a generic strongly typed ID base class that utilizes Ulid. Update the UserId strongly typed ID to use this new class instead of Snowflake IDs.
Reset the database schema by changing UserId from a bigint to CHAR(26) column type to accommodate the Ulid-based IDs. Create the MapStronglyTypedUuid mapper to allow Entity Framework to read and write Ulid values.
Ensure that the Microsoft.EntityFrameworkCore.Design NuGet package is added to the AccountManagement.Api project, as it is required by the EF Database …
> Add NUlid NuGet package and Implement generic strongly typed ID base class using Ulid

- account-management/Api/Api.csproj
- account-management/Tests/Tests.csproj
- shared-kernel/DomainCore/DomainCore.csproj
- shared-kernel/InfrastructureCore/InfrastructureCore.csproj
- shared-kernel/Tests/Tests.csproj
Update all NuGet packages to the latest version to incorporate the latest improvements and bug fixes:
- Upgrade EntityFrameworkCore NuGet packages from 7.0.5 to 7.0.7
- Upgrade AspNetCore.Mvc.Testing NuGet packages from 7.0.5 to 7.0.7
- Upgrade Microsoft.Extensions.Logging NuGet packages from 7.0.0 to 7.0.1
- Upgrade Microsoft.NET.Test.Sdk NuGet packages from 17.6.1 to 17.6.2
-
> Upgrade NuGet packages

- account-management/Api/Tenants/TenantEndpoints.cs
- account-management/Api/Users/UserEndpoints.cs
- account-management/Domain/Tenants/TenantTypes.cs
- account-management/Domain/Users/UserTypes.cs
- account-management/Tests/Api/Tenants/TenantEndpointsTests.cs
- account-management/Tests/Api/Users/UserEndpointsTests.cs
- shared-kernel/ApiCore/AspNetCoreUtilsConfiguration.cs
- shared-kernel/ApiCore/Filters/XEnumNamesSchemaFilter.cs
Modify the default Json serialization of REST endpoints to use enums as strings instead of their integer values. This change enhances the clarity when working with the API. Also, update the Swagger configuration to accurately display the correct contract, reflecting the usage of enum strings.
Refactor all REST endpoints to use online expression-bodied methods instead of dedicated endpoint methods. This approach simplifies the code and improves maintainability by reducing redundancy and promoting a more concise coding style.
> Update REST endpoints to use enums as strings and utilize expression-bodied methods

- .github/workflows/azure-infrastructure-change-preview.yml
- .github/workflows/azure-infrastructure-deployment.yml
- cloud-infrastructure/cluster/config/production-west-europe.sh
Disable the Azure SQL Server elastic pool on the Production West Europe cluster.
Enable manual triggering of the azure-infrastructure-change-preview.yml and azure-infrastructure-deployment.yml GitHub workflows.
> Disable Azure SQL Server elastic pool and allow manual triggering of infrastructure workflows

- .github/workflows/azure-infrastructure.yml
Correct the missing .result in YAML workflow job conditions. The condition `needs.production-environment-deploy` should now be `needs.production-environment-deploy.result`.
Enhance the stability of multi-statement bash scripts within YAML workflows. This change ensures that subsequent statements are not executed if a preceding statement fails.
> Correct syntax error in workflow

- .github/workflows/azure-infrastructure.yml
- cloud-infrastructure/cluster/deploy-cluster.sh
- cloud-infrastructure/cluster/firewall.sh
- cloud-infrastructure/cluster/grant-database-permissions.sh
Modify the GitHub Workflow to grant database permissions in a separate step. Unfortunately a manual step is required to grant SQL Server access to read the Managed Identity from Active Directory. Currently, there it seems there is no way to automate this action. For more details, refer to this [Stack Overflow question](https://stackoverflow.com/q/76995900/8547).
Install the new version of SQLCMD, specifically the [go-sqlcmd](https://learn.microsoft.com/en-us/sql/tools/sqlcmd/go-sqlcmd-utility) utility. This version adds support for the -authentication-method=ActiveDirectoryDefault option, facilitating the use of GitHub service principals for Azure access.
Ensure the firewall is closed, even if the script execution fails, to maintain security.
Alter the GitHub workflow jobs to execute all …
> Separate step for Database Permissions and changes in GitHub workflow and tooling

- cloud-infrastructure/modules/key-vault.bicep
- cloud-infrastructure/modules/service-bus.bicep
Azure Key Vault and Service Bus no longer offer the option to configure the duration for retaining audit logs. Consequently, this pull request removes the settings for audit log retention periods.
> Remove audit log retention configuration for Azure services

- .github/workflows/azure-infrastructure.yml
- cloud-infrastructure/cluster/deploy-cluster.sh
- cloud-infrastructure/cluster/grant-database-permissions.sh
- cloud-infrastructure/cluster/main-cluster.bicep
- cloud-infrastructure/deploy.sh
Grant access to databases for managed identities by directly providing the internal Azure AD security identifier (SID). Instead of relying on the standard SQL command `CREATE USER [$MANAGED_IDENTITY] FROM EXTERNAL PROVIDER`, which necessitates the SQL Server to have permissions to read the Active Directory, this pull request employs a more direct approach using `CREATE USER [$MANAGED_IDENTITY] WITH SID = $SID, TYPE = E`. This effectively bypasses the need for the SQL Server to have Active Directory permissions.
The SID is obtained by fetching the Client ID of the Managed Identity from the Bicep output and converting converting it to its binary form.
> Grant managed identity permissions to database using security identifier (SID) 

- cloud-infrastructure/initialize-azure.sh
Introduce federated credentials for shared, staging, and production environments. For Azure authentications in GitHub Actions with an environment constraint, the federated credentials are now explicitly constrained to that specific environment. The same Service Principal from the Main branch is utilized.
> Add federated credentials for shared, staging, and production environments

- cloud-infrastructure/modules/microsoft-sql-database.bicep
Add required GeneralPurpose and Capacity SKU properties to the SQL Database Bicep configuration. Despite their recurrent appearance as deleted items in every Bicep what-if execution, these properties remain essential.
> Add required SKU properties to SQL database Bicep configuration

- .github/workflows/platformplatform-build-and-test.yml
- README.md
- application/account-management/Api/Dockerfile
- application/account-management/Api/Properties/launchSettings.json
- application/account-management/Api/appsettings.development.json
- application/docker-compose.yml
- application/shared-kernel/InfrastructureCore/InfrastructureCoreConfiguration.cs
Introduce Docker Compose to simplify the local setup of PlatformPlatform, including the initialization of SQL Server and the Account Management API. Store the SQL password in an environment variable, facilitating the seamless setup and configuration of SQL Server and the connection string, whether running the API in Docker or debugging via Rider or Visual Studio.
Transform the Account Management API's Dockerfile into a multi-stage build, streamlining the build process and including only the necessary binaries and runtime for production deployment.
Revise the GetConnectionString method to dynamically construct the SQL Server connection string based on the running environment (Azure, Docker, or debugging). Cache the connection string at startup.
Update the README to guide users in setting …
> Introduce Docker Compose for local setup to run SQL Server and Account Management API

- .github/workflows/_deploy-container.yml
- .github/workflows/_publish-container.yml
- .github/workflows/application.yml
- application/account-management/Api/Dockerfile
Implement guards in both `application.yml` and `_publish-container.yml` to ensure container images are pushed exclusively from the main branch.
Remove the redundant success check for the staging job in production deployment, streamlining the workflow.
Simplify the creation of a non-root user in the Dockerfile by omitting the creation of a nonroot group.
> Restrict container image pushes to main branch and streamline deployment workflows

- .github/workflows/_deploy-container.yml
- .github/workflows/_publish-container.yml
- .github/workflows/cloud-infrastructure.yml
- cloud-infrastructure/cluster/deploy-cluster.sh
- cloud-infrastructure/cluster/main-cluster.bicep
- cloud-infrastructure/deploy.sh
- cloud-infrastructure/environment/deploy-environment.sh
- cloud-infrastructure/initialize-azure.sh
- cloud-infrastructure/modules/container-app.bicep
- cloud-infrastructure/modules/container-apps-environment.bicep
- cloud-infrastructure/modules/managed-certificate.bicep
- cloud-infrastructure/shared/deploy-shared.sh
Introduce Bicep code to automate the configuration of a Custom Domain and the automatic creation of a valid SSL Certificate for the `account-management-api`. This process unfolds in three distinct steps:
1. Deploy the container apps environment to retrieve the auto-generated environment URL and the Custom Domain Verification Id.
2. Deploy the container app again to set up the Domain and SSL Certificate, albeit without binding them (as this is not supported in one step; see https://github.com/microsoft/azure-container-apps/tree/main/docs/templates/bicep/managedCertificates).
3. Proceed to bind the SSL certificate to the domain.
The first step will fail when initially setting up custom domains. Bash scripts have been crafted to extract the container app url and Domain Verification ID, …
> Add infrastructure automation to configure custom domain and SSL certificates

- .github/workflows/cloud-infrastructure.yml
Update the cloud infrastructure workflow to pass the `DOMAIN_NAME` environment variable to the Bash scripts, enabling them to configure custom domains.
> Update cloud infrastructure workflow to set the DOMAIN_NAME environment variable

- .github/workflows/cloud-infrastructure.yml
Fix incorrect reference to the environment variable `DOMAIN_NAME`. It was previously referenced as `env.DOMAIN_NAME.DOMAIN_NAME`, but it should naturally be `env.DOMAIN_NAME`.
> Correct duplicate reference of environment variable env.DOMAIN_NAME.DOMAIN_NAME

- .github/workflows/cloud-infrastructure.yml
- cloud-infrastructure/initialize-azure.sh
Streamline the deployment process by merging the Plan jobs for Shared, Staging, and Production into a singular Plan job. In a similar fashion, unify the jobs for Shared Environment Resources and Cluster deployment into one consolidated job per environment. This refinement reduces the deployment steps to a Plan, Shared, Staging, and Production jobs.
This reorganization not only eliminates redundant tasks such as code checkout, Azure login, and Bicep installation but also introduces a trade-off by potentially making the multi-cluster deployment process less transparent.
Furthermore, transition the DOMAIN_NAME environment variable to utilize DOMAIN_NAME_STAGING and DOMAIN_NAME_PRODUCTION. This adaptation allows for the effective reuse of these variables in the Plan job, circumventing its …
> Consolidate infrastructure deployment jobs for streamlined process and quicker execution

- cloud-infrastructure/cluster/config/development-west-europe.sh
- cloud-infrastructure/cluster/config/production-west-europe.sh
- cloud-infrastructure/cluster/config/staging-west-europe.sh
- cloud-infrastructure/deploy.sh
- cloud-infrastructure/environment/config/development.sh
- cloud-infrastructure/environment/config/production.sh
- cloud-infrastructure/environment/config/staging.sh
- cloud-infrastructure/shared/config/shared-development.sh
- cloud-infrastructure/shared/config/shared.sh
Address error handling in infrastructure Bash deployment scripts to correct the issue where the output of Bicep commands piped to `tee /dev/tty` fails in non-interactive environments. Modify the piping to `2>&1` to capture both `stdout` and `stderr` reliably across different contexts.
Introduce `#!/bin/bash` shebang to all infrastructure scripts to standardize execution behavior and formatting, aligning the local terminal experience with that of GitHub Actions.
> Improve Bash Deployment Scripts for Robust Error Handling

- cloud-infrastructure/cluster/deploy-cluster.sh
- cloud-infrastructure/cluster/main-cluster.bicep
- cloud-infrastructure/deploy.sh
- cloud-infrastructure/environment/main-environment.bicep
- cloud-infrastructure/modules/container-app.bicep
- cloud-infrastructure/modules/container-apps-environment.bicep
- cloud-infrastructure/modules/container-registry-permission.bicep
- cloud-infrastructure/modules/container-registry.bicep
- cloud-infrastructure/modules/key-vault.bicep
- cloud-infrastructure/modules/managed-certificate.bicep
- cloud-infrastructure/modules/microsoft-sql-database.bicep
- cloud-infrastructure/modules/microsoft-sql-server-diagnostic.bicep
- cloud-infrastructure/modules/microsoft-sql-server-elastic-pool.bicep
- cloud-infrastructure/modules/microsoft-sql-server.bicep
- cloud-infrastructure/modules/private-endpoint-sql-server.bicep
- cloud-infrastructure/modules/virtual-network.bicep
- cloud-infrastructure/shared/main-shared.bicep
Address deployment errors when making revision-based changes to the Azure Container App, which requires a new revision suffix. The revision suffix is now exclusively managed through the `az container app update` command when deploying new container images. The only exception to this rule is the assignment of the suffix `initial` during the creation of a new container. Note that Bicep will make a random suffix in the rare case where revision-based changes are done (like changing CPU, Memory, and scaling rules).
Furthermore, the `account-management-api` configuration is adjusted to run 1 replica by default, rather than 0. The Container App Bicep module has been enhanced with `minReplicas` and `maxReplicas` parameters, with default values set to 1 and 3, respectively.
Additionally, a minor …
> Streamline Azure Container App deployments and update Bicep resource versions

- application/account-management/Api/Tenants/TenantEndpoints.cs
- application/account-management/Api/Users/UserEndpoints.cs
- application/account-management/Application/Tenants/CreateTenant.cs
- application/account-management/Application/Tenants/DeleteTenant.cs
- application/account-management/Application/Tenants/GetTenant.cs
- application/account-management/Application/Tenants/UpdateTenant.cs
- application/account-management/Application/Users/CreateUser.cs
- application/account-management/Application/Users/DeleteUser.cs
- application/account-management/Application/Users/GetUser.cs
- application/account-management/Application/Users/UpdateUser.cs
- application/account-management/Tests/Api/Tenants/TenantEndpointsTests.cs
- application/account-management/Tests/Api/Users/UserEndpointsTests.cs
- application/account-management/Tests/Application/Tenants/CreateTenantValidationTests.cs
- application/account-management/Tests/Application/Tenants/TenantCreatedEventHandlerTests.cs
Previously, Commands, Queries, Handlers, and Validators were nested within a static class named after the command or query. For instance, the `CreateTenantCommand` static class included nested `Command`, `Handler`, and `Validator` classes. This approach, while structured, led to references like `CreateTenant.Command` in the API, which received multiple remarks for its complexity and readability.
Addressing these concerns, the nested classes have now been elevated to the top level and renamed accordingly. For example, what was previously `CreateTenant.Command` is now `CreateTenantCommand`.
> Refactoring CQRS structure for enhanced clarity and accessibility

- .github/workflows/application.yml
- application/account-management/Api/Api.csproj
- application/account-management/WebApp/WebApp.esproj
The GitHub workflow has been updated to utilize Java 17, ensuring compatibility with SonarCloud. This update is in response to a warning from SonarCloud stating: "The version of Java (11.0.21) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17." By upgrading to Java 17, we align with SonarCloud's requirements, ensuring continued support and avoiding potential disruptions in our analysis processes.
The .NET solution now includes WebApp as a dependency, necessitating the installation of node modules for a successful `dotnet build`. To address this, the `WebApp.csproj` file has been updated to execute `bun install`. Additionally, updates have been made to the API to run `dotnet tool restore` and `bun install` as a pre-build …
> Eliminate SonarCloud Java warnings on Pull Requests, remove Bun warnings in clean .NET build

- application/account-management/Api/Api.csproj
Recent changes to the Api's pre- and post-build events have been reverted. These events were recently changed to run in all modes, including DEBUG and RELEASE. However, this led to an issue in the Docker build process within GitHub, where `bun` was not installed, causing the release build to fail. To resolve this, the build events in the Api project are now set to execute only in DEBUG mode.
> Revert Api build events to DEBUG mode only

- .github/workflows/_publish-container.yml
- .github/workflows/application.yml
- README.md
- application/README.md
- application/account-management/Api/Api.csproj
- application/account-management/Api/Dockerfile
- application/docker-compose.yml
- cloud-infrastructure/README.md
The strategy for creating container images has been revised to optimize the build process. Instead of building self-contained systems within a multi-stage Dockerfile, the new approach reuses the build artifacts from the GitHub build when creating container images. This change addresses a critical issue that arose with the recent update, where the build of frontend artifacts inside the Docker build was failing in the GitHub runner. Specifically, failures were due to warnings during the `rspack build`, such as "warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)".
This change also opens up for completely removing the dependency on Dockerfiles and using the lightweight and secure .NET Chiseled Ubuntu images and using Aspire instead of Docker Compose for local orchestration.
With …
> Remove multi stage docker builds and reuse GitHub build, fixing container build when running in GitHub workflows

- .github/workflows/application.yml
- application/docker-compose.yml
- cloud-infrastructure/cluster/deploy-cluster.sh
- cloud-infrastructure/cluster/main-cluster.bicep
- cloud-infrastructure/modules/container-app.bicep
- cloud-infrastructure/modules/microsoft-sql-database.bicep
Rename the `Account Management API` container app, image, domain prefix, and related components to `Account Management`. This change reflects the integration of the API and SPA into the same container.
Add logic in Bicep to set the `PUBLIC_URL` and `CDN_URL` environment variables based on whether the container app has an FQDN attached. These variables are injected into the SPA by the newly added `WebAppMiddleware`.
Change in the SQL database SKU to 'Basic' to reduce hosting costs. This size is adequate for the current workload.
Update to the cluster deployment script to grant database permissions when running outside the GitHub action, such as from a terminal.
Lastly, modify the Docker Compose configuration to enable a quick shutdown of the SQL server container in 1 second.
> Update infrastructure to reflect combined API and WebApp

- .github/workflows/application.yml
- application/.run/Api_ WebApi.run.xml
- application/account-management/Api/Api.csproj
- application/account-management/Api/Dockerfile
- application/account-management/Application/Application.csproj
- application/account-management/Domain/Domain.csproj
- application/account-management/Infrastructure/Infrastructure.csproj
- application/account-management/Tests/Api/BaseApiTest.cs
- application/account-management/Tests/Application/Tenants/CreateTenantValidationTests.cs
- application/account-management/Tests/Tests.csproj
- application/global.json
- application/shared-kernel/ApiCore/ApiCore.csproj
- application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
- application/shared-kernel/ApiCore/Middleware/GlobalExceptionHandlerMiddleware.cs
- application/shared-kernel/ApiCore/Middleware/ModelBindingExceptionHandlerMiddleware.cs
- application/shared-kernel/ApiCore/Middleware/WebAppMiddleware.cs
- application/shared-kernel/ApplicationCore/ApplicationCore.csproj
- application/shared-kernel/DomainCore/DomainCore.csproj
- application/shared-kernel/InfrastructureCore/InfrastructureCore.csproj
- application/shared-kernel/Tests/Tests.csproj
Upgrade of all project files to .NET 8, including updating of `global.json`, Dockerfile, and related files. Update GitHub workflows to utilize .NET 8, aligning CI/CD processes with the latest .NET version.
Update all NuGet packages to their latest versions for .NET 8 compatibility. This is essential for Microsoft packages like Entity Framework to benefit from the new .NET 8 improvements.
Fix various regression bugs and warnings post-upgrade. This includes configuring JSON serialization globally to use camelCase for consistent and readable JSON data. Also, address the warning in Content-Security-Policy headers from using 'add' to 'append', preventing an "IDictionary.Add will throw..." warning.
Temporarily disable jetbrains-code-inspection until .NET 8 support is added.
> Upgrade to .NET 8 in projects, Dockerfile, GitHub workflows, etc.

- application/account-management/Application/Tenants/CreateTenant.cs
- application/account-management/Application/Tenants/DeleteTenant.cs
- application/account-management/Application/Tenants/GetTenant.cs
- application/account-management/Application/Tenants/TenantCreatedEventHandler.cs
- application/account-management/Application/Tenants/UpdateTenant.cs
- application/account-management/Infrastructure/AccountManagementDbContext.cs
- application/account-management/Infrastructure/Tenants/TenantRepository.cs
- application/shared-kernel/ApiCore/ApiResults/ApiResult.cs
- application/shared-kernel/ApplicationCore/Behaviors/PublishDomainEventsPipelineBehavior.cs
- application/shared-kernel/ApplicationCore/Behaviors/UnitOfWorkPipelineBehavior.cs
- application/shared-kernel/ApplicationCore/Behaviors/ValidationPipelineBehavior.cs
- application/shared-kernel/DomainCore/Entities/AudibleEntity.cs
- application/shared-kernel/DomainCore/Entities/Entity.cs
- application/shared-kernel/DomainCore/Identity/StronglyTypedId.cs
- application/shared-kernel/DomainCore/Identity/StronglyTypedIdTypeConverter.cs
- application/shared-kernel/InfrastructureCore/EntityFramework/ModelBuilderExtensions.cs
- application/shared-kernel/InfrastructureCore/EntityFramework/UpdateAuditableEntitiesInterceptor.cs
- application/shared-kernel/InfrastructureCore/InfrastructureCoreConfiguration.cs
- application/shared-kernel/InfrastructureCore/Persistence/RepositoryBase.cs
- application/shared-kernel/InfrastructureCore/Persistence/UnitOfWork.cs
Refactoring applicable constructors across the project to leverage the new C# 12 primary constructors. This change simplifies the constructor syntax and enhances code readability and maintainability.
Additionally, the formatting of existing type declarations has been standardized to ensure consistency throughout the codebase.
> Update code to use C# 12 primary constructors

- .github/workflows/application.yml
- application/Directory.Packages.props
- application/account-management/Api/Api.csproj
- application/account-management/Tests/Tests.csproj
- application/shared-kernel/ApiCore/ApiCore.csproj
- application/shared-kernel/ApplicationCore/ApplicationCore.csproj
- application/shared-kernel/DomainCore/DomainCore.csproj
- application/shared-kernel/InfrastructureCore/InfrastructureCore.csproj
- application/shared-kernel/Tests/Tests.csproj
This update introduces central package management for NuGet packages, a feature from .NET 6. It involves adding a `Directory.Packages.props` file in the root of the solution. All `.csproj` files have been updated to not specify versions.
> Use central package management for easy updates NuGet packages

- application/account-management/Application/Users/CreateUser.cs
- application/account-management/Application/Users/DeleteUser.cs
- application/account-management/Application/Users/GetUser.cs
- application/account-management/Application/Users/UpdateUser.cs
- application/shared-kernel/ApiCore/Middleware/GlobalExceptionHandlerMiddleware.cs
- application/shared-kernel/ApiCore/Middleware/ModelBindingExceptionHandlerMiddleware.cs
- application/shared-kernel/InfrastructureCore/Persistence/DomainEventCollector.cs
- application/shared-kernel/Tests/TestEntities/TestAggregate.cs
- application/shared-kernel/Tests/TestEntities/TestAggregateRepository.cs
- application/shared-kernel/Tests/TestEntities/TestDbContext.cs
Refactoring the remaining parts of the codebase to make use of primary constructors wherever possible.
> Convert more constructors to primary constructors

- .github/workflows/application.yml
Optimizes the build pipeline by combining the `build` and `test-with-code-coverage` jobs. Both were installing .NET, bun, and restoring .NET packages and tools. Overall, this makes the pipeline complete faster using fewer resources.
Make the jetbrains-code-inspection job run in complete isolation. It must pass before merging pull-requests, but it's not running on `main`.
> Simplify and speed up application GitHub workflow by combining build and test-with-code-coverage job

- .github/workflows/_deploy-container.yml
- .github/workflows/cloud-infrastructure.yml
This change temporarily disables the production cluster, a strategic move to conserve Azure resources. This includes both the deployment of infrastructure shared resources, such as log analytics, and the production-west-europe cluster, as well as suspending the deployment of application docker images to the production-west-europe cluster.
> Temporarily disable production cluster to conserve Azure resources

- application/shared-kernel/ApiCore/Middleware/WebAppMiddleware.cs
In development mode it often happens that the WebApp build folder is being created as the server starts up - the UseStaticFiles middleware throws an exception if the folder doesn't exist.
This is only an issue in development mode.
> Wait for WebApp build to be ready in development mode

- .github/workflows/application.yml
In a previous update (refer to [pull request #229](https://github.com/PlatformPlatform/platformplatform/pull/229)), code inspections were inadvertently disabled for pull requests and enabled for the main branch. This reverts that change, so code inspections now run on pull requests.
> Shift code inspections to execute on pull requests

- application/Directory.Packages.props
- application/account-management/Tests/Tests.csproj
- application/shared-kernel/Tests/Tests.csproj
Configure Xunit tests to run in parallel using the `Meziantou.Xunit.ParallelTestFramework` NuGet package. This change reduces the test execution time of the test suite on a developer's laptop from 16 to 6 seconds. On GitHub runners, the `Run Test with dotCover and SonarScanner reporting` step is shortened from an average of 1m 55s to 1m 35s.
By default, Xunit treats each class as a test collection, and tests within a test collection run sequentially. The `Meziantou.Xunit.ParallelTestFramework` package configures tests to run in parallel by default, with each test in its own test collection. Tests that require sequential execution can be marked with the `[Collection("Sequential")]` attribute.
> Speed up tests with parallel execution

- application/account-management/Tests/Api/ApiCore/CustomExceptionHandlingTests.cs
- application/account-management/Tests/Api/BaseApiTest.cs
- application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
- application/shared-kernel/ApiCore/ApiResults/ApiResult.cs
- application/shared-kernel/ApiCore/Middleware/GlobalExceptionHandler.cs
- application/shared-kernel/ApiCore/Middleware/ModelBindingExceptionHandlerMiddleware.cs
- application/shared-kernel/ApiCore/Middleware/TimeoutExceptionHandler.cs
Simplify the creation of problem details to adhere to RFC standards, using .NET to set the 'Type' field to relevant URLs, like `https://tools.ietf.org/html/rfc9110#section-15.5.5` for a `404 Not Found` error. 
Also, implement the built-in `Results.Problem(...)` method to automatically set the `httpContext.Response.ContentType` to `application/problem+json` and ensure correct JSON serialization. Update tests accordingly. This greatly simplifies the code.
Additionally, add a `traceId` to the ProblemDetails extension for server-side exceptions. The can be shown in the client and used in support scenarios.
> Streamline creation of problem details to align with RFC standards

- cloud-infrastructure/cluster/deploy-cluster.sh
- cloud-infrastructure/cluster/main-cluster.bicep
- cloud-infrastructure/modules/container-app.bicep
- cloud-infrastructure/modules/managed-certificate.bicep
Add the Application Insights connection string as an environment variable, named `APPLICATIONINSIGHTS_CONNECTION_STRING`, to the Azure Container App. This is a special name that enables the Application Insights SDK to automatically recognize and use this connection string, eliminating the need for additional configuration.
Opting not to retrieve the connection string via Bicep due to a known issue (see [GitHub Issue #157](https://github.com/Azure/arm-template-whatif/issues/157)), which affects the `--what-if` functionality. Instead, the Azure CLI is used to fetch the connection string and pass it as a parameter to Bicep, ensuring the `--what-if` functionality remains effective.
To enhance clarity, the `environmentName` and `environmentId` parameters in the Bicep container App module have …
> Integrate Application Insights connection string with Azure Container App

- .github/workflows/application.yml
- application/Directory.Packages.props
- application/account-management/Application/Tenants/CreateTenant.cs
- application/account-management/Application/Tenants/DeleteTenant.cs
- application/account-management/Application/Tenants/UpdateTenant.cs
- application/account-management/Application/Users/CreateUser.cs
- application/account-management/Application/Users/DeleteUser.cs
- application/account-management/Application/Users/UpdateUser.cs
- application/account-management/Tests/Api/BaseApiTest.cs
- application/account-management/Tests/Api/Tenants/TenantEndpointsTests.cs
- application/account-management/Tests/Application/Tenants/CreateTenantValidationTests.cs
- application/account-management/Tests/BaseTest.cs
- application/account-management/Tests/Tests.csproj
- application/shared-kernel/ApiCore/ApiCore.csproj
- application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
- application/shared-kernel/ApiCore/Aspire/ServiceDefaultsExtensions.cs
- application/shared-kernel/ApplicationCore/ApplicationCore.csproj
- application/shared-kernel/ApplicationCore/ApplicationCoreConfiguration.cs
- application/shared-kernel/ApplicationCore/Behaviors/PublishAnalyticEventsPipelineBehavior.cs
- application/shared-kernel/ApplicationCore/Behaviors/ValidationPipelineBehavior.cs
- application/shared-kernel/ApplicationCore/Tracking/AnalyticEventCollector.cs
- application/shared-kernel/Tests/ApplicationCore/Tracking/AnalyticEventsCollectorSpy.cs
Configure Application Insights to track requests, exceptions, dependencies, traces, and custom events. To align with Application Insights' shift towards OpenTelemetry, the OpenTelemetry SDK is utilized for collecting all supported telemetry types (requests, exceptions, dependencies, and traces). However, for custom events, the traditional Microsoft.ApplicationInsights SDK is employed.
Custom events, termed "analytics events" to distinguish them from DDD Domain and Integration Events, are crucial for tracking specific feature usages for business insights. These events are not to be tracked until after an operation is successfully completed. For instance, `TenantCreated` and `UserCreated` events should only be logged in Application Insights once these entities are securely saved to the …
> Add telemetry with Application Insights and OpenTelemetry

- application/Directory.Packages.props
- developer-cli/Installation/ChangeDetection.cs
- developer-cli/Installation/PrerequisitesChecker.cs
Update .NET Aspire to preview 2. Update the CLI tool prerequisites checker to show a warning if the incorrect Aspire version is installed.
Simultaneously, update all NuGet packages to the latest version. This includes OpenTelemetry, ASP.NET HealthChecks, and Yarp.ReverseProxy used in .NET Aspire, as well as an upgrade to Application Insights NuGet packages and xUnit and Bogus NuGet packages used for testing.
Refine the change detection in the Developer CLI to solely evaluate files that are part of the Git repository. This avoids triggering changes if, for example, Rider configurations are changed.
> Upgrade .NET Aspire to preview 2 and upgrade NuGet packages

- .vscode/settings.json
When using the VS Code Github extension workflows to start working on issues the branch name was formatted:
```js
"${user}/issue-${issueNumber}"
```
When using github.com to create a branch the name was formatted:
```js
"${issueNumber}-${sanitizedIssueTitle}"
```
This pr aligns the GitHub extension with github.com
> Update vs code github extension branch naming

- .vscode/settings.json
Modify the VS Code GitHub extensions configuration to create branch names in lowercase. This aligns with GitHub's default naming convention of `{issue number}-{issue-title-in-lower-case-spinal}` when branches are created from the issue page on github.com.
> Convert branch naming in GitHub VS Code extension to lowercase

- application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
Our service is served behind a proxy both locally and in the cloud. We need to enable support for for proxy headers such as X-Forwarded-For and X-Forwarded-Proto to resolve the request client ip correctly.
> Enable support for proxy headers

- application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
- application/shared-kernel/ApiCore/Filters/EndpointTelemetryFilter.cs
We don't want to track calls for internal infrastructure endpoints. This pr adds an Endpoint Telemetry Filter
> Exclude tracking of live metrics health and track endpoints

- application/shared-kernel/ApiCore/Aspire/ServiceDefaultsExtensions.cs
Enrich OpenTelemetry data adding Client IP for user location
> Add client ip in OpenTelemetry tracking

- cloud-infrastructure/modules/container-app.bicep
Modify the dynamic construction of the SQL Server connection string in Bicep. Replace the use of `environment().sqlManagement` with `environment().suffixes.sqlServerHostname`. This change ensures the connection string correctly uses `.database.windows.net`, aligning with standard SQL Server hostname conventions, instead of the previously returned `https://management.core.windows.net:8443/`.
> Refine the dynamic SQL Server connection string construction in Bicep

- developer-cli/Installation/ChangeDetection.cs
On Windows, the publish folder for the CLI may contain spaces (due to a user account name with spaces), MSBuild will split the path using space and create multiple switches, resulting in the build error MSB1008. Example path: C:\Users\Martin Rosén-Lidholm\AppData\Local\PlatformPlatform. The fix is to put quotes around the path.
> Fix change detection in CLI when publish folder contains space

- application/AppHost/Program.cs
- application/Directory.Packages.props
- application/dotnet-tools.json
- application/global.json
- developer-cli/Installation/PrerequisitesChecker.cs
.NET Aspire has been upgraded to preview 3. In conjunction, the .NET SDK has been updated to version 8.0.200, as well as ASP.NET Core and EF Core have also seen updates to versions 8.0.1 and 8.0.2.
All NuGet packages within the project have been upgraded to their latest version. This includes upgrading the .NET SonarScanner tool to version 6.1.0.
> Update .NET ecosystem and NuGet packages to latest versions including .NET Aspire Preview 3

- .github/workflows/_publish-container.yml
- .github/workflows/application.yml
- .github/workflows/cloud-infrastructure.yml
All GitHub Actions used in the project are updated to their latest versions, a move primarily motivated by the deprecation of Node.js version 16. The updates include transitioning from:
- actions/checkout@v3 to actions/checkout@v4
- actions/download-artifact@v3 to actions/download-artifact@v4
- actions/upload-artifact@v3 to actions/upload-artifact@v4
- docker/setup-buildx-action@v2 to docker/setup-buildx-action@v3
- actions/setup-dotnet@v3 to actions/setup-dotnet@v4
- actions/setup-java@v3 to actions/setup-java@v4
However, azure/login@v1 remains unchanged as it awaits an update for Node.js 20 compatibility, as discussed in https://github.com/Azure/login/issues/357.
> Upgrade GitHub actions to latest versions for Node.js compatibility

- application/AppHost/Program.cs
With this pull request, we specify the port of the SQL Server container, so that it becomes easier to query our database when we are outside of docker.
> Specify a specific port for the SQL server container

- cloud-infrastructure/cluster/deploy-cluster.sh
- cloud-infrastructure/cluster/main-cluster.bicep
Fix first-time deployment of Azure Container App when Azure Communication Services is not fully provisioned. The Container App attempts to read the email address for sending emails, which is not available.
Remove warning from az application-insights extension.
> Fix dependencies between Azure Container App and Communication Services

- application/AppHost/Program.cs
- application/Directory.Packages.props
- application/shared-kernel/ApplicationCore/Services/IEmailService.cs
- application/shared-kernel/InfrastructureCore/InfrastructureCore.csproj
- application/shared-kernel/InfrastructureCore/InfrastructureCoreConfiguration.cs
- application/shared-kernel/InfrastructureCore/Services/AzureEmailService.cs
- application/shared-kernel/InfrastructureCore/Services/DevelopmentEmailService.cs
Create an `IEmailService` for sending emails from the platform.
Implement `AzureEmailService` to utilize the Email Communication Service when operating in Azure environments. This service should fetch the Azure Communication Service's connection string from Key Vault and retrieve the sender's email address from an environment variable.
For local development environments, establish a `DevelopmentEmailService`. Integrate a MailHog Email Docker Server into `AspireHost` to facilitate straightforward email testing. This service will capture all outgoing emails, making them accessible through an inbox viewable directly from the Aspire Dashboard.
> Create email signature service for both production and development

- application/account-management/Api/appsettings.json
- application/account-management/Directory.Build.props
- application/shared-kernel/Directory.Build.props
Reverts the `<UseArtifactsOutput>` setting in .NET 8 projects, which resolves an issue preventing Entity Framework migrations from being executed. Additionally, a development connection string has been added to facilitate Entity Framework migration processes.
> Fix failing Entity Framework migrations

- developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
This pull request fixes a previous error where we need to wrap the execution into the RunAzureCliCommand method which provides the `az` command for Azure CLI.
> Fix typo when calling an Azure CLI command

- application/shared-kernel/InfrastructureCore/InfrastructureCoreConfiguration.cs
- cloud-infrastructure/modules/container-app.bicep
- cloud-infrastructure/modules/key-vault.bicep
Fix the connection to KeyVault, which failed to use the managed identity of the Azure Container App. Add the ID of the Account Management Managed Identity ID as an environment variable (named `MANAGED_IDENTITY_CLIENT_ID`) to Azure Container Apps, and use this to explicitly specify the Identity when creating `DefaultAzureCredentialOptions`.
Change the KeyVault configuration to use Role-Based Access Control instead of the legacy Key Vault access policy. Grant the Account Management Managed Identity ID `Key Vault Secrets User role` permissions.
> Fix connection to Azure KeyVault

- application/account-management/Api/AccountRegistrations/AccountRegistrationsEndpoints.cs
- application/account-management/Application/AccountRegistrations/IsSubdomainFree.cs
- application/account-management/Tests/Api/AccountRegistrations/AccountRegistrationsTests.cs
Introduce a lightweight endpoint dedicated to verifying subdomain availability during the account registration process. Include tests.
> Add endpoint for subdomain availability check

- application/account-management/Api/AccountRegistrations/AccountRegistrationsEndpoints.cs
- application/account-management/Api/Tenants/TenantEndpoints.cs
- application/account-management/Api/Users/UserEndpoints.cs
- application/account-management/Application/Tenants/DeleteTenant.cs
- application/account-management/Application/Tenants/GetTenant.cs
- application/account-management/Application/Users/DeleteUser.cs
- application/account-management/Application/Users/GetUser.cs
- application/account-management/Application/Users/GetUsers.cs
- application/account-management/Application/Users/GetUsersDto.cs
- application/account-management/Domain/Users/IUserRepository.cs
- application/account-management/Domain/Users/UserTypes.cs
- application/account-management/Infrastructure/Users/UserRepository.cs
- application/account-management/Tests/Api/Tenants/TenantEndpointsTests.cs
- application/account-management/Tests/Api/Users/UserEndpointsTests.cs
- application/shared-kernel/DomainCore/Persistence/SortOrder.cs
Add API endpoints to allow searching, sorting, and pagination of users. The result includes a list of `UserDto`s, total found rows, and total pages. This enables the frontend to display pagination information like "Showing 50 users, Page 2 out of 12 pages."
Update the API endpoint to use `[AsParameters]`, enabling the addition of `GetUsersQuery` as an API contract. In the OpenAPI contract, this will show all the possible query string parameters.
Here is an example showing the possibilities:
`/api/users?search=john&userRole=TenantOwner&pageSize=10&pageOffset=0&orderBy=Email&sortOrder=Descending`
> Add API endpoints and logic for searching, sorting, and pagination

- application/account-management/Api/Program.cs
- application/account-management/Domain/AccountRegistrations/AccountRegistration.cs
- application/account-management/Domain/Tenants/TenantTypes.cs
- application/account-management/Domain/Users/UserTypes.cs
- application/account-management/WebApp/app/register/components/actions.ts
- application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
- application/shared-kernel/DomainCore/Identity/StronglyTypedId.cs
- application/shared-kernel/DomainCore/Persistence/SortOrder.cs
After upgrading from Swashbuckle to NSwag, the Swagger UI displayed strongly typed IDs, such as `TenantId` and `UserId`, as complex objects `{ "value": "string" }` instead of simply a `string`. This issue affected only the UI and TypeScript definitions, necessitating the suppression of a warning.
The solution involves loading all strongly typed IDs and overriding the default in the `AddOpenApiDocument` configuration's `settings.PostProcess()`.
Additionally, the convention for creating strongly typed IDs has been updated to avoid creating a TypeConverter class for each strongly typed ID.
> Update Swagger contract generation to correctly treat strongly typed IDs as plain text

- application/shared-kernel/InfrastructureCore/InfrastructureCoreConfiguration.cs
This Pull request will only register the Repository classes in the DI container. This way we avoid the registration of classes that are inside the same assembly.
> Configure Scrutor to only register the repository classes within the Assembly

- .gitignore
- application/Directory.Packages.props
- application/account-management/Api/Api.csproj
- application/account-management/Api/appsettings.json
- application/account-management/WebApp/eslint.config.js
- application/account-management/WebApp/package.json
- application/shared-kernel/ApiCore/Middleware/WebAppMiddlewareConfiguration.cs
- application/shared-kernel/ApiCore/Middleware/WebAppMiddlewareExtensions.cs
- application/shared-kernel/InfrastructureCore/InfrastructureCoreConfiguration.cs
Replace the custom Post Build Event used to generate the Open API JSON file with NSwag by leveraging .NET's built-in but undocumented `OpenApiGenerateDocumentsOnBuild` property. Although NSwag is still utilized behind the scenes, this adjustment eliminates the need for the custom event, making the implementation much cleaner.
When generating the Open API file, the .NET API process still needs to be started. However, this change ensures that any .NET exceptions in the startup are displayed directly in the output. Previously, with the custom post-build event, the output was cluttered with information about the NSwag configuration, obscuring the root cause.
Previously, the `SWAGGER_GENERATOR` environment variable was passed to .NET during Open API generation to avoid running Database …
> Streamline Open API Documentation generation with built-in OpenApiGenerateDocumentsOnBuild property

- application/AppHost/AppHost.csproj
- application/PlatformPlatform.sln
- application/account-management/WebApp/WebApp.esproj
Upgrade `Microsoft.VisualStudio.JavaScript.SDK` to the final version and add the `WebApp` dependency back to the Aspire AppHost project.
This change allows for the removal of the configuration where the WebApp was added as a dependency in the `PlatformPlatform.sln` file. Consequently, it is now possible to run `pp run` without first needing to build the entire solution, as `pp run` was just running AppHost but did not build the WebApp.
> Add WebApp dependency to Aspire AppHost after upgrading Microsoft.VisualStudio.JavaScript.SDK

- application/AppHost/AppHost.csproj
- application/AppHost/Program.cs
- application/Directory.Packages.props
Use .NET Aspire's `AddAzureStorage` and `RunAsEmulator` to configure the Azure storage emulator for localhost development. Behind the scenes, Aspire utilizes the `azure-storage/azurite` Docker container to emulate Blob, Queue, and Table Storage. When the Aspire AppHost is started, the storage emulator automatically starts.
> Set up emulator for storage for local development

- cloud-infrastructure/cluster/main-cluster.bicep
- cloud-infrastructure/modules/container-app.bicep
- cloud-infrastructure/modules/microsoft-sql-server-diagnostic.bicep
- cloud-infrastructure/modules/role-assignments-container-registry-acr-pull.bicep
- cloud-infrastructure/modules/role-assignments-storage-blob-data-contributor.bicep
- cloud-infrastructure/modules/storage-account.bicep
Add a new Azure Blob Storage Container to the Account Management self-contained system for storing user profile avatars.
Introduce the `STORAGE_ACCOUNT_URL` environment variable to the container app and switch to using `DATABASE_CONNECTION_STRING` for the database, moving away from the `ConnectionStrings__${sqlDatabaseName}` format.
Update the storage account Bicep module to include the option of creating default containers as part of the infrastructure deployment, and add an `Avatars` container.
Reorganize Bicep resources to position the Container App Environment at the top and consolidate all Account Management SCS resources at the bottom.
Refactor the role-assignment module for Blob Data Contributor for clarity and consistency, and rename the existing ACR Pull role assignment module …
> Add blob storage infrastructure to Account Management and create avatars container

- .github/workflows/application.yml
- application/AppGateway/AppGateway.csproj
Add GitHub action jobs to publish the App Gateway to the Container Registry and deploy the Azure Container App, adopting the new `dotnet publish` approach for publishing containers to the container registry, moving away from Dockerfile.
Update the AppGateway project file using `ContainerFamily` property to set Alpine as base image, and set the default `ContainerPort` to `8080`.
Rename the Account Management API container image, deployment steps, and deployment artifacts in the API for enhanced clarity.
Modify the display names of the Setup Java and Setup Node steps to align with the naming convention of other GitHub action steps.
Incorporate version numbers into .NET assemblies to facilitate accurate logging in Application Insights.
> Configure deployment for App Gateway and standardize naming of GitHub action steps

- application/account-management/Api/Api.csproj
The Alpine container image used to deploy the API failed when running Entity Framework queries, with a `CultureNotFoundException` (see this GitHub Issue: https://github.com/dotnet/SqlClient/issues/2239).
The root cause is that the SqlClient doesn't support invariant globalization.
The solution requires that the docker container has ICU libraries installed. Using a Dockerfile, this would be simple, but since we are using `dotnet publish -t:PublishContainer ...` we change the container image from `alpine` to `jammy-chiseled-extra`. Not a perfect solution as this image is bigger, and hence also has a bigger attack surface.
> Change API container image to use jammy-chiseled-extra container image which includes ICU libraries

- application/Directory.Packages.props
- application/dotnet-tools.json
Upgrade .NET NuGet packages, including AspNetCore and EF Core to 8.0.4, and upgrade SonarScanner to the latest version. This addresses an issue where GitHub build agents failed when utilizing outdated tooling.
> Upgrade .NET NuGet packages and .NET tooling

- application/AppHost/Program.cs
Update the path configuration for Azurite, ensuring that uploaded avatars are correctly persisted between Aspire sessions.
> Ensure uploaded avatars are persisted between Aspire sessions

- .github/workflows/_publish-container.yml
- .github/workflows/application.yml
- application/AppGateway/AppGateway.csproj
- application/AppGateway/Dockerfile
- application/account-management/Api/Api.csproj
- application/account-management/Api/Dockerfile
Reintroduce Dockerfile for building to create smaller and safer images than those generated with `8.0-jammy-chiseled-extra`, which was found to have several open CVEs. The initial switch to `jammy-chiseled-extra` was solely for the installation of `icu-libs` and to set `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` to false, a requirement dictated by SQLClient.
Additionally, this change fixes a problem where the frontend build files are correctly incorporated into the images.
> Reintroduce Dockerfile for building containers to get smaller and safer images

- application/AppHost/AppHost.csproj
- application/AppHost/Program.cs
- application/AppHost/Properties/launchSettings.json
- application/AppHost/SecretManagerHelper.cs
- application/Directory.Packages.props
- application/shared-kernel/ApiCore/Aspire/ServiceDefaultsExtensions.cs
- developer-cli/Commands/ConfigureDeveloperEnvironmentCommand.cs
- developer-cli/Commands/InstallCommand.cs
- developer-cli/Commands/RunCommand.cs
- developer-cli/Commands/UninstallCommand.cs
- developer-cli/Installation/PrerequisitesChecker.cs
Upgrade to .NET Aspire preview 5, including updates to all associated NuGet dependencies and addressing breaking changes. In preview 5, NuGet packages are much more granular, leading to the addition of several new packages and the removal of many that were unused.
Additionally, upgrade all NuGet packages to the latest versions, including OpenTelemetry.Instrumentation, which had a security vulnerability.
Finally, in Aspire preview 5, one can no longer start a SQL Server with a given password using a simple string. It now requires a complex `IResourceBuilder<ParameterResource>`, necessitating the creation of a new `SecretManagerHelper` class with a `CreateStablePassword` method to generate a password. Going forward, the AppHost from Aspire will generate a SQL Server password the first time …
> Update to .NET Aspire preview 5

- application/shared-kernel/ApiCore/ApiCore.csproj
Remove the `Microsoft.AspNetCore.Mvc.ApiExplorer` deprecated package, since the `Microsoft.AspNetCore.Mvc.ApiExplorer` assembly is referenced by the `Microsoft.AspNetCore.App` framework
> Remove deprecated package Microsoft.AspNetCore.Mvc.ApiExplorer 

- application/account-management/AccountManagement.sln
Add the AppHost project to the Account Management solution. This integration allows developers to work on the Account Management self-contained system in isolation, separate from the Shared Kernel and other self-contained systems. When starting the AppHost, dependencies will automatically be initiated, enabling effective debugging.
This functionality was previously disabled because Visual Studio on Windows did not compile if the AppHost had a dependency on the WebApp, which disrupted this capability.
In Rider, it might be needed to build the Shared Kernel, because Rider tries to optimize the build process and is not using MSBuild. This is not a problem in practice, as the Shared Kernel will likely already be in the correct state.
> Enable development of Account Management self-contained systems in isolation

- application/Directory.Packages.props
- application/shared-kernel/ApiCore/Middleware/WebAppMiddleware.cs
- application/shared-kernel/ApiCore/Middleware/WebAppMiddlewareConfiguration.cs
- developer-cli/Installation/PrerequisitesChecker.cs
Upgrade to Aspire preview 6, a minor update that is likely the last preview before its general availability (GA). This update introduces no breaking changes.
The prerequisites in the PlatformPlatform CLI have been upgraded to check for preview 6.
Upgrade all NuGet packages to latest version including OpenTelemetry, XUnit, and FluentValidation.
> Update to .NET Aspire preview 6

- application/account-management/Application/Users/UpdateUser.cs
- application/account-management/Domain/Users/User.cs
- application/account-management/Infrastructure/Users/UserRepository.cs
- application/account-management/Tests/Api/BaseApiTest.cs
- application/account-management/Tests/Api/Tenants/TenantEndpointsTests.cs
- application/account-management/Tests/Api/Users/UserEndpointsTests.cs
- application/account-management/Tests/DatabaseSeeder.cs
This pull request adds extra tests for the `GetUsersQuery` that handles user searches.
The search logic is updated to enable searches on full name. Additionally, the query logic has been optimized to request the Total Count from the database only if the primary result exceeds the page size, avoiding an extra database roundtrip in most cases.
The `User.Update` method is repurposed to update only the first name and last name. The existing `User.Update(email, userRole)` method is split into two separate methods, `UpdateEmail` and `ChangeUserRole`, to provide a clearer separation of use cases.
> Add tests for user search endpoint

- .github/workflows/application.yml
- application/account-management/Api/Properties/launchSettings.json
- application/account-management/Tests/Api/BaseApiTest.cs
- application/account-management/WebApp/WebApp.esproj
- application/account-management/WebApp/package.json
- application/account-management/WebApp/rspack.config.ts
This update significantly reduces the time required to start the frontend with Aspire, improving the startup time from approximately 10 seconds to less than 1 second, depending on the machine.
Until now, starting the Aspire AppHost required a full build of all frontend artifacts by the WebApp, resulting in slow startup times and a subpar developer experience. When developing, we use the RSPack devserver, so these frontend artifacts were not needed. The `WebApp.esproj` has been updated to only generate the API contract based on the OpenAPI `Api.json` generated by the API build.
The GitHub workflow has been updated to build the frontend bundles needed for production.
> Optimize frontend startup time when using Aspire

- .github/workflows/application.yml
- application/AppGateway/AppGateway.csproj
- application/account-management/Api/Api.csproj
- application/account-management/WebApp/App.tsx
- application/account-management/WebApp/WebApp.esproj
- application/account-management/WebApp/dist/index.html
- application/account-management/WebApp/package.json
- application/shared-kernel/ApiCore/Middleware/WebAppMiddlewareConfiguration.cs
- application/shared-kernel/ApiCore/Middleware/WebAppMiddlewareExtensions.cs
Speed up starting the frontend WebApp. Starting Aspire Dashboard and all dependencies now only takes a handful of seconds depending on the machine. This is accomplished while simultaneously optimizing the orchestration of the frontend build.
The following changes have been made:
- `dist/index.html` is added to git. This guarantees it's always available, allowing the API to start faster, as it previously waits for `index.html` to be created, which takes between 1-10 seconds. Retry logic from `WebAppMiddleware` is hence no longer needed and is removed. This in turn enables simplifying the generation of OpenAPI `Api.json` as this no longer needs to gracefully handle if `index.html` did not exist.
- MSBuild logic has been moved from the `WebApp.esproj` into `package.json`, greatly simplifying …
> Speed up starting and simplify building the WebApp

- README.md
Fix incorrect instructions in the README file where the directory name `development-cli` is mentioned. It should be `developer-cli`.
> Correct directory name for developer cli

- README.md
The `dotnet dev-certs` tool currently does not support Linux. To address this, we have added a small guide using the `dotnet` tool's `linux-dev-certs` command. Additionally, the guide includes steps on how to manually trust the generated certificates on Windows.
> Update WSL guide installing and trusting certificates

- application/account-management/WebApp/package.json
Upgrading to React 18.3.x broke the use of `useFormState`, which remains an experimental feature, which will hopefully make it into React 19. Until a permanent fix is found, we will continue to use React 18.3 canary.
> Revert React and React Dom to canary

- application/AppHost/Program.cs
- application/Directory.Packages.props
- developer-cli/Installation/PrerequisitesChecker.cs
Upgrade to Aspire preview 7, a minor unplanned update before general availability (GA). This update includes a small breaking change where `UseBlobPort()` was renamed to `WithBlobPort()`.
The prerequisites in the PlatformPlatform CLI have been upgraded to check for preview 7.
Additionally, upgrade all NuGet packages to the latest versions, including OpenTelemetry, XUnit, and Bogus.
> Update to .NET Aspire preview 7

- application/account-management/WebApp/package.json
When running on Windows, the WebApp build for Account-Management fails because it is using `rm` for deleting all files in the `dist` folder. `rm` does not exist on Windows so it fails. `rimraf` is an operating system agnostic tool for deleting files.
> Use rimraf for operating system agnostic deleting WebApp dist folder

- application/account-management/WebApp/package.json
Update the use of `rimraf` to only delete the content inside the folder, as deleting the entire folder made starting the WebApp fail.
> Update rimraf usage to only delete contents inside the dist folder, keeping the folder itself

- .github/workflows/application.yml
- README.md
- developer-cli/Commands/BuildCommand.cs
- developer-cli/Commands/CodeCleanupCommand.cs
- developer-cli/Commands/CodeCoverageCommand.cs
- developer-cli/Commands/CodeInspectionsCommand.cs
- developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
- developer-cli/Commands/DevCommand.cs
- developer-cli/Commands/InstallCommand.cs
- developer-cli/Commands/RunCommand.cs
- developer-cli/Commands/TestCommand.cs
- developer-cli/Commands/TranslateCommand.cs
- developer-cli/Installation/Configuration.cs
- developer-cli/Installation/PrerequisitesChecker.cs
- developer-cli/Utilities/ProcessHelper.cs
Update the `configure-continuous-deployments` command, so it now automatically triggers the `Cloud Infrastructure - Deployment` and `Application - Build and Deploy` GitHub workflows. This allows for a full setup of Azure infrastructure and CI/CD for application code by just answering two questions about naming of Azure resources, in addition to logging in to Azure and GitHub. After this, the entire process of setting up a fully automated CI/CD takes a few seconds, and the initial deployment takes about 45 minutes (primarily because of spinning up a full Azure container App Environment).
The `configure-continuous-deployments` has also been enhanced so it now only prompts users to log in to GitHub if they are not already authenticated, and a check has been added to ensure the user has Admin …
>  Enhance the CLI for setting up CI/CD and improve the first-time start of Aspire AppHost for better stability and usability

- .github/workflows/account-management.yml
- .github/workflows/app-gateway.yml
- README.md
- developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
Prepare for multiple self-contained systems by enabling isolated deployment of the AppGateway and AccountManagement. Split `application.yml` into `app-gateway.yml` and `application.yml`. Update the CLI for setting up CI/CD accordingly. Update the badges in the README file to reflect these changes.
> Split application.yml for isolated deployment of AppGateway and AccountManagement

- cloud-infrastructure/cluster/deploy-cluster.sh
- cloud-infrastructure/cluster/main-cluster.bicep
- cloud-infrastructure/environment/deploy-environment.sh
- cloud-infrastructure/environment/main-environment.bicep
- cloud-infrastructure/modules/application-insights.bicep
- cloud-infrastructure/modules/container-app.bicep
- cloud-infrastructure/modules/microsoft-sql-server-diagnostic.bicep
- cloud-infrastructure/modules/storage-account.bicep
- cloud-infrastructure/modules/user-assigned-managed-identity.bicep
- cloud-infrastructure/shared/deploy-shared.sh
- cloud-infrastructure/shared/main-shared.bicep
Make all Bicep module deployment names unique to avoid concurrent deployments of resources like managed identity container permissions. This resolves issues where deployments failed due to naming conflicts.
Fix race condition when assigning user-managed identity permissions to container registry immediately after creation. The fix involves setting the `principalType` to `ServicePrincipal` on Bicep `roleAssignments` resource.
Remove `-role-assignment` postfix from Bicep module names to allow for longer resource names, as deployment names in Bicep cannot be longer than 64 characters.
Ensure `deploy-cluster.sh` reliably checks for failed deployments even when `az CLI` outputs warnings. This ensures JSON results are parsed correctly by stripping any prefixed warning messages.
Rename …
> Stabilize infrastructure deployments by fixing race conditions and making deployment names unique

- .gitignore
- application/client-foundation/clientFilesystemRouter/lib/pageReactRoutesCode.ts
Mark unused methods in the generated client router with `// @ts-ignore` to prevent build errors when creating new self-contained systems like BackOffice.
Add generated files like images and `.map` files in the `WebApp/dist` folder to `.gitignore` to avoid including them in the repository during production builds.
> Suppress TypeScript errors in generated client router

- .github/workflows/account-management.yml
- .github/workflows/app-gateway.yml
Rename workflow jobs and steps with more generic names after splitting App Gateway and Account Management API into separate workflows. This removes the need for self-contained system prefixes in GitHub steps and actions.
Skip publishing Docker images when workflow is triggered from pull requests. This avoids unnecessary and failing Docker image publications, especially for external pull requests, as only workflows triggered by a maintainer have OIDC permissions to publish to Azure Container Registry.
Ensure unit tests and code coverage run even when Sonar Cloud is not configured. This ensures unit tests are executed when forking PlatformPlatform where Sonar Cloud is not configured by default.
Remove explicit "Install Node modules" step when building the WebApp as this step is now done …
> Streamline workflows and build processes

- .github/workflows/account-management.yml
- .github/workflows/app-gateway.yml
Revert previous changes made to the GitHub Actions workflow. The initial modification was intended to stop publishing artifacts used for Docker images on pull requests, but it had the opposite effect. This PR corrects that issue.
> Revert changes to GitHub Actions workflow for artifact publishing

- .github/workflows/account-management.yml
- .github/workflows/app-gateway.yml
- .github/workflows/back-office.yml
- application/Directory.Packages.props
- developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
- developer-cli/Installation/PrerequisitesChecker.cs
Update .NET Aspire to the GA (General Availability) version, replacing the previous preview versions. There are no breaking changes, so this is a straightforward update.
Update other NuGet packages to their latest versions, including updating ASP.NET and EF Core to version 8.0.5.
Update GitHub workflows to trigger build when files in `application/*` are changed.
> Update .NET Aspire to GA and update other NuGet packages to latest versions

- developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
Change the name of the SQL Server Admin AD group to include the container repository name as a postfix. This change is implemented in the `configure-continuous-deployment` CLI command.
Remove the `ACRPush` permissions from the GitHub Service Principal, as it already has `Contributor` rights.
> Update SQL Server Admin AD group naming and adjust permissions

- .github/workflows/cloud-infrastructure.yml
- developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
Add the missing CI/CD step for granting the BackOffice Managed Identity permissions to the database as part of the BackOffice self-contained system setup.
Update the `configure-continuous-deployments` CLI command to:
- Create federated credentials for pull requests, correcting a removal from the previous pull request.
- Check if a unique prefix is used for an Azure Container Registry on a different subscription.
- Create a 60-second countdown timer to allow canceling deployment to Azure.
> Update CI/CD steps and configure-continuous-deployments CLI command

- application/account-management/Workers/Program.cs
- application/back-office/Workers/Program.cs
- cloud-infrastructure/cluster/deploy-cluster.sh
- cloud-infrastructure/cluster/main-cluster.bicep
- cloud-infrastructure/modules/container-apps-environment.bicep
- cloud-infrastructure/modules/microsoft-sql-database.bicep
- developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
Enhance the behavior of Azure Container Apps for Workers by stopping background workers after database migrations. This change allows the workers to scale to zero, reducing hosting costs.
Update Azure Container App logs to use Log Analytics instead of Azure Monitor, enabling proper log viewing.
Fix the `grant-database-permissions` script to work correctly when deploying from localhost by correcting the parameters.
Reorder `main-cluster.bicep` to prioritize the creation of the Azure Communication Service resource, speeding up overall deployment.
Correct the "Successfully created an App Registration" message to include the App Registration name.
Remove double `;;` in the SQL connection string in Bicep, ensuring proper string formatting.
> Improve database migration and container apps logging

- application/account-management/Workers/Program.cs
- application/back-office/Workers/Program.cs
- application/shared-kernel/InfrastructureCore/InfrastructureCoreConfiguration.cs
- application/shared-kernel/InfrastructureCore/Services/AzureEmailService.cs
Revert "Simplify retry logic for handling when SQL Server is still starting on localhost". In a previous pull request, a different DB context execution strategy was introduced to simplify code that handles errors during database migrations locally while SQL Server was still starting. This change caused migrations to fail in Azure.
Revert "Stop background workers after they have run database migrations". In an earlier pull request, background workers running database migrations were made to stop in hopes of allowing Azure container apps to scale to 0. However, this caused the servers to crash and continuously restart.
Change mail sending in Azure to return when mail is initiated instead of waiting for delivery. Previously, sending mail using Azure Communication Services had …
> Revert and optimize database migration and email handling processes

- application/.editorconfig
- application/AppGateway/AppGateway.csproj
- application/AppHost/AppHost.csproj
- application/account-management/Api/AccountManagement.Api.csproj
- application/account-management/Application/AccountManagement.Application.csproj
- application/account-management/Directory.Build.props
- application/account-management/Domain/AccountManagement.Domain.csproj
- application/account-management/Infrastructure/AccountManagement.Infrastructure.csproj
- application/account-management/Tests/AccountManagement.Tests.csproj
- application/account-management/Workers/AccountManagement.Workers.csproj
- application/back-office/Api/BackOffice.Api.csproj
- application/back-office/Application/BackOffice.Application.csproj
- application/back-office/Directory.Build.props
- application/back-office/Domain/BackOffice.Domain.csproj
- application/back-office/Infrastructure/BackOffice.Infrastructure.csproj
- application/back-office/Tests/BackOffice.Tests.csproj
- application/back-office/Workers/BackOffice.Workers.csproj
- application/shared-kernel/ApiCore/Endpoints/TestEndpoints.cs
- application/shared-kernel/ApiCore/Middleware/GlobalExceptionHandler.cs
- application/shared-kernel/ApiCore/SharedKernel.ApiCore.csproj
- application/shared-kernel/ApplicationCore/SharedKernel.ApplicationCore.csproj
- application/shared-kernel/Directory.Build.props
- application/shared-kernel/DomainCore/SharedKernel.DomainCore.csproj
- application/shared-kernel/InfrastructureCore/SharedKernel.InfrastructureCore.csproj
- application/shared-kernel/Tests/SharedKernel.Tests.csproj
- developer-cli/.editorconfig
- developer-cli/DeveloperCli.csproj
- developer-cli/dotnet-tools.json
Update formatting rules to avoid conflicts between Visual Studio and code cleanup. The `.editorconfig` file has been updated to insert a space before the closing tag in XML. For example, `<ProjectReference Include="..."/>` is now `<ProjectReference Include="..." />`. This aligns with the default format when using Visual Studio and Rider to create project references. All `.csproj` and `.props` files have been updated to reflect this change.
> Update formatting rules to align Visual Studio and code cleanup

- application/account-management/Api/Program.cs
- application/account-management/Api/Properties/launchSettings.json
- application/back-office/Api/Program.cs
- application/back-office/Api/Properties/launchSettings.json
- application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
Simplify the .NET Aspire dashboard by removing `applicationUrl` from `launchSettings.json and moving the configuration to .NET code. This change ensures that only a link to the AppGateway is shown, making it easier to know which link to click to access the application.
> Remove links to API from the Aspire dashboard

- application/AppGateway/Program.cs
- application/AppGateway/Transformations/HttpStrictTransportSecurityTransform.cs
- application/AppGateway/Transformations/ManagedIdentityTransform.cs
Create HTTP Strict-Transport-Security (HSTS) `ResponseHeaderValueTransform` in AppGateway to enforce HSTS on all self-contained systems. This replaces the `app.UseHsts()` in the AppGateway `Program.cs`, which did not affect downstream services.
> Create HTTP Strict-Transport-Security ResponseHeaderValueTransform in AppGateway

- application/shared-webapp/build/plugin/DevelopmentServerPlugin.ts
Use specific match pattern to ignore own dist folder by including the sytem folder as part of the match pattern. We cannot match on "dist" alone as that would ignore all watch on changes in `shared-webapp` packages. Since we write files in to the dist folder also in development mode we have to ignore the webapp's own dist folder to prevent infinite recompilations.
> Use specific match pattern to ignore own dist folder

- application/account-management/WebApp/pages/-landing/sections/HeroSection.tsx
- application/account-management/WebApp/pages/__root.tsx
- application/back-office/WebApp/pages/__root.tsx
- application/package-lock.json
- application/package.json
- application/shared-webapp/build/package.json
- application/shared-webapp/infrastructure/package.json
- application/shared-webapp/infrastructure/themeMode/ThemeModeSelector.tsx
- application/shared-webapp/infrastructure/themeMode/useThemeMode.tsx
- application/shared-webapp/ui/package.json
- application/shared-webapp/utils/package.json
- application/turbo.json
We want users to choose what theme mode to use. This pr includes the initial infrastructure for enabling this.
We currently use local storage for persisting the user selected theme mode.
This pr also ensures packages to be build before starting the applications in development mode.
> Add infrastructure for the user to change the theme mode

- application/PlatformPlatform.sln
Ensure that working with Visual Studio 2022 on Windows does not change the format of the `.sln` file.
- Change .NET Projects types from `FAE04EC0-301F-11D3-BF4B-00C04F79EFBC` (old .NET Framework) to `9A19103F-16F7-4668-BE54-9A1E7A4F7556` (new .NET Core)
- Move `GlobalSection(SolutionProperties)` above `GlobalSection(NestedProjects)`
- Fix naming of `SharedKernel.Tests`
> Ensure .sln file format consistency with Visual Studio 2022

- application/account-management/Api/Users/UserEndpoints.cs
- application/account-management/Application/TelemetryEvents/TelemetryEvents.cs
- application/account-management/Application/Users/ChangeUserRole.cs
- application/account-management/Application/Users/UpdateUser.cs
- application/account-management/Tests/Api/Users/UserEndpointsTests.cs
- application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
Add option to update `FirstName`, `LastName`, and `Title` when calling `UpdateUserCommand`. Introduce a new endpoint and command for changing user roles.
Changing user roles is implemented as a separate endpoint, intended for Admin use only.
> Update API endpoint for updating user and create separate endpoint for changing user role

- application/account-management/Api/Program.cs
- application/account-management/Workers/Program.cs
- application/back-office/Api/Program.cs
- application/back-office/Workers/Program.cs
- application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
This pull request will configure kestrel to only listen to localhost and not any IP for the development environment. This change will also stop the firewall warnings popup from the APIs.
Also, rename ServerOnPort extension method to ConfigureDevelopmentPort to make it clear that this is only for development.
> Set up kestrel to listen to localhost instead of any IP

- application/AppGateway/Program.cs
- application/AppGateway/Transformations/BlockInternalApiTransform.cs
- application/AppGateway/Transformations/ManagedIdentityTransform.cs
- application/AppGateway/appsettings.json
- application/shared-kernel/ApiCore/Endpoints/HealthEndpoints.cs
- cloud-infrastructure/cluster/main-cluster.bicep
- cloud-infrastructure/modules/container-app.bicep
Configure Azure Container Apps HTTPS health probes for the Account Management and Back Office API and Workers for Live and Readiness health checks. AppGateway will continue using TCP health probes.
Initially, Azure Container App uses a QuickStart Image that lacks HTTP health endpoints. Therefore, HTTP health endpoints are configured only after infrastructure deployment when a self-contained system with health endpoints is deployed.
Relocate health endpoints to `[self-contained-system]/internal-api/live` and `[self-contained-system]/internal-api/readiness`.
Create a new `RequestTransformation` in YARP AppGateway to block all traffic to any path containing `/internal-api/`, ensuring that health endpoints are not publicly accessible but can be only accessed internally by Azure Container …
> Configure HTTPS health probes and secure internal health endpoints

- developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
- developer-cli/Utilities/ProcessHelper.cs
Ensure that when running the `configure-continuous-deployments` CLI command on a newly forked/cloned repository, GitHub workflows are enabled. Due to a recent change in GitHub, the CLI can no longer start a workflow using `gh workflow run` to enable workflows automatically. Now, if workflows are not enabled, a browser is opened, and the user must enable workflows before the CLI continues.
The `configure-continuous-deployments` CLI command has been updated to replace the null-conditional operator in `Config?.Path` with the null-forgiving operator `Config!.Path`. All GitHub CLI commands now explicitly specify the GitHub repository. Additionally, method names in the `configure-continuous-deployments` CLI command have been refined for consistency and clarity.
> Ensure GitHub workflows are enabled when running configure-continuous-deployments CLI command

- application/account-management/WebApp/package.json
- application/account-management/WebApp/pages/-landing/sections/CtaSection2.tsx
- application/account-management/WebApp/pages/-landing/sections/FeatureSection.tsx
- application/account-management/WebApp/pages/-landing/sections/FeatureSection3.tsx
- application/account-management/WebApp/pages/-landing/sections/FooterSection.tsx
- application/account-management/WebApp/pages/-landing/sections/TechnologySection.tsx
- application/account-management/WebApp/pages/-landing/sections/TechnologySection2.tsx
- application/back-office/WebApp/package.json
- application/package-lock.json
- application/package.json
- application/shared-kernel/ApiCore/SinglePageApp/SinglePageAppConfiguration.cs
- application/shared-webapp/build/package.json
- application/shared-webapp/infrastructure/package.json
- application/shared-webapp/ui/package.json
- application/shared-webapp/utils/package.json
- application/turbo.json
Addressed an issue causing intermittent white screens during the loading process due to an empty `index.html` file. The frontend build process creates an empty file and then writes to it afterward, leading to an empty file for a short period, which may result in a white screen.
Additionally, fixed an issue with the Application Insights bundle generation, which is also generated in two steps. If the web app is loaded with the first (smaller) file, it also results in a white screen.
The solution involves:
- Looping until the `index.html` is found.
- Extracting the Application Insights script path using a regex.
- Loading the script from the Web Server and checking if it’s the larger file.
Additional updates:
* Using `rimraf` as cross-platform `rm -rf`.
* Mark images on the landing page for …
> Fix white screen issue when loading website and improve build performance of frontend

- cloud-infrastructure/modules/container-app.bicep
Change liveness and readiness health probes scheme from HTTPS to HTTP. In a previous pull request, we switched from TCP to HTTP health probes for the API in Azure Container App. However, these failed to start because the scheme was set to HTTPS instead of HTTP. This PR corrects the scheme to HTTP, ensuring proper functionality.
> Change liveness and readiness health probes scheme from HTTPS to HTTP

- .github/workflows/_deploy-container.yml
- .github/workflows/account-management.yml
- .github/workflows/app-gateway.yml
- .github/workflows/back-office.yml
- cloud-infrastructure/cluster/main-cluster.bicep
Add logic to deployment workflows to monitor deployments and fail workflows if activation does not result in a healthy running container. This ensures that any issues during deployment are promptly identified and addressed.
Change health probes for worker containers to use TCP instead of HTTP, improving reliability and accuracy in monitoring the health of worker containers.
Update deployment logic to ensure that any changes to `_deploy-container.yml` trigger the deployment of self-contained systems.
> Enhance deployment workflows with monitoring and update health probes for workers

- application/AppHost/Program.cs
Ensure Azurite is using the latest image to prevent application startup failures on local machines. Aspire sometimes does not use the latest version of the Docker image for Azurite, which causes issues due to hard dependencies in the .NET Azure Storage SDK on newer versions of Azurite. If Aspire starts with an older version, exceptions are thrown indicating that Azurite does not support the specific API version used in the SDK. This update ensures compatibility and prevents these exceptions, enhancing development reliability and performance.
> Ensure Aspire is using the the latest version of the Azurite image

- cloud-infrastructure/cluster/main-cluster.bicep
- cloud-infrastructure/modules/user-assigned-managed-identity.bicep
Update Bicep infrastructure to ensure the Account Management managed identity is granted the Key Vault Crypto Officer role, allowing it to sign access tokens.
> Update Bicep infrastructure to grant Account Management sign permissions in Key Vault Access

- cloud-infrastructure/cluster/main-cluster.bicep
- cloud-infrastructure/modules/virtual-network.bicep
Enable the specification of IP address ranges within the Bicep module file for a virtual network. This change allows the module to be used multiple times with different IP ranges. Without this enhancement, multiple virtual networks using the same IP range cannot be connected via peering.
- Allow specifying IP address range for virtual network
> Allow specifying IP address range for virtual network

- application/account-management/Core/Authentication/Commands/CompleteLogin.cs
- application/account-management/Core/Authentication/Commands/Logout.cs
- application/account-management/Core/Authentication/Commands/StartLogin.cs
- application/account-management/Core/Authentication/Domain/Login.cs
- application/account-management/Core/Signups/Commands/StartSignup.cs
- application/account-management/Core/Signups/Domain/Signup.cs
- application/account-management/Core/Signups/Queries/IsSubdomainFree.cs
- application/account-management/Core/Tenants/Commands/DeleteTenant.cs
- application/account-management/Core/Tenants/Queries/GetTenant.cs
- application/account-management/Core/Users/Commands/ChangeUserRole.cs
- application/account-management/Core/Users/Commands/DeleteUser.cs
- application/account-management/Core/Users/Commands/RemoveAvatar.cs
- application/account-management/Core/Users/Domain/UserTypes.cs
- application/account-management/Core/Users/Queries/GetUser.cs
- application/account-management/Core/Users/Queries/GetUsers.cs
- application/shared-kernel/SharedKernel/Endpoints/IEndpoints.cs
- application/shared-kernel/SharedKernel/Endpoints/TrackEndpoints.cs
- application/shared-kernel/SharedKernel/ExternalAnnotations/FluentValidation.xml
- application/shared-kernel/SharedKernel/ExternalAnnotations/MediatR.xml
- application/shared-kernel/SharedKernel/ExternalAnnotations/README.md
Mark `MediatR.IRequestHandler`, `FluentValidation.AbstractValidator`, and `SharedKernel.IEndpoints` as being used implicitly, resolving incorrect warnings about unused code like the one shown in the screenshot:
The change is implemented using JetBrains External Annotations, which are XML files stored in an ExternalAnnotations folder alongside the solution or project file. These annotations prevent misleading warnings in JetBrains IDEs. For more details, refer to [Rider documentation](https://www.jetbrains.com/help/rider/Code_Analysis__External_Annotations.html) and [JetBrains’ standard annotations](https://github.com/JetBrains/ExternalAnnotations).
Additionally, all Request and Command classes have been marked with the [PublicAPI] attribute to avoid similar warnings about unused code.
> Add external annotations to mark implicitly created types as used

- application/shared-kernel/SharedKernel/Behaviors/ConcurrentCommandCounter.cs
In rare conditions, the code allows the unit of work and/or the events to not be published at the end of the request.
Multiple threads can decrement the concurrent counter at the same time using Interlocked to ensure atomicity of the operation. However, when reading the data, Interlocked was not used, leading to potential race conditions.
Note: I am aware there is no concurrency involved in here. But the counter itself has partial support for thread safety, and this is addressed in the PR.
> Make ConcurrentCommandCounter thread safe

- application/AppGateway/Filters/ClusterDestinationConfigFilter.cs
- application/AppGateway/appsettings.json
- application/account-management/Api/Properties/launchSettings.json
- application/account-management/Tests/EndpointBaseTest.cs
- application/account-management/WebApp/shared/components/AvatarButton.tsx
- application/back-office/Api/Properties/launchSettings.json
- application/back-office/Tests/EndpointBaseTest.cs
- application/shared-webapp/build/plugin/MFPlugin.ts
Update YARP configuration to fix the issue where federated modules were not loading in production. All communication for static files on localhost is now routed through the YARP gateway, rather than directly to the self-contained systems, which run as separate processes on localhost for hot reloading.
Added new YARP routes for static files and changed the loading of federated modules to always use /[self-contained system]/remoteEntry.js for both localhost and production. The federated module configuration has been simplified, as the same approach is now used for both environments.
> Fix federated module loading on production and align localhost to fetch static files through YARP

- application/account-management/Core/Authentication/Commands/CompleteLogin.cs
- application/account-management/Core/Authentication/Commands/StartLogin.cs
- application/account-management/Core/Authentication/Services/AuthenticationTokenGenerator.cs
- application/account-management/Core/Authentication/Services/AuthenticationTokenService.cs
- application/account-management/Core/Users/Commands/CreateUser.cs
- application/account-management/Core/Users/Domain/UserRepository.cs
- application/shared-kernel/SharedKernel/EntityFramework/SharedKernelDbContext.cs
Fix issue with refreshing tokens after introducing tenant-scoped query filters. The `IExecutionContext` was missing the `TenantId` during access token refresh because the RefreshToken JWT did not include the `TenantId`. By adding the `TenantId` to the RefreshToken, the refresh process now correctly assigns a valid `TenantId`, allowing `GetUserByIdAsync` to function as expected.
Additionally, all repository methods using `.IgnoreQueryFilters()` have been renamed to `XxxUnfilteredAsync()` for clarity, and documentation has been added to these methods.
> Fix tenant id issue in access token refresh and rename unfiltered repository methods

- application/account-management/Core/Users/Commands/CreateUser.cs
- application/account-management/Tests/DatabaseSeeder.cs
- application/account-management/Tests/Signups/StartSignupTests.cs
- application/account-management/Tests/Tenants/GetTenantTests.cs
- application/account-management/Tests/Users/CreateUserTests.cs
- application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
- application/shared-kernel/SharedKernel/Domain/TenantId.cs
Fixes a bug where TenantId containing a hyphen caused model binding to fail. Updates tests to use `tenant-1` as seed data and add coverage for hyphenated TenantId. Changes `CreateUserCommand.TenantId` from a string to a `TenantId` type for consistency.
> Fix model binding issue when TenantId contains a hyphen

- application/shared-kernel/SharedKernel/ExecutionContext/HttpExecutionContext.cs
This fix resolves a bug where the `TenantId` in `HttpExecutionContext` would always be null if `UserInfo` was the first property accessed. The issue stemmed from internal logic in `HttpExecutionContext`, which only set the `TenantId` when `UserInfo` was accessed first. The fix ensures that both `UserInfo` and `TenantId` are correctly set, regardless of which property is accessed first on `HttpExecutionContext`.
- Fix tenantId is null bug when UserInfo has not been accessed
> Fix tenantId is null bug when UserInfo has not been accessed

- application/shared-kernel/SharedKernel/SinglePageApp/SinglePageAppConfiguration.cs
This PR resolves an issue where the backend experienced delays when serving the `index.html` file of a SinglePageApp. The delay occurred because the backend was waiting for the `index.html` file to regenerate before serving it, ensuring the file included references to newly generated JavaScript bundles. The logic now checks for updates using the `LastWriteTime` to confirm when the new file is ready.
The delay primarily affected Windows due to differences in how file timestamps are handled across operating systems. On Windows, the `CreationTime` doesn't update when a file is modified, unlike on MacOS where both `CreationTime` and `LastWriteTime` are updated. The fix ensures consistent behavior across platforms by relying on the `LastWriteTime`.
- Fix issue when waiting extensively on …
> Fix delay issue in serving SinglePageApp index.html on Windows

- application/account-management/WebApp/shared/translations/locale/da-DK.po
- developer-cli/Commands/DevCommand.cs
- developer-cli/Commands/TranslateCommand.cs
- developer-cli/DeveloperCli.csproj
- developer-cli/Utilities/SecretHelper.cs
Replace the Ollama LLM model running locally on Docker with the OpenAI GPT-4o model to improve translation speed and quality.
Other changes include:
- Re-translate back to English to confirm the accuracy of translations.
- Add an option to provide additional context to the translator.
- Add an option to use a custom translation.
- Fix an issue where translations would appear on a new line in the `.po` file.
- Maintain translations in their original position in the `.po` file for easier review.
- Prompt the user for an OpenAI key.
> Do a reverse translation to confirm the accuracy of translated text

- application/shared-kernel/SharedKernel/SharedInfrastructureConfiguration.cs
With the upgrade to a newer version of .NET, a bug was exposed in the `PlatformPlatform` code, specifically affecting the avatars blob storage setup. The issue surfaced because the BlobStorage account was registered as a normal service rather than a keyed service in the local environment configuration (when not running in Azure). While this was not a problem in the previous .NET version, the upgrade made the bug evident. This PR resolves the issue by registering the BlobStorage account as a keyed service in the local environment, aligning the behavior with the intended configuration and fixing the bug in `PlatformPlatform`.
> Fix bug with BlobStorage in local environment not using KeyedService

- application/shared-kernel/SharedKernel/Authentication/UserInfo.cs
- application/shared-kernel/SharedKernel/ExecutionContext/HttpExecutionContext.cs
Fix blank page being served where browser language settings like `en` or `en-UK` were uncritically used as the HTML Document language, even if translations weren't available for that exact locale. Now, the logic checks if a translation exists for the base language code (e.g., `en`), and if none is found, it falls back to `en-US`. This ensures that the document always has a valid locale that corresponds to available translations.
> Fix blank web page when locale is invalid by improving language fallback logic

- application/AppGateway/ApiAggregation/ApiAggregationEndpoints.cs
- application/AppGateway/ApiAggregation/ApiAggregationService.cs
- application/AppGateway/ApiAggregation/ApiExplorerRouteFilter.cs
- application/AppGateway/AppGateway.csproj
- application/AppGateway/Program.cs
- application/Directory.Packages.props
- application/shared-kernel/SharedKernel/ApiDependencyConfiguration.cs
Aggregate OpenAPI specifications for all self-contained systems into a unified UI. Previously, each system had its own SwaggerUI, accessible only on internal endpoints and not in production. The YARP AppGateway now fetches `OpenAPI.json` from each self-contained system and combines them into a single OpenAPI contract.
With the upcoming removal of Swagger in .NET 9, the UI for the aggregated API uses Scalar, an open-source alternative (https://github.com/scalar/scalar), accessible at `/openapi/v1`.
Because self-contained systems can be deployed independently of the AppGateway, the aggregation cannot occur during AppGateway startup. Instead, the OpenAPI contracts are fetched dynamically from each system. For performance optimization, the contract is cached for 5 minutes using standard .NET …
> Aggregate OpenAPI for all self-contained systems using Scalar

- application/AppGateway/ApiAggregation/ApiAggregationEndpoints.cs
- application/AppGateway/ApiAggregation/ApiAggregationService.cs
Follow-up to the recent change for aggregating OpenAPI specifications. The aggregation was not working correctly in production because URLs for the self-contained systems were not fetched properly from the YARP configuration, leading to empty API contracts.
To resolve this, the list of YARP clusters to include in the aggregated OpenAPI specification is now hardcoded, rather than relying on conventions for clusters with an `-api` postfix. This adjustment provides more flexibility in configuring the setup.
> Change OpenAPI aggregation to use hardcoded clusters to add flexibility and resolve issue in Azure

- application/account-management/Api/Endpoints/TenantEndpoints.cs
- application/account-management/Api/Endpoints/UserEndpoints.cs
- application/account-management/Core/Tenants/Queries/GetTenant.cs
- application/account-management/Core/Users/Queries/GetUser.cs
- application/account-management/Core/Users/Queries/GetUsers.cs
- application/account-management/Tests/Users/GetUsersTests.cs
- application/account-management/WebApp/shared/components/userModals/UserProfileModal.tsx
- application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
- application/shared-kernel/SharedKernel/Endpoints/TrackEndpoints.cs
Rename all DTOs to use the `Response` or `Request` postfix instead of `DTO`. This change standardizes naming conventions across the project, making it clearer whether a data structure represents an incoming request or an outgoing response. Additionally, this update avoids using the `DTO` term in the frontend code.
> Change DTOs to use Response/Request postfix instead of DTO

- application/account-management/WebApp/routes/__root.tsx
- application/account-management/WebApp/shared/components/AvatarButton.tsx
Move the check for missing user profile information to the Avatar Button federated module, ensuring that the User Profile dialog is displayed whenever required information is missing, regardless of the self-contained system the user is attempting to access. This change centralizes the profile completeness check, so any self-contained system that includes the Avatar Button module will automatically prompt users to complete their profile if needed.
> Show the User Profile dialog when any information is missing

- application/shared-kernel/SharedKernel/Database/DatabaseMigrationService.cs
Improve deployment reliability by ensuring that GitHub deployments to Azure fail if database migrations do not complete successfully. Previously, if a database migration failed, it only logged an error without impacting the deployment status. With this change, an exception is now thrown if a migration fails. This ensures that the GitHub Action deploying to Azure will fail, as it waits for the migration Worker to start up successfully before proceeding.
> Ensure GitHub deployment fails if database migrations time out

- application/AppHost/SslCertificateManager.cs
- application/shared-kernel/SharedKernel/ApiDependencyConfiguration.cs
- application/shared-kernel/SharedKernel/SharedDependencyConfiguration.cs
- application/shared-kernel/SharedKernel/SinglePageApp/SinglePageAppConfiguration.cs
- application/shared-kernel/SharedKernel/SinglePageApp/SinglePageAppFallbackExtensions.cs
Enable self-contained systems to support multiple projects with repositories and MediatR commands and queries by updating `ApiDependencyConfiguration` and `SharedDependencyConfiguration` to accept `params Assembly[] assemblies`. This allows commands and queries from multiple projects to be seamlessly integrated within a single self-contained system.
Add support for injecting additional environment variables into the single-page application, enhancing customization and flexibility.
Update the Content Security Policy (CSP) to allow `data:` and `blob:` URLs, facilitating inline images and file uploads within the application.
Lastly, enhance `SslCertificateManager` in Aspire AppHost to support self-signed certificates for multiple domains, improving certificate management in development and …
> Enhance support for multiple projects, environment variables, and CSP in self-contained systems

- application/account-management/Core/Database/DatabaseMigrations.cs
- application/account-management/Core/DependencyConfiguration.cs
- application/account-management/Core/Features/Authentication/Commands/CompleteLogin.cs
- application/account-management/Core/Features/Users/Avatars/AvatarUpdater.cs
- application/account-management/Core/Features/Users/Commands/CreateUser.cs
- application/account-management/Core/Features/Users/Commands/UpdateAvatar.cs
- application/account-management/Core/Features/Users/Domain/User.cs
- application/account-management/Core/Integrations/Gravatar/GravatarClient.cs
- application/account-management/Core/TelemetryEvents/TelemetryEvents.cs
- application/account-management/Tests/Authentication/CompleteLoginTests.cs
- application/account-management/Tests/DatabaseSeeder.cs
Add logic to download Gravatar images to blob storage, addressing browser console warnings about "Tracking Prevention blocked" when loading assets from external sites. The Gravatar image is downloaded when a user is created and refreshed each time the user logs in.
To support this functionality, the logic for saving an avatar to blob storage has been refactored into a new, shared `AvatarUpdater` class. Additionally, a new `GravatarClient` has been created in a new `Infrastructure` namespace. This update demonstrates a method for extracting shared logic within a vertical-sliced architecture while adhering to the single responsibility principle.
> Download gravatar images to blob storage to prevent browser warnings

- application/account-management/Core/Features/Authentication/Commands/CompleteLogin.cs
- application/account-management/Core/Features/Users/Avatars/AvatarUpdater.cs
- application/account-management/Core/Features/Users/Commands/CreateUser.cs
- application/account-management/Core/Features/Users/Commands/UpdateAvatar.cs
- application/account-management/Core/Integrations/Gravatar/GravatarClient.cs
- application/account-management/WebApp/shared/components/userModals/UserProfileModal.tsx
- application/account-management/WebApp/shared/translations/locale/da-DK.po
- application/account-management/WebApp/shared/translations/locale/en-US.po
- application/account-management/WebApp/shared/translations/locale/nl-NL.po
- application/shared-kernel/SharedKernel/Persistence/RepositoryBase.cs
- application/shared-webapp/infrastructure/api/PlatformApiClient.ts
Introduce functionality allowing users to change their avatars, with an option to upload a new avatar when saving their User Profile. Supported formats include JPEG, PNG, GIF, and WebP, providing users with flexibility in avatar choices.
Address several issues with Gravatar handling: users without Gravatars now correctly avoid default Gravatar images, and the system gracefully handles timeouts when fetching Gravatars, returning a `Not Found` status if an image is missing. Additionally, the user profile no longer displays a broken image for users without an avatar.
The recently introduced `GravatarClient` has been decoupled from the Users feature, enabling more modular use across the application.
To streamline avatar uploads, a strongly-typed `api.uploadFile` method has been implemented, …
> Add support for changing and uploading avatars

- application/account-management/Core/Features/Authentication/Commands/CompleteLogin.cs
- application/account-management/Core/Features/Authentication/Commands/Logout.cs
- application/account-management/Core/Features/Authentication/Commands/RefreshAuthenticationTokens.cs
- application/account-management/Core/Features/Signups/Commands/CompleteSignup.cs
- application/account-management/Core/Features/Tenants/Commands/UpdateTenant.cs
- application/account-management/Core/Features/Users/Commands/ChangeLocale.cs
- application/account-management/Core/Features/Users/Commands/ChangeUserRole.cs
- application/account-management/Core/Features/Users/Commands/CreateUser.cs
- application/account-management/Core/Features/Users/Commands/DeleteUser.cs
- application/account-management/Core/Features/Users/Commands/InviteUser.cs
- application/account-management/Core/TelemetryEvents/TelemetryEvents.cs
- application/account-management/Tests/Authentication/CompleteLoginTests.cs
- application/account-management/Tests/Authentication/StartLoginTests.cs
- application/account-management/Tests/Signups/CompleteSignupTests.cs
- application/account-management/Tests/Signups/StartSignupTests.cs
- application/account-management/Tests/Tenants/DeleteTenantTests.cs
- application/account-management/Tests/Tenants/UpdateTenantTests.cs
- application/account-management/Tests/Users/InviteUserTests.cs
- application/shared-kernel/SharedKernel/Behaviors/PublishTelemetryEventsPipelineBehavior.cs
- application/shared-kernel/SharedKernel/TelemetryEvents/TelemetryEventsCollector.cs
Update Application Insights tracking for custom events by adding user-specific properties such as `UserId`, `TenantId`, `Local`, `UserRole`, and `IsAuthenticated`. These properties are prefixed with `user_` (e.g., `user_Local`, `user_IsAuthenticated`) by convention, ensuring consistency and enhancing the clarity of user-related data in telemetry.
The creation of telemetry events has also been simplified to reduce errors. Event names are now derived using `GetType().Name` instead of `nameof(EventName)`, avoiding issues from copy-pasting, such as when `UserUpdated` events were incorrectly named as `UserCreated`.
Additionally, telemetry tracking is now updated to collect `UserId` and `TenantId` specifically in unauthenticated login flows and admin role changes, ensuring precise event data …
> Enhance Application Insights tracking with user-specific properties and simplified event naming

- application/AppGateway/Program.cs
- application/account-management/Core/TelemetryEvents/TelemetryEvents.cs
- application/account-management/Tests/Authentication/CompleteLoginTests.cs
- application/account-management/Tests/Authentication/StartLoginTests.cs
- application/account-management/Tests/Signups/StartSignupTests.cs
- application/shared-kernel/SharedKernel/ApiDependencyConfiguration.cs
- application/shared-kernel/SharedKernel/Behaviors/PublishTelemetryEventsPipelineBehavior.cs
- application/shared-kernel/SharedKernel/ExecutionContext/BackgroundWorkerExecutionContext.cs
- application/shared-kernel/SharedKernel/ExecutionContext/HttpExecutionContext.cs
- application/shared-kernel/SharedKernel/ExecutionContext/IExecutionContext.cs
- application/shared-kernel/SharedKernel/SharedInfrastructureConfiguration.cs
- application/shared-kernel/SharedKernel/SinglePageApp/SinglePageAppConfiguration.cs
- application/shared-kernel/SharedKernel/Telemetry/ApplicationInsightsTelemetryInitializer.cs
- application/shared-kernel/SharedKernel/Telemetry/OpenTelemetryEnricher.cs
- application/shared-kernel/SharedKernel/Telemetry/TelemetryContextMiddleware.cs
- application/shared-kernel/SharedKernel/TelemetryEvents/TelemetryEventsCollector.cs
- application/shared-webapp/infrastructure/applicationInsights/ApplicationInsightsProvider.tsx
Enhance telemetry tracking for better accuracy and consistency across the YARP AppGateway, Application Insights, and OpenTelemetry.
The YARP AppGateway has been updated to correctly forward the client’s IP address, allowing Application Insights telemetry (events and page views) and OpenTelemetry requests to track the correct geo-location data, including city and country.
When saving OpenTelemetry request data to Application Insights, the built-in authenticated user ID is now set. Since OpenTelemetry cannot set the built-in Application Insights properties for `UserID` and `TenantId`, these are added as custom properties across PageViews and CustomEvents, ensuring that all telemetry data consistently includes these values.
Custom property naming has been standardized to align with …
> Enhance telemetry tracking with geo data and align property naming with OpenTelemetry standards

- application/account-management/Core/Database/DatabaseMigrations.cs
Switch ID columns from `char(xx)` to `varchar(32)` to eliminate issues with blank spaces when saving strongly typed IDs like `usr_01JA5QZTCP69B5T916WF1TSQG8` (30 characters). Developers often forget to adjust column sizes when copying migration code, causing unnecessary padding in `char` columns. Defaulting to `varchar(32)` provides flexibility for IDs up to 32 characters without blank space issues and supports strongly typed IDs with up to 5-character prefixes. The `signup` ID column remains `varchar(33)` due to the lack of a suitable 5-character prefix for "signup."
Update all Entity Framework database migrations to replace `char(xx)` with `varchar(32)` for ID columns. Note that this is a non-breaking change, as the original EF Core migration is updated instead of creating a new one, …
> Switch ID columns to varchar(32) to prevent padding issues

- README.md
- application/AppGateway/Properties/launchSettings.json
- application/AppHost/Program.cs
- application/shared-kernel/SharedKernel/SinglePageApp/SinglePageAppConfiguration.cs
- application/shared-webapp/build/plugin/DevelopmentServerPlugin.ts
Aspire is now configured to keep SQL Server alive between debug sessions using the new Aspire 9 `.WithLifetime(ContainerLifetime.Persistent)`, significantly improving secondary startup.
Unfortunately, Aspire does not seem to release ports immediately upon shutdown, requiring 10 seconds to a minute before the AppHost can restart. To mitigate this issue temporarily, logic has been added to kill any Developer Control Pane processes (`dcpctrl`) from previous sessions when starting the AppHost, preventing conflicts and strange errors. For more details, see this issue: https://github.com/dotnet/aspire/issues/6704.
The SPA generation and `index.html` caching strategy have been updated to align with the new Aspire startup behavior during debugging.
The AppGateway no longer launches automatically …
> Follow-up improvements to Aspire 9 debugging and configuration

- .github/workflows/account-management.yml
- .github/workflows/app-gateway.yml
- .github/workflows/back-office.yml
- application/AppGateway/AppGateway.csproj
- application/AppGateway/Dockerfile
- application/AppHost/AppHost.csproj
- application/AppHost/SslCertificateManager.cs
- application/Directory.Packages.props
- application/account-management/Api/AccountManagement.Api.csproj
- application/account-management/Api/Dockerfile
- application/account-management/Core/AccountManagement.csproj
- application/account-management/Tests/AccountManagement.Tests.csproj
- application/account-management/WebApp/AccountManagement.WebApp.esproj
- application/account-management/Workers/AccountManagement.Workers.csproj
- application/account-management/Workers/Dockerfile
- application/back-office/Api/BackOffice.Api.csproj
- application/back-office/Api/Dockerfile
- application/back-office/Core/BackOffice.csproj
- application/back-office/Tests/BackOffice.Tests.csproj
- application/back-office/WebApp/BackOffice.WebApp.esproj
- application/back-office/Workers/BackOffice.Workers.csproj
- application/back-office/Workers/Dockerfile
- application/global.json
- application/shared-kernel/SharedKernel/Configuration/SharedInfrastructureConfiguration.cs
- application/shared-kernel/SharedKernel/SharedKernel.csproj
- application/shared-kernel/Tests/SharedKernel.Tests.csproj
- application/shared-webapp/SharedKernel.WebApp.esproj
Upgrade the project from .NET 8 to .NET 9, bringing improved features and simplifying workflows. All .NET projects and the global `global.json` have been updated to target .NET 9. NuGet packages have also been upgraded to their .NET 9-compatible versions, except for Entity Framework, which remains on the older version due to test failures caused by multiple service registrations.
The Docker image has been updated to use `mcr.microsoft.com/dotnet/aspnet:9.0-alpine`, and GitHub Actions have been upgraded to use .NET 9. Additionally, the Aspire workload installation step has been removed from GitHub Actions, as it is no longer needed.
The `SslCertificateManager` has been refactored and simplified with .NET 9’s new cross-platform `X509CertificateLoader.LoadPkcs12FromFile` method, replacing …
> Upgrade to .NET 9

- application/account-management/Core/Features/Tenants/Commands/DeleteTenant.cs
- application/account-management/Core/Features/Users/Commands/ChangeUserRole.cs
- application/account-management/Core/Features/Users/Commands/DeleteUser.cs
- application/account-management/Tests/Tenants/DeleteTenantTests.cs
- application/account-management/Tests/Users/DeleteUserTests.cs
- application/account-management/WebApp/routes/admin/users/-components/UserTable.tsx
- application/account-management/WebApp/shared/translations/locale/da-DK.po
- application/account-management/WebApp/shared/translations/locale/en-US.po
- application/account-management/WebApp/shared/translations/locale/nl-NL.po
- application/shared-webapp/ui/components/Modal.tsx
Introduce the ability to delete a user, with a confirmation dialog in the UI. The dialog displays the user's name or email (if the name is not provided) when confirming the deletion.
The `Modal` component has been updated to support disabling background blur, which is not useful when showing confirmation box.
On the server side, logic has been added to allow only owners to delete users or change roles. Owners cannot delete or modify their own roles.
The delete option has been disabled in the UI by default.
> Add option to delete a user with confirmation and enhanced permissions

- application/account-management/Api/AccountManagement.Api.csproj
- application/back-office/Api/BackOffice.Api.csproj
Resolve the issue with OpenAPI generation failing in .NET 9 due to the `<OpenApiDocumentsDirectory>` using forward slashes instead of backslashes. The configuration now uses backslashes to ensure compatibility with the new .NET 9 requirements.
Fix the issue with OpenAPI generation failing in .NET 9 with the error `Missing required option '--project'`. This was caused by `<OpenApiDocumentsDirectory>` using forward slashes instead of backslashes.
Update all paths in `.csproj` files to use backslash for compatibility with Windows.
> Fix OpenAPI generation issue after .NET 9 upgrade

- application/AppHost/Program.cs
Configure the Azure Blob Storage emulator and the Mailpit mail server to remain running between Aspire sessions using the new `.WithLifetime(ContainerLifetime.Persistent)` feature in Aspire 9. This reduces startup time during debugging by keeping these services alive across sessions.
> Persist Blob Storage emulator and Mail Server across Aspire sessions

- application/AppGateway/appsettings.json
Fix issues with YARP Gateway routes for `/api/account-management` and `/api/back-office`. The route for the BackOffice API was not correctly redirecting API traffic, causing requests to fail. Additionally, the Account Management API route was misconfigured but appeared to work because it was inadvertently using the SPA YARP route.
Both routes have been updated to ensure proper redirection and alignment with their respective APIs.
Update YARP configuration for self-contained system to map API endpoints correctly.
> Fix YARP Gateway routes for Account Management and BackOffice APIs

- developer-cli/Commands/CodeCoverageCommand.cs
- developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
- developer-cli/Commands/InstallCommand.cs
- developer-cli/Commands/PullPlatformPlatformChangesCommand.cs
- developer-cli/Commands/TranslateCommand.cs
- developer-cli/Commands/UninstallCommand.cs
- developer-cli/Installation/ChangeDetection.cs
- developer-cli/Installation/Configuration.cs
- developer-cli/Program.cs
- developer-cli/Utilities/GitHelper.cs
- developer-cli/Utilities/GithubHelper.cs
- developer-cli/Utilities/SolutionHelper.cs
Update the PlatformPlatform .NET CLI to address issues encountered when running multiple CLIs side by side. These changes improve configuration management, naming conventions, and code quality for better usability and maintainability.
Key updates include:
- Use the Git source code folder root name as the CLI name, enhancing support for running multiple CLIs side by side.
- Add detection for existing CLI installations when setting up aliases to avoid conflicts.
- Refactor `GetSourceCodeFolder` to a static `SourceCodeFolder` property and introduce `ApplicationFolder` and `CliFolder` properties in `Configuration.GitFolder` for more structured folder management.
- Rename `SourceCodeFolder` in CLI .json to `CliSourceCodeFolder`.
- Ensure it's not possible to change the path in …
> Update PlatformPlatform .NET CLI for improved side-by-side project support

- application/account-management/Core/Configuration.cs
- application/shared-kernel/SharedKernel/Configuration/SharedDependencyConfiguration.cs
Move the registration of authentication-related services to the Shared Kernel to allow self-contained systems to create authenticated HTTP clients in base tests. The following services are now registered in the Shared Kernel:
- `IPasswordHasher<object>`
- `OneTimePasswordHelper`
- `RefreshTokenGenerator`
- `AccessTokenGenerator`
- `AuthenticationTokenService`
Additionally, `AddEmailSignatureClient` has been renamed to `AddEmailClient` for improved clarity and consistency.
> Move authentication token registration to Shared Kernel

- application/account-management/WebApp/routes/admin/users/-components/UserTable.tsx
- application/account-management/WebApp/shared/lib/api/userRole.ts
- application/account-management/WebApp/shared/translations/locale/da-DK.po
- application/account-management/WebApp/shared/translations/locale/en-US.po
- application/account-management/WebApp/shared/translations/locale/nl-NL.po
- application/shared-webapp/ui/components/AlertDialog.tsx
- application/shared-webapp/ui/components/Heading.tsx
Enable owners to change the roles of other users, such as switching from Member to Admin or Owner. This functionality is implemented in a new modal dialog with a dropdown for selecting roles. A new `UserRole.ts` file has been introduced to support translations of all options in the `UserRole` enum.
The `AlertDialog` has been updated to support configurations without action buttons (e.g., OK and Cancel), as selecting a role in the dropdown automatically submits the change. Additionally, a new size option for the header has been added to allow for smaller headings.
To ensure tenant integrity, it is not possible for users to change their own role, preventing scenarios where a tenant could be left without an owner. This is a UI change only, as there are other ways to lose access to the sole …
> Enable owners to change user roles

- application/AppHost/SslCertificateManager.cs
When running on Windows, the `dotnet dev-certs` command fails to create the SSL certificate when the `.aspnet/dev-certs/https/` folder doesn't exist.
This change ensures the full path is created before executing the `dotnet dev-certs`.
> Ensure certificate directory exists before creating it

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/validate-pull-request-conventions.yml
Fix a bug in the GitHub Action for Git convention validation when the pull requestX originates from a forked repository. The logic for checking commit history has been updated to handle this scenario correctly.
Enhance error messages to provide clearer guidance when convention validation fails, improving the developer experience. 
Introduce new validation rules for pull requestX:
- Disallow the use of the phrase "pull requestX" in the description.
- Prevent titles in the format `Pp ###` followed by a title derived directly from the branch name.
Finally, update the pull requestX template to no longer require confirmation that a label is present
> Fix Git convention validation for forked repositories and enhance rules

- developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
- developer-cli/Installation/Prerequisite.cs
Fix an issue in the Developer CLI where missing prerequisites (e.g., NodeJS) resulted in the CLI exiting without any error message. The CLI now correctly identifies missing prerequisites and displays an error such as: `NodeJS of minimum version 25.3.0 should be installed.`
Additionally, a validation has been added to the `configure-continuous-deployments` CLI command to ensure that the selected Azure subscriptions for staging and production belong to the same tenant, preventing configuration errors.
> Improve Developer CLI error handling for prerequisites and Azure subscription validation

- application/account-management/Api/Endpoints/AuthenticationEndpoints.cs
- application/account-management/Api/Endpoints/SignupEndpoints.cs
- application/account-management/Core/Features/Authentication/Commands/ResendLoginCode.cs
- application/account-management/Core/Features/Authentication/Domain/Login.cs
- application/account-management/Core/Features/Signups/Commands/ResendSignupCode.cs
- application/account-management/Core/Features/Signups/Commands/StartSignup.cs
- application/account-management/Core/Features/Signups/Domain/Signup.cs
- application/account-management/Core/Features/TelemetryEvents.cs
- application/account-management/Tests/Signups/StartSignupTests.cs
- application/account-management/WebApp/routes/login/verify.tsx
- application/account-management/WebApp/routes/signup/index.tsx
- application/account-management/WebApp/routes/signup/verify.tsx
- application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
Introduce the ability to resend one-time passwords during the signup and login processes. To achieve this, new `signup/resend-code` and `login/resend-code` API endpoints have been implemented, along with `ResendSignupCodeCommand` and `ResendLoginCodeCommand`. The Signup and Login aggregates have been updated with a new `UpdateVerificationCode` method to support this functionality.
The link to resend the login code has been moved below the Verify button for simplicity. When a code is resent, the verification timeout is extended by an additional 5 minutes. A 30-second cooldown between sending verification codes has also been introduced to prevent abuse.
> Resending the one time password for login and signup does

- application/AppHost/ConfigurationExtensions.cs
- application/AppHost/Program.cs
- application/account-management/Api/Properties/launchSettings.json
- application/back-office/Api/Properties/launchSettings.json
- application/shared-kernel/SharedKernel/SinglePageApp/SinglePageAppConfiguration.cs
Up to now, it has been hard to test the web app on other devices, as the code was hard coded to the web app being at `localhost:9000`, thus allowing only tests from the computer where development takes place. With this change, `PUBLIC_URL` can be configured for the AppGateway to allow serving the app on any address, allowing testing on multiple devices.
This allows using a reverse proxy tool, such as ngrok or Tailscale, to serve the local web app on address of your choice. With Tailscale you can use `tailscale serve` to serve on your Tailscale network, or `tailscale funnel` to serve on the internet:
```
➜  ~ tailscale serve https://localhost:9000
Available within your tailnet:
https://your-computer-name.tail492ec.ts.net/
|-- proxy https://localhost:9000
```
Tailscale assigns a unique …
> Allow serving local environment from any address

- .github/workflows/validate-pull-request-conventions.yml
As a follow-up to the previous change, extend the GitHub Action for Git convention validation to allow commit messages with multiple sentences if they are cherry-picked from PlatformPlatform and start with "PlatformPlatform PR".
> Allow multiple sentences in commit messages for PlatformPlatform cherry-picked commits

- application/account-management/Api/Endpoints/UserEndpoints.cs
- application/account-management/Core/Features/Signups/Queries/IsSubdomainFree.cs
- application/account-management/Core/Features/Tenants/Queries/GetTenant.cs
- application/account-management/Core/Features/Users/Domain/UserRepository.cs
- application/account-management/Core/Features/Users/Queries/GetUser.cs
- application/account-management/Core/Features/Users/Queries/GetUserSummary.cs
- application/account-management/WebApp/routes/admin/index.tsx
- application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
- application/account-management/WebApp/shared/translations/locale/da-DK.po
- application/account-management/WebApp/shared/translations/locale/en-US.po
- application/account-management/WebApp/shared/translations/locale/nl-NL.po
- application/shared-webapp/infrastructure/auth/constants.ts
Update the Admin Dashboard to display accurate metric cards for Total Users, Active Users, and Invited Users. A new `GetUserSummary` query, endpoint, and repository method have been created to retrieve these metrics.
Additionally, parameter names in query handlers have been standardized for consistency across the codebase.
> Add user summary metrics to Admin Dashboard

- .github/workflows/_deploy-container.yml
- .github/workflows/_deploy-infrastructure.yml
- .github/workflows/account-management.yml
- .github/workflows/app-gateway.yml
- .github/workflows/back-office.yml
- .github/workflows/validate-pull-request-conventions.yml
- cloud-infrastructure/cluster/deploy-cluster.sh
- cloud-infrastructure/cluster/main-cluster.bicep
- cloud-infrastructure/environment/deploy-environment.sh
Upgrade all GitHub runners to the latest stable version, Ubuntu 24.04, for improved stability and predictability. Previously, runners used `ubuntu:latest`, which posed risks due to breaking changes between updates.
In Ubuntu 24.04, the classic Microsoft `sqlcmd` (ODBC) is no longer installed by default, so the logic to uninstall it has been removed. The new `sqlcmd` (Go) is still installed, but it relies on the older package source from Ubuntu 22.04 (`https://packages.microsoft.com/config/ubuntu/22.04/prod.list`) due to the lack of an updated package for 24.04. For more details, see: https://github.com/microsoft/go-sqlcmd/issues/532.
Additionally, Bicep output parsing has been improved. JSON extraction now removes warnings about unneeded dependencies, preventing failures in detecting …
> Upgrade GitHub runners to Ubuntu 24.04 and improve Bicep output parsing

- application/account-management/WebApp/routes/login/index.tsx
- application/account-management/WebApp/routes/login/verify.tsx
Improve the login flow by redirecting users to the page they were attempting to access before being prompted to log in. For example, if a user tries to visit `/admin/users` without being logged in, they are redirected to the login page with `?returnPath=%2Fadmin%2Fusers` in the URL. After logging in, the user is redirected back to `/admin/users`.
To ensure security, redirects to different domains are explicitly blocked. Only `returnPath` values starting with `/` are allowed, preventing open redirect vulnerabilities.
> Redirect users to the intended page after successful login

- application/shared-webapp/ui/components/SideMenu.tsx
- application/shared-webapp/ui/hooks/useLocalStorage.ts
Add logic to save the collapsed state of the side menu in the admin center to ensure it retains the same state when reloading the browser.
The `useLocalStorage` hook has been introduced to enable seamless saving of state to the browser's local storage.
> Persist side menu state in the admin center

- application/account-management/Core/Features/Signups/Commands/CompleteSignup.cs
- application/account-management/Core/Features/Tenants/Commands/CreateTenant.cs
- application/account-management/Core/Features/Users/Commands/CreateUser.cs
- application/account-management/Core/Features/Users/Commands/InviteUser.cs
- application/account-management/Core/Features/Users/Domain/User.cs
- application/account-management/Tests/DatabaseSeeder.cs
- application/account-management/Tests/Users/CreateUserTests.cs
- application/account-management/WebApp/routes/__root.tsx
- application/account-management/WebApp/routes/signup/verify.tsx
- application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
- application/back-office/WebApp/routes/__root.tsx
- application/shared-webapp/infrastructure/translations/LocaleSwitcher.tsx
- application/shared-webapp/infrastructure/translations/constants.ts
- application/shared-webapp/infrastructure/translations/useInitializeLocale.ts
Ensure that a user's language selection is saved in the browser, so the same language is used when they sign out or later return. If an anonymous user changes the language while signing up, the created user will have the selected language set. Maintain the logic that sets the language to match the user's profile language upon signing in.
This is achieved by saving the preferred language in the browser storage. Additionally, the `CreateUser` and `CompleteSignup` endpoints have been extended to include language preferences, ensuring that language settings are properly stored during user creation and signup completion.
Please update the `/WebApp/routes/__root.tsx` file to initialize the correct locale.
```typescript
import { useInitializeLocale } from …
```
> Remember to use language choice between browser sessions

- application/Directory.Packages.props
- application/account-management/Core/Database/AccountManagementDbContext.cs
- application/account-management/Core/Features/Authentication/Domain/LoginConfiguration.cs
- application/account-management/Core/Features/Signups/Domain/SignupConfiguration.cs
- application/account-management/Core/Features/Signups/Domain/SignupRepository.cs
- application/account-management/Core/Features/Tenants/Domain/TenantConfiguration.cs
- application/account-management/Core/Features/Users/Domain/UserConfiguration.cs
- application/account-management/Tests/DatabaseSeeder.cs
- application/shared-kernel/SharedKernel/EntityFramework/ModelBuilderExtensions.cs
- application/shared-kernel/SharedKernel/EntityFramework/SharedKernelDbContext.cs
- application/shared-kernel/SharedKernel/SharedKernel.csproj
Remove the need for centralized configuration in the `DbContext` when defining aggregates in a self-contained system. Previously, the `DbContext` required a `DbSet<T>` property for each aggregate (table) and explicit configuration in `OnModelCreating` for strongly typed IDs and other EF configurations like `.HasOne<T>()`, `.WithMany()`, `.OnDelete()`, `.ToJson()`, etc. Over time, this made the `DbContext` in a self-contained system big and hard to maintain
With this change, all entity configurations are moved to dedicated classes implementing `IEntityTypeConfiguration<T>`, keeping each aggregate's configuration within its vertical slice. The `SharedKernelDbContext` now automatically discovers and registers these configurations, eliminating the need for central configuration.
Additionally, …
> Simplify DbContext by extracting aggregate configuration into dedicated classes

- application/account-management/WebApp/shared/components/AvatarButton.tsx
Fix an issue where logging out from a page without user context did not immediately redirect the user. While the authentication cookies were removed, the logout was only detected after an authenticated API request failed with a `401 Unauthorized` response.
Now, the logout logic immediately redirects the browser to the `loginPath`, ensuring an instant logout experience rather than waiting for a failed request. This makes the logout process more seamless and responsive.
> Fix logout issue on pages without user context

- application/dotnet-tools.json
- application/shared-kernel/Tests/Behaviors/PublishDomainEventsPipelineBehaviorTests.cs
- application/shared-kernel/Tests/Behaviors/UnitOfWorkPipelineBehaviorTests.cs
- application/shared-kernel/Tests/Persistence/RepositoryTests.cs
After upgrading Rider and ReSharper to JetBrains 2024.3.4, new warnings started appearing in the editor, specifically recommending the use of `CancellationToken.None` instead of `new CancellationToken()`. 
Warnings have been fixed, and the `jetbrains.resharper.globaltools` version in the `global.json` .NET tooling file has been updated to 2024.3.4, ensuring consistency between the build server and local development environments.
Please run the `code-inspections` CLI command to detect any warnings and fix these before continuing.
> Fix JetBrains warnings and update ReSharper version to 2024.3.4

- application/AppGateway/Program.cs
- application/Directory.Packages.props
- application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
- application/back-office/WebApp/shared/lib/api/BackOffice.Api.json
Upgrade all NuGet packages to their latest versions, with a few exceptions:
- **FluentValidation** has been updated to the latest 7.x version, and a comment has been added to prevent upgrading to 8.x, as it requires a commercial license.
- **Entity Framework** remains at version 8.x due to breaking changes in 9.x that have not yet been addressed.
- **Scrutor** has not been upgraded, as the latest version caused runtime errors that need further investigation.
Entity Framework and Scrutor will be revisited in a future update once the necessary fixes are implemented.
> Upgrade NuGet packages with exceptions for FluentValidation

- application/account-management/Api/Endpoints/UserEndpoints.cs
- application/account-management/Core/Features/Authentication/Commands/CompleteLogin.cs
- application/account-management/Core/Features/Authentication/Commands/ResendLoginCode.cs
- application/account-management/Core/Features/Signups/Commands/CompleteSignup.cs
- application/account-management/Core/Features/Signups/Commands/ResendSignupCode.cs
- application/account-management/Core/Features/Users/Commands/ChangeLocale.cs
- application/account-management/Core/Features/Users/Commands/ChangeUserRole.cs
- application/account-management/Core/Features/Users/Commands/DeleteUser.cs
- application/account-management/Core/Features/Users/Commands/RemoveAvatar.cs
- application/account-management/Core/Features/Users/Commands/UpdateAvatar.cs
- application/account-management/Core/Features/Users/Commands/UpdateCurrentUser.cs
- application/account-management/Core/Features/Users/Domain/UserRepository.cs
- application/account-management/Core/Features/Users/Queries/GetCurrentUser.cs
- application/account-management/Tests/Users/GetCurrentUserTests.cs
- application/account-management/Tests/Users/UpdateCurrentUserTests.cs
- application/account-management/WebApp/routes/(index)/-components/FeatureSection4.tsx
- application/account-management/WebApp/shared/components/userModals/UserProfileModal.tsx
- application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
- application/shared-kernel/SharedKernel/Configuration/SharedDependencyConfiguration.cs
- application/shared-kernel/SharedKernel/DomainEvents/IDomainEvent.cs
Following the previous change that moved tenant-related API endpoints to `/tenants/current`, all endpoints for the logged-in user are now moved to `/users/me` for consistency. This applies to all relevant endpoints, including `GET`, `PUT`, `change-locale`, `update-avatar`, `remove-avatar`, etc. Commands, tests, and the frontend have been updated to align with this change, including the removal of obsolete tests.
Additionally, minor code cleanups have been applied:
- Simplified guards in commands to one-liners where appropriate.
- Updated `IDomainEvent` documentation to remove outdated references to the Application Layer.
- Standardized spelling by replacing British English with American English.
> Move logged-in user endpoints to /users/me and apply code cleanup

- developer-cli/Commands/AmendAsCoAuthorCommand.cs
Introduce a new `amend-as-coauthor` CLI command to easily annotate a Git commit with a co-author. This simplifies the process of making small adjustments to commits while properly crediting maintainers. The command appends a `Co-authored-by:` line to the commit message, ensuring clean and traceable contributions in PlatformPlatform.
> Add Developer CLI command to easily amend commits with co-authors

- application/global.json
Correct a mistake from the previous change where the `.NET global.json` file was wrongly moved from `/application` to `/developer-cli`. This restores `global.json` to `/application` while also upgrading the .NET SDK version from `9.0.100` to `9.0.102`.
> Restore .NET global.json in application folder and upgrade to .NET 9.0.102

- application/account-management/WebApp/shared/components/topMenu/index.tsx
- application/back-office/WebApp/shared/components/topMenu/index.tsx
- application/shared-webapp/infrastructure/translations/LocaleSwitcher.tsx
- application/shared-webapp/infrastructure/translations/Translation.tsx
Fix an issue where not all translations using `t(..)` were updated when changing the language, causing some text to remain in the previous language until a full page reload. This ensures the correct language is applied immediately across the entire UI.
Additionally, improve the **LocaleSwitcher** by enabling language changes via keyboard navigation and updating its styling to align with the rest of the UI. Spacing adjustments have also been made to the top menu buttons to prevent border cropping.
> Fix translation updates and improve LocaleSwitcher usability

- application/shared-kernel/SharedKernel/EntityFramework/SharedKernelDbContext.cs
Enable custom naming for table names as a follow-up to the **"Simplify DbContext by extracting aggregate configuration into dedicated classes"** change from a few pull requests ago. This allows more flexibility in defining table names instead of relying solely on convention-based pluralization.
> Enable custom naming for table names

- application/account-management/Core/Features/Users/Domain/UserRepository.cs
- application/account-management/WebApp/routes/admin/index.tsx
- application/account-management/WebApp/routes/admin/users/-components/UserQuerying.tsx
- application/account-management/WebApp/routes/admin/users/-components/UserTable.tsx
- application/account-management/WebApp/shared/translations/locale/da-DK.po
- application/account-management/WebApp/shared/translations/locale/en-US.po
- application/account-management/WebApp/shared/translations/locale/nl-NL.po
Update the User Summary dashboard to make the Total Users, Active Users, and Invited Users cards clickable. Clicking a card now navigates to the Users page with the relevant filter applied.
Previously, the date range picker on the Users page filtered users by their creation date. This has now been changed to filter by modified date for better accuracy. The Last Seen column in the users table has also been renamed to Modified, as it was already displaying the `ModifiedAt` property.
Additionally, the User Summary dashboard has been updated so the cards correctly adapt to dark mode, aligning with the Figma design.
> Make user summary dashboard interactive and update date filters

- application/account-management/WebApp/routes/(index)/-components/FeatureSection3.tsx
- application/account-management/WebApp/routes/(index)/-components/HeroSection.tsx
- application/account-management/WebApp/routes/admin/account/index.tsx
- application/account-management/WebApp/routes/admin/index.tsx
- application/account-management/WebApp/routes/admin/users/index.tsx
- application/account-management/WebApp/routes/login/verify.tsx
- application/account-management/WebApp/routes/signup/verify.tsx
- application/account-management/WebApp/shared/components/AvatarButton.tsx
- application/account-management/WebApp/shared/components/SharedSideMenu.tsx
- application/account-management/WebApp/shared/components/topMenu/index.tsx
- application/account-management/WebApp/shared/components/userModals/UserProfileModal.tsx
- application/account-management/WebApp/shared/layouts/HorizontalHeroLayout.tsx
- application/account-management/WebApp/shared/translations/locale/da-DK.po
- application/account-management/WebApp/shared/translations/locale/en-US.po
- application/account-management/WebApp/shared/translations/locale/nl-NL.po
- application/back-office/WebApp/routes/back-office/index.tsx
- application/back-office/WebApp/shared/components/SharedSideMenu.tsx
- application/back-office/WebApp/shared/components/topMenu/index.tsx
- application/back-office/WebApp/shared/translations/locale/da-DK.po
- application/back-office/WebApp/shared/translations/locale/en-US.po
- application/back-office/WebApp/shared/translations/locale/nl-NL.po
- application/shared-webapp/infrastructure/translations/LocaleSwitcher.tsx
- application/shared-webapp/ui/components/OneTimeCodeInput.tsx
- application/shared-webapp/ui/components/SideMenu.tsx
- application/shared-webapp/ui/theme/ThemeModeSelector.tsx
Performed a full review of translations and accessibility across the website, ensuring correct ARIA labels and consistent terminology.
- Added ARIA labels to LocaleSwitcher, ThemeModeSelector, and AvatarButton, ensuring they are always visible and correctly translated.
- Improved accessibility for one-time password input fields by adding meaningful ARIA labels.
- Updated the User Profile Modal to include proper ARIA labels and changed the placeholder example name from "Olivia Rhye" to "Alex Taylor" for a more inclusive default.
- Standardized terminology by replacing "avatar" and "photo" with "profile picture" in the User Profile dialog.
- Added an ARIA label and translation for the toggle collapsed menu button.
> Improve accessibility and translations across the UI

- developer-cli/Commands/PullPlatformPlatformChangesCommand.cs
- developer-cli/Installation/Configuration.cs
- developer-cli/Utilities/GitHelper.cs
Fix multiple issues in the `pull-platformplatform-changes` CLI command on Windows:
- Commit parsing failed due to incorrect handling of new line characters. Previously, the command split Git output using `Environment.NewLine`, which worked on Mac but not on Windows, where Git outputs `\n` instead of `\r\n`. This has been corrected to ensure proper commit recognition across operating systems.
- Fix an issue where parsing pull request descriptions containing double quotation marks (`"`) caused the command to exit without an error. The CLI now correctly handles these cases.
- Improve error handling by adding a proper error message when pushing changes to origin fails, providing better feedback to the user.
Additionally, fix a bug in the `install` command on newly installed macOS systems. …
> Fix commit parsing and improve error handling in pull-platformplatform-changes CLI command

- application/Directory.Packages.props
- application/account-management/Tests/EndpointBaseTest.cs
- application/back-office/Tests/EndpointBaseTest.cs
- application/shared-kernel/SharedKernel/Configuration/SharedInfrastructureConfiguration.cs
- application/shared-kernel/SharedKernel/EntityFramework/SharedKernelDbContext.cs
Upgrade Entity Framework Core from version 8 to 9 to address a breaking change in how database providers are registered. In EF9, `DbContextOptions<T>` should no longer be used for replacing database providers in test configurations. Instead, `IDbContextOptionsConfiguration<T>` must be used to prevent conflicts when multiple providers are registered.
Please update `EndpointBaseTest.cs` in your self-contained system like this:
```diff
- services.Remove(services.Single(d => d.ServiceType == typeof(DbContextOptions<TContext>)));
+ services.Remove(services.Single(d => d.ServiceType == typeof(IDbContextOptionsConfiguration<TContext>)));
```
> Upgrade Entity Framework Core from 8 to 9

- developer-cli/Utilities/ProcessHelper.cs
On Windows, the `start {url}` command fails with a `Command not found` error. With this change, the browser now opens correctly when parsing a URL.
> Fix error when opening URLs on Windows

- application/shared-webapp/ui/components/ComboBox.tsx
Fixes issue in ComboBox. It's content did not fill up the width of the containing element.
> Fix layout issue in ComboBox, where content did not fill the whole width

- cloud-infrastructure/cluster/main-cluster.bicep
Fixes an issue in production builds introduced in PR #696, which prevented the frontend assets from account-management from loading, as the CDN_URL environment variable needed to changed on the deployed container app.
> Fix routing to account-management frontend assets

- application/shared-kernel/SharedKernel/ApiResults/ApiResult.cs
- application/shared-kernel/Tests/ApiAssertionExtensions.cs
When a command or query has multiple validation rules on a single key, adding the error messages to the dictionary causes:
> An item with the same key has already been added. Key: 'PropertyName'
This change groups validation errors by `PropertyName` and adds all error messages to the errors dictionary.
> Allow multiple rules on a single property

- application/account-management/Api/Endpoints/UserEndpoints.cs
- application/account-management/Tests/EndpointBaseTest.cs
- application/account-management/WebApp/shared/lib/api/client.ts
- application/back-office/Tests/EndpointBaseTest.cs
- application/shared-kernel/SharedKernel/Antiforgery/AntiforgeryMiddleware.cs
- application/shared-kernel/SharedKernel/Authentication/AuthenticationTokenHttpKeys.cs
- application/shared-kernel/SharedKernel/Configuration/ApiDependencyConfiguration.cs
- application/shared-kernel/SharedKernel/Endpoints/TrackEndpoints.cs
- application/shared-kernel/SharedKernel/SinglePageApp/SinglePageAppFallbackExtensions.cs
- application/shared-webapp/build/plugin/RunTimeEnvironmentPlugin.ts
Implement antiforgery protection using ASP.NET Core’s built-in cryptographic double-submit pattern to prevent CSRF (Cross-Site Request Forgery) attacks. This mechanism generates a secure, `HttpOnly` cookie containing a server-side token and requires an `x-xsrf-token` Header in non-GET requests. The token includes the user's `ClaimUid` and is validated on every request that mutates data (`POST`, `PUT`, `DELETE`, etc.)
A new antiforgery middleware has been introduced to enforce this validation across the application, except for explicitly excluded endpoints like the Application Insights tracking API. The `upload-avatar` endpoint has been updated to remove the previous antiforgery bypass.
Additional security improvements:
- Antiforgery cookies now use the `__Host_` prefix. This special …
> Implement ASP.NET Core antiforgery protection with cryptographic double-submit pattern  

- .github/workflows/_deploy-container.yml
Fix an issue where container images were not deployed to production due to a leftover configuration from when staging and production shared a container registry. Previously, images were only pushed to the staging registry, but the production deployment did not retrieve them.
This change ensures that production images are correctly imported from the staging container registry using `az acr import`. This avoids redundant builds while ensuring that production always gets the correct image version.
Key changes:
- Removed the unused `latest` tag from the build step to prevent unintended overwrites.
- Added an `az acr import` step to pull images from the staging container registry into production.
- Introduced logic to authenticate against both staging and production Azure subscriptions.
- …
> Fix missing container image deployment to production by importing from staging registry

- .github/workflows/_deploy-container.yml
- .github/workflows/_deploy-infrastructure.yml
- .github/workflows/cloud-infrastructure.yml
- cloud-infrastructure/environment/deploy-environment.sh
- cloud-infrastructure/environment/main-environment.bicep
- developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
Fix an issue where container images were not deployed to production due to incorrect federated credentials when attempting to pull images from the staging container registry. The previous approach relied on GitHub Actions federated credentials, which failed because the production workflow was not using the correct federated credential to access staging.
To resolve this, Bicep infrastructure has been updated to grant the production service principal ACR pull permissions on the staging container registry during infrastructure deployment. This ensures that production can securely pull images from staging without requiring federated identity access.
This change makes the GitHub workflow much cleaner, as there is no longer a need for production workflows to log in to staging. However, this …
> Fix production container image deployment by granting ACR pull access via Bicep infrastructure

- .github/workflows/_deploy-container.yml
- cloud-infrastructure/environment/main-environment.bicep
- cloud-infrastructure/modules/role-assignments-container-registry-data-importer.bicep
Fix an issue preventing container images from being deployed to production due to incorrect role assignments when pulling images from the staging container registry. The previous attempt used the `ACR Pull` role, but `az acr import` requires the `Container Registry Data Importer` role instead.
Additionally:
- The `az acr import` command has been updated to use the correct `--registry` parameter, specifying the Azure Resource Manager path instead of the FQDN.
- A new Bicep module (`role-assignments-container-registry-data-importer.bicep`) has been introduced to assign the correct role.
- The role assignment for the production service principal to the staging container registry is now configured to await ACR creation to prevent deployment failures on first-time setup.
> Fix container deployment to production by using correct Azure role and registry parameters

- cloud-infrastructure/cluster/main-cluster.bicep
- cloud-infrastructure/environment/main-environment.bicep
- cloud-infrastructure/modules/communication-services.bicep
- cloud-infrastructure/modules/container-app.bicep
- cloud-infrastructure/modules/container-apps-environment.bicep
- cloud-infrastructure/modules/log-analytics-workspace.bicep
- cloud-infrastructure/modules/managed-certificate.bicep
- cloud-infrastructure/modules/role-assignments-storage-blob-data-contributor.bicep
- cloud-infrastructure/modules/role-assignments-storage-blob-data-reader.bicep
- cloud-infrastructure/modules/storage-account.bicep
- cloud-infrastructure/modules/user-assigned-managed-identity.bicep
- cloud-infrastructure/modules/virtual-network.bicep
Update Azure Container Apps infrastructure to automatically configures .NET data protection. This ensures that encryption keys used for antiforgery tokens, authentication cookies, and other protected state are securely managed and automatically shared between containers in the same Azure Container Apps Environment.
To enable this feature, the container app module now includes:
```bicep
runtime: {
dotnet: {
autoConfigureDataProtection: true
}
}
```
All Bicep modules have also been upgraded to the latest stable API versions.
This infrastructure change must be merged and deployed to Azure environments before the upcoming .NET changes that rely on shared data protection keys across containers.
> Enable Azure Container Apps auto-configuration for .NET data protection

- application/account-management/Api/Endpoints/AuthenticationEndpoints.cs
- application/account-management/WebApp/bootstrap.tsx
- application/account-management/WebApp/shared/lib/api/client.ts
- application/back-office/WebApp/bootstrap.tsx
- application/back-office/WebApp/shared/lib/api/client.ts
- application/shared-kernel/SharedKernel/Configuration/ApiDependencyConfiguration.cs
- application/shared-webapp/infrastructure/http/antiforgeryTokenHandler.ts
- application/shared-webapp/infrastructure/translations/LocaleSwitcher.tsx
Resolve several issues introduced by the recent addition of antiforgery protection and improve cross-system compatibility in PlatformPlatform.
Fixes and improvements include:
1. The internal `/internal-api/account-management/authentication/refresh-authentication-tokens` endpoint now explicitly disables antiforgery checks, as it did not receive the required antiforgery cookie or header, causing users to be logged out when trying to refresh the access token.
2. Antiforgery logic has been extracted into a shared module in the web app infrastructure. This provides:
- A reusable fetch wrapper that automatically adds the antiforgery token for non-GET requests.
- A reusable middleware for TanStack Query (`openapi-fetch`) clients.
- Simpler integration in LocaleSwitcher and other components …
> Fix critical antiforgery issue and ensure compatibility of self-contained systems

- .github/workflows/_deploy-container.yml
- .github/workflows/_deploy-infrastructure.yml
- .github/workflows/_migrate-database.yml
- .github/workflows/account-management.yml
- .github/workflows/app-gateway.yml
- .github/workflows/back-office.yml
- .github/workflows/cloud-infrastructure.yml
- .github/workflows/pull-request-conventions.yml
- application/Directory.Packages.props
- application/account-management/Api/AccountManagement.Api.csproj
- application/account-management/Core/Database/DatabaseMigrations.cs
- application/account-management/Directory.Build.props
- application/account-management/Workers/Program.cs
- application/back-office/Api/BackOffice.Api.csproj
- application/back-office/Core/Database/DatabaseMigrations.cs
- application/back-office/Directory.Build.props
- application/back-office/Workers/Program.cs
- application/dotnet-tools.json
- application/shared-kernel/SharedKernel/SharedKernel.csproj
- cloud-infrastructure/cluster/firewall.sh
- cloud-infrastructure/cluster/grant-database-permissions.sh
- developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
This change moves database migrations from Workers to GitHub Workflow actions, with a preview and approval flow for database changes:
- Create a new reusable `_migrate-database.yml` workflow that detects and applies pending migrations using .NET tools for Entity Framework Core (`dotnet ef migrations`) 
- Restructure GitHub workflows to include separate steps for previewing pending database changes with approval gates
- Modify worker services to only run migrations in local development, not in Azure environments
- Improve firewall scripts to scope rules at the database level, allowing multiple GitHub workflows to run in parallel
- Update workflow naming conventions and job titles for consistency and clarity
The CI/CD workflow has been extended from 3 jobs to 7 jobs for self-contained …
> Move database migrations to CI/CD with SQL preview on pull requests and approval workflow

- developer-cli/Commands/TranslateCommand.cs
Update the `translate` CLI command to translate all `.po` files that are missing translations by default.
Add a new `--self-contained-system` flag (alias `-s`) that will scope the translations to only translate files for one self-contained system.
Sample usage:
```bash
pp translate # Translates all files  
pp translate -s back-office # Translates all files for Back Office  
pp translate -l da-DK # Translates only Danish files  
pp translate -s back-office -l da-DK # Translates Danish files for Back Office
```
> Extend translate CLI command to default to all languages and add option for translating only one self-contained system

- .ai-rules/frontend/translations.md
- application/account-management/WebApp/routes/admin/account/-components/DeleteAccountConfirmation.tsx
- application/account-management/WebApp/routes/admin/account/index.tsx
- application/account-management/WebApp/routes/admin/index.tsx
- application/account-management/WebApp/routes/admin/users/-components/InviteUserModal.tsx
- application/account-management/WebApp/routes/admin/users/-components/UserQuerying.tsx
- application/account-management/WebApp/routes/admin/users/-components/UserTable.tsx
- application/account-management/WebApp/routes/admin/users/index.tsx
- application/account-management/WebApp/routes/signup/index.tsx
- application/account-management/WebApp/shared/components/userModals/UserProfileModal.tsx
- application/account-management/WebApp/shared/translations/locale/da-DK.po
- application/account-management/WebApp/shared/translations/locale/en-US.po
- application/account-management/WebApp/shared/translations/locale/nl-NL.po
- application/back-office/WebApp/shared/components/SharedSideMenu.tsx
- application/back-office/WebApp/shared/translations/locale/da-DK.po
- application/back-office/WebApp/shared/translations/locale/en-US.po
- application/back-office/WebApp/shared/translations/locale/nl-NL.po
Update all UI text to consistently use `Sentence case` instead of `Title Case` for a more modern and consistent interface. This change affects:
- Buttons (e.g. "Delete account" instead of "Delete Account")
- Menu items (e.g. "View profile" instead of "View Profile")
- Headings (e.g. "Account settings" instead of "Account Settings")
- Form labels (e.g. "User role" instead of "User Role")
- Placeholders (e.g. "Software engineer" instead of "Software Engineer")
The change also updates the translation AI rules to explicitly specify that buttons, menus, and headings must use sentence case.
For maintainers of downstream projects, you should:
1. Update your UI text
Look in your `.po` files and identify all places you use `Title Case`, then find the places in your code where the translation is …
> Update all UI texts to consistently use sentence case instead of title case

- .cursor/mcp.json
- developer-cli/Commands/BrowserToolsCommand.cs
Add Model Context Protocol (MCP) server configuration for Cursor AI to improve AI-assisted development workflows.
This configuration is specific to Cursor. In other AI editors like Windsurf, setting up MCP servers must currently be done manually.
- Add configuration for the Sequential Thinking MCP server  
Enables AI editors like Cursor to maintain task-aware state, improving how the assistant breaks down and sequences actions to solve large, complex tasks.
- Add configuration for the Browser Tools MCP server in the new `.cursor` folder  
Allows Cursor to inspect Chrome-based browsers directly, making it possible to see console output, network errors, DOM state, and even take screenshots without switching context.
- Add Developer CLI command: `pp browser-tools` (or shorthand `pp bt`) …
> Add Sequential Thinking Context Protocol and Browser Tools MCP server configuration for Cursor AI

- application/account-management/Api/Endpoints/UserEndpoints.cs
- application/account-management/Core/Features/TelemetryEvents.cs
- application/account-management/Core/Features/Users/Commands/BulkDeleteUsers.cs
- application/account-management/Core/Features/Users/Domain/UserRepository.cs
- application/account-management/Tests/Users/BulkDeleteUsersTests.cs
- application/account-management/WebApp/routes/admin/users/-components/ChangeUserRoleDialog.tsx
- application/account-management/WebApp/routes/admin/users/-components/DeleteUserDialog.tsx
- application/account-management/WebApp/routes/admin/users/-components/InviteUserDialog.tsx
- application/account-management/WebApp/routes/admin/users/-components/UserQuerying.tsx
- application/account-management/WebApp/routes/admin/users/-components/UserTable.tsx
- application/account-management/WebApp/routes/admin/users/-components/UserToolbar.tsx
- application/account-management/WebApp/routes/admin/users/index.tsx
- application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
- application/account-management/WebApp/shared/translations/locale/da-DK.po
- application/account-management/WebApp/shared/translations/locale/en-US.po
- application/account-management/WebApp/shared/translations/locale/nl-NL.po
- application/shared-kernel/SharedKernel/Domain/IBulkRemoveRepository.cs
- application/shared-kernel/SharedKernel/Persistence/RepositoryBase.cs
- application/shared-webapp/infrastructure/translations/TranslationContext.tsx
Add support for bulk deletion of users and improve the user management interface.
- Implement backend support for bulk user deletion with validation and telemetry tracking
- Add `IBulkRemoveRepository` interface and implement it in `RepositoryBase` to support efficient bulk operations
- Create new `UserToolbar` component to manage user actions and selection
- Extract user role change and deletion logic into separate dialog components for reusability
- Rename `InviteUserModal` to `InviteUserDialog` for consistency with other UI components
- Add multi-select support to the user table to enable bulk operations
- Update translations for new bulk deletion UI elements
These changes improve the user management workflow by allowing administrators to delete multiple users at once while preserving …
> Add bulk user deletion functionality and refactor user management UI

- application/account-management/WebApp/routes/__root.tsx
- application/account-management/WebApp/routes/admin/users/-components/ChangeUserRoleDialog.tsx
- application/account-management/WebApp/routes/admin/users/-components/DeleteUserDialog.tsx
- application/account-management/WebApp/routes/admin/users/-components/InviteUserDialog.tsx
- application/account-management/WebApp/routes/admin/users/-components/UserTable.tsx
- application/account-management/WebApp/routes/admin/users/-components/UserToolbar.tsx
- application/account-management/WebApp/routes/admin/users/index.tsx
- application/account-management/WebApp/shared/components/AvatarButton.tsx
- application/account-management/WebApp/shared/lib/api/client.ts
- application/back-office/WebApp/routes/__root.tsx
- application/back-office/WebApp/shared/lib/api/client.ts
Configure TanStack's global query cache invalidation to automatically refresh data after mutations, eliminating the need for manual cache management. When mutation endpoints (`POST`, `PUT`, `DELETE`) are called, all data in the active UI is automatically refreshed. While this may result in too many `GET` calls, it significantly simplifies the frontend code and ensures the UI is always up-to-date.
- Configure `QueryClient` with `MutationCache` to invalidate all queries on successful mutations
- Remove manual query refetching and state updates after mutations in user management
- Simplify component props by removing redundant refresh callbacks
- Simplify logout logic by using TanStack's `onSuccess` for redirect trigger
This change introduces a recommended pattern for handling cache …
> Configure global query cache invalidation for TanStack

- application/account-management/Core/Database/Migrations/20250217000000_Initial.cs
- application/account-management/Core/Database/Migrations/20250402000000_CascadeDeleteLogins.cs
- application/account-management/Core/Features/Authentication/Domain/LoginConfiguration.cs
- application/account-management/Core/Features/TelemetryEvents.cs
- application/account-management/Core/Features/Tenants/Commands/DeleteTenant.cs
- application/account-management/Core/Features/Users/Domain/UserRepository.cs
- application/account-management/Tests/Users/DeleteUserTests.cs
- application/back-office/Core/Database/Migrations/20250217000000_Initial.cs
Fix a bug where both user and tenant deletion fails due to foreign key constraints when users have login history or a tenant has users. The fix is implemented in two different ways:
1. User deletion: Add cascade delete to the `Logins` table foreign key to automatically remove login records when a user is deleted, since login history is less critical.
2. Tenant deletion: Add bulk deletion of users to properly clean up tenant data, deliberately avoiding cascade delete for better control and safety in case of accidental tenant deletion.
Additional changes:
- Track the number of users deleted in the `TenantDeleted` telemetry event to monitor the impact of tenant deletions
- Move database migrations to a `Migrations` namespace and rename files to match Entity Framework conventions
- Add a test …
> Fix foreign key constraints when deleting users and tenants 

- application/account-management/Tests/Authentication/CompleteLoginTests.cs
- application/account-management/Tests/Signups/CompleteSignupTests.cs
- application/account-management/Tests/Signups/StartSignupTests.cs
- application/account-management/Tests/Tenants/DeleteTenantTests.cs
- application/account-management/Tests/Users/BulkDeleteUsersTests.cs
- application/account-management/Tests/Users/DeleteUserTests.cs
- application/account-management/Tests/Users/GetUsersTests.cs
- developer-cli/Commands/BuildCommand.cs
- developer-cli/Commands/CheckCommand.cs
- developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
- developer-cli/Commands/FormatCommand.cs
- developer-cli/Commands/InspectCommand.cs
Time-based tests were failing on Windows machines.
- Use `TimeProvider` in tests to get consistent results and ensure the tests pass reliably
- Replace all usages of `Stopwatch.StartNew()` with `Stopwatch.GetTimestamp()` to reduce allocations and follow the recommended approach
Update tests to use `TimeProvider.System.GetUtcNow()` instead of `DateTime.UtcNow()`.
> Use consistent time provider

- application/AppHost/AppHost.csproj
- application/AppHost/Program.cs
- application/Directory.Packages.props
- application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
- application/back-office/WebApp/shared/lib/api/BackOffice.Api.json
- application/dotnet-tools.json
- application/shared-kernel/SharedKernel/PipelineBehaviors/PublishDomainEventsPipelineBehavior.cs
- application/shared-kernel/SharedKernel/PipelineBehaviors/PublishTelemetryEventsPipelineBehavior.cs
- application/shared-kernel/SharedKernel/PipelineBehaviors/UnitOfWorkPipelineBehavior.cs
- application/shared-kernel/SharedKernel/PipelineBehaviors/ValidationPipelineBehavior.cs
Upgrade .NET Aspire to version 9.2.0 and enhance the Aspire dashboard with friendly URLs:
- Add friendly URLs for `WebApp`, `Back Office`, `Open API`, and mail server (a debug-time link to read mail)
- Remove `IsAspireHost` property from `AppHost.csproj`, no longer needed with .NET Aspire 9.2.0
- Add `aspire.cli` .NET tool version 9.2.0-preview.1 to enable `dotnet tool run aspire run`
- Upgrade all NuGet packages to their latest compatible versions, including Aspire packages
Consider enhancing the Aspire dashboard with friendly URLs for your self-contained system:
```csharp
appGateway.WithUrl($"{appGateway.GetEndpoint("https")}/your-self-contained-system", "Your System Name");
```
> Upgrade to .NET Aspire 9.2.0 and add friendly URLs to dashboard

- .gitignore
- application/AppGateway/Middleware/AuthenticationCookieMiddleware.cs
- application/account-management/Tests/Authentication/CompleteLoginTests.cs
- application/account-management/Tests/Signups/CompleteSignupTests.cs
- application/account-management/Tests/Users/InviteUserTests.cs
- application/shared-kernel/Tests/Persistence/SqliteConnectionExtensions.cs
- developer-cli/Utilities/GitHelper.cs
Update SQLite extension methods to improve type safety and add new functionality for tests:
- Add `Update` method for modifying existing rows with proper type handling
- Add `Delete` method for removing rows from SQLite tables
- Add `ExecuteScalar<T>` generic method to allow strong typing of SQL query results
- Mark the old `ExecuteScalar` method as obsolete to encourage migration to the generic version
Additional improvements:
- Fix bug in `GitHelper.GetChangedFiles()` to properly handle empty directories
- Add `.run` directory used by JetBrains Rider to `.gitignore`
- Remove obsolete check for refresh token in `AuthenticationCookieMiddleware`
> Improve SQLite extension methods and remove obsolete code

- .github/workflows/_deploy-container.yml
- .github/workflows/_deploy-infrastructure.yml
- .github/workflows/_migrate-database.yml
- .github/workflows/account-management.yml
- .github/workflows/app-gateway.yml
- .github/workflows/back-office.yml
- .github/workflows/pull-request-conventions.yml
- Replace all hardcoded `dotnet-version: 9.0.x` values in GitHub workflows with a reference to the centralized `global.json` file for consistent .NET versioning
- Reformat GitHub workflow files to use consistent indentation around blank lines
This change fixes a sporadic error where the actions/setup-dotnet@v4 GitHub task sometimes installed an incorrect .NET version, causing workflows to fail.
Update all GitHub workflow files to reference the `global.json` file instead of hardcoded versions:
```diff
- dotnet-version: 9.0.x
+ global-json-file: application/global.json
```
> Upgrade GitHub workflows to use centralized global.json for .NET version

- application/shared-webapp/ui/components/TextArea.tsx
Add TextArea component to the shared webapp UI components. It's a multi line resizable text field with a `rows` prop used to set the default size. See [React Aria documentaion](https://reactspectrum.blob.core.windows.net/reactspectrum/709eab2068e13a1bd147cdceb6217aedfd0ec5be/docs/react-aria/useTextField.html#text-area).
> Add TextArea shared webapp component

- .vscode/settings.json
- biome.json
Fix the issue with Biome code formatting when working with tools like VS Code, Cursor, and Windsurf from the root of the mono repository. Since Biome settings is located under `application/biome.json`, Biome used default settings, including tabs instead of spaces.
- Add symbolic link to `biome.json` in the repository root that points to `application/biome.json`, ensuring code editors can locate the configuration when the root directory is opened.
- Correct the `biome.lspBin` path in VS Code settings from `./application/node_modules/.bin/workspace-biome` to `./application/node_modules/.bin/biome`, addressing an invalid path that prevented the Biome language server from functioning properly.
> Fix Biome formatter configuration and add symbolic link for editor integration

- application/AppHost/SslCertificateManager.cs
Add certificate expiration check in the Aspire AppHost to prevent startup failures due to expired SSL certificates. Previously, if the localhost certificate expired, the application would fail to start without a clear error message or automatic recovery.
> Check SSL certificate expiration and renew automatically in Aspire AppHost

- .github/workflows/_deploy-container.yml
- .github/workflows/_deploy-infrastructure.yml
- .github/workflows/cloud-infrastructure.yml
Fix GitHub Actions workflow issues with deployment to staging environments from pull requests. Previously, two bugs were preventing proper deployment:
- Fix infrastructure planning step that was failing to run on pull requests with the "Deploy to Staging" label.
- Fix application code deployment to staging that was blocked when the "Deploy to Staging" label was set on a pull request.
> Change GitHub action condition to display infrastructure changes on pull requests

- application/shared-webapp/infrastructure/http/queryClient.ts
Fix a bug introduced in the previous change where query cache invalidation did not occur automatically after a successful mutation. This resulted in stale UI state after mutations (`POST`, `PUT`, `DELETE`).
- Add an `onSuccess` handler to the MutationCache configuration to automatically invalidate all queries on mutation success
> Restore logic to invalidate all queries globally after a successful mutation

- developer-cli/Commands/TranslateCommand.cs
- developer-cli/DeveloperCli.csproj
Add support for Azure OpenAI as an alternative to standard OpenAI for translations in the Developer CLI.
- Add Azure OpenAI client integration for custom endpoints
- Enhance API key validation to support both standard OpenAI (sk-...) and Azure OpenAI keys
- Add interactive prompt for Azure OpenAI endpoint URL when Azure key is detected
- Store Azure OpenAI endpoint in secrets alongside the API key
> Add option to use Azure OpenAI for translations

- application/account-management/WebApp/bootstrap.tsx
- application/back-office/WebApp/bootstrap.tsx
- application/shared-webapp/infrastructure/http/errorHandler.ts
- application/shared-webapp/infrastructure/http/httpClient.ts
- application/shared-webapp/infrastructure/http/queryClient.ts
Changes error handling to allow application code to catch and handle errors, overriding the error handling, which shows toast notifications to the user. Toasts are no longer shown in `handleError`, but instead from a global error handler that catches unhandled exceptions.
Validation errors (HTTP 400) are now only suppressed in mutations. Furthermore, mutations can override error handling by specifying a custom `onError` handler.
Global error handling needs to be enabled in each frontend project. Edit `bootstrap.tsx`, adding a call to `setupGlobalErrorHandlers` before the `reactDom.createRoot` line:
```diff
+import { setupGlobalErrorHandlers } from "@repo/infrastructure/http/errorHandler";
...
+setupGlobalErrorHandlers();
+
reactDom.createRoot(rootElement).render(
```
> Show error toasts only for unhandled errors

- developer-cli/Commands/TranslateCommand.cs
Removes the regular expression in the title of the text prompt.
The regular expression is picked up as a color code and causes the following error:
> Translation failed. Could not find color or style 'a-z0-9'.
> Fix translate CLI command

- application/AppHost/Program.cs
- developer-cli/Commands/WatchCommand.cs
- developer-cli/Installation/ChangeDetection.cs
- developer-cli/Utilities/ProcessHelper.cs
Add a new `watch` command to the developer CLI that manages the Aspire AppHost lifecycle. The command provides a convenient way to start, stop, and monitor the Aspire application host with support for both attached and detached modes.
- Create `watch` command with options for `--force`, `--stop`, `--attach/-a`, and `--detach/-d modes`
- Automatically detect and kill all .NET processes in the project when stopping
- Add `--public-url` parameter to set PUBLIC_URL environment variable for external device testing using e.g. ngrok and Tailscale
- Implement automatic ngrok tunnel startup when using ngrok URLs with the watch command
- Add port conflict detection in AppHost with user-friendly warnings when ports are already in use
> Add watch CLI command to manage Aspire AppHost lifecycle

- application/account-management/WebApp/routes/admin/account/index.tsx
- application/account-management/WebApp/routes/admin/users/-components/ChangeUserRoleDialog.tsx
- application/account-management/WebApp/routes/admin/users/-components/DeleteUserDialog.tsx
- application/account-management/WebApp/routes/admin/users/-components/InviteUserDialog.tsx
- application/account-management/WebApp/shared/components/userModals/UserProfileModal.tsx
- application/account-management/WebApp/shared/translations/locale/da-DK.po
- application/account-management/WebApp/shared/translations/locale/en-US.po
- application/account-management/WebApp/shared/translations/locale/nl-NL.po
- application/shared-webapp/infrastructure/http/errorHandler.ts
- application/shared-webapp/ui/components/Toast.tsx
- application/shared-webapp/ui/hooks/useToast.ts
Centralize toast notification timeout configuration and add success toasts for all mutation operations to provide consistent user feedback across the application. Toast notifications now appear in the upper right corner with centralized duration settings based on notification type (info: 4s, success: 4s, warning: 6s, error: 10s).
- Introduce centralized `DEFAULT_TOAST_DURATIONS` configuration for consistent toast display times.
- Add success toast notifications for all mutations: changing user roles, deleting users, inviting users, updating profiles, and modifying account information.
- Move toast container to upper right corner for better visibility and stack new toasts below existing ones.
- Standardize toast variants to info, success, warning, and error (removing neutral and danger).
- …
> Centralize toast notification configuration and add success toasts for all mutations

- application/account-management/WebApp/routes/__root.tsx
- application/back-office/WebApp/routes/__root.tsx
- application/shared-kernel/SharedKernel/Endpoints/TrackEndpoints.cs
- application/shared-webapp/infrastructure/applicationInsights/ApplicationInsightsProvider.tsx
- application/shared-webapp/infrastructure/applicationInsights/PageTracker.tsx
- application/shared-webapp/infrastructure/http/errorHandler.ts
Fix duplicate page view tracking that occurred when navigating between pages in the single-page application. Application Insights' enableAutoRouteTracking feature was causing duplicate tracking with TanStack Router because both systems independently detected navigation events.
- Disable enableAutoRouteTracking in Application Insights configuration
- Create custom PageTracker component that integrates properly with TanStack Router
- Track initial page load and subsequent navigations without duplicates
- Maintain existing JavaScript error tracking functionality
The enableAutoRouteTracking feature is designed for React Router and listens to browser history changes (popstate, pushState/replaceState, hashchange). Since TanStack Router also manipulates browser history, both were detecting the …
> Fix duplicate page navigation tracking in Application Insights

- .cursor/rules/tools.mdc
- .windsurf/rules/tools.md
- application/account-management/Tests/EndpointBaseTest.cs
- application/back-office/Tests/EndpointBaseTest.cs
- developer-cli/Commands/End2EndCommand.cs
- developer-cli/Installation/PlaywrightInstaller.cs
- developer-cli/Program.cs
- developer-cli/Utilities/CommandLineArgumentsPreprocessor.cs
- developer-cli/Utilities/SelfContainedSystemHelper.cs
This change adds a new `e2e` command to the developer CLI that provides a streamlined way to run Playwright end-to-end tests which will be introduce in the next change. The command offers comprehensive test execution capabilities with smart defaults and extensive configuration options.
Key features:
- Automatic server availability checking before running tests
- Support for running tests across multiple self-contained systems
- Flexible test filtering by search terms, tags (@smoke, @comprehensive), or file patterns
- Browser selection (chromium, firefox, webkit, safari, all)
- Interactive debugging with Playwright Inspector
- Performance analysis with timing output
- Test artifacts management (videos, traces, reports)
- Smart test retry logic for flaky tests
- Parallel test execution with …
> Add end-to-end test command to developer CLI with comprehensive Playwright integration
